# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ABTestPostTestActions do
  use MetaAds.Model

  field("auto_change_budget_to_winner", "int", [])
  field("winner_budget", "string", [])

  finish()
end
