# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetFeedSpecBody do
  use MetaAds.Model

  field("adlabels", "list<AdAssetFeedSpecAssetLabel>", [])
  field("text", "string", [])
  field("url_tags", "string", [])

  finish()
end
