# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetTargetRuleTargeting do
  use MetaAds.Model

  field("age_max", "unsigned int", [])
  field("age_min", "unsigned int", [])
  field("audience_network_positions", "list<string>", [])
  field("device_platforms", "list<AdAssetTargetRuleTargeting_device_platforms>", [])
  field("facebook_positions", "list<string>", [])
  field("geo_locations", "TargetingGeoLocation", [])
  field("instagram_positions", "list<string>", [])
  field("publisher_platforms", "list<string>", [])
  field("threads_positions", "list<string>", [])
  field("whatsapp_positions", "list<string>", [])

  finish()
end
