# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountPaymentDetails do
  use MetaAds.Model

  field("amount", "CurrencyAmount", [])
  field("create_date", "int", [])
  field("id", "string", [])
  field("last_action_status", "string", [])
  field("metadata", "Object", [])
  field("payment_details_id", "string", [])

  finish()
end
