# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetOnsiteDestinations do
  use MetaAds.Model

  field("auto_optimization", "string", [])
  field("details_page_product_id", "string", [])
  field("shop_collection_product_set_id", "string", [])
  field("source", "string", [])
  field("storefront_shop_id", "string", [])

  finish()
end
