# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountDefaultDestination do
  use MetaAds.Model

  field("destination_id", "string", [])
  field("destination_url", "string", [])

  finish()
end
