# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountURLForAssetExtraction do
  use MetaAds.Model

  field("source_type", "string", [])
  field("source_url", "string", [])

  finish()
end
