# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountAdLimitsInsights do
  use MetaAds.Model

  field("date_start", "string", [])
  field("date_stop", "string", [])

  finish()
end
