# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountDeliveryEstimate do
  use MetaAds.Model

  field("estimate_mau_lower_bound", "int", [])
  field("estimate_mau_upper_bound", "int", [])
  field("estimate_ready", "bool", [])
  field("targeting_optimization_types", "list<map<string, int>>", [])

  finish()
end
