# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountIosFourteenCampaignLimits do
  use MetaAds.Model

  field("campaign_group_limit", "int", [])
  field("campaign_group_limits_details", "list<Object>", [])
  field("campaign_limit", "int", [])

  finish()
end
