# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountLiveVideoAdvertiser do
  use MetaAds.Model

  field("ig_lva_default_duration_s", "int", [])
  field("is_lva_toggle_on", "bool", [])
  field("lva_default_budget", "int", [])
  field("lva_default_duration_s", "int", [])
  field("should_default_current_live", "bool", [])
  field("should_default_scheduled_live", "bool", [])
  field("should_default_toggle_on_from_model", "bool", [])
  field("should_show_lva_toggle", "bool", [])

  finish()
end
