# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetImage do
  use MetaAds.Model

  field("hash", "string", [])
  field("id", "string", [])
  field("image_crops", "AdsImageCrops", [])
  field("name", "string", [])
  field("tag", "string", [])
  field("url", "string", [])
  field("url_tags", "string", [])

  finish()
end
