# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetFeedSpecCarousel do
  use MetaAds.Model

  field("adlabels", "list<AdAssetFeedSpecAssetLabel>", [])
  field("child_attachments", "list<AdAssetFeedSpecCarouselChildAttachment>", [])
  field("multi_share_end_card", "bool", [])
  field("multi_share_optimized", "bool", [])

  finish()
end
