# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountRecommendedCamapaignBudget do
  use MetaAds.Model

  field("daily", "string", [])
  field("lifetime", "string", [])
  field("objective", "string", [])

  finish()
end
