# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetFeedAdditionalDataPageNudgeMessage do
  use MetaAds.Model

  field("enabled", "bool", [])
  field("quick_replies", "list<Object>", [])
  field("text", "string", [])

  finish()
end
