# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountAdRulesCountByType do
  use MetaAds.Model

  field("count", "int", [])
  field("evaluation_type", "string", [])

  finish()
end
