# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetLinkURL do
  use MetaAds.Model

  field("android_deeplink_url", "string", [])
  field("carousel_see_more_url", "string", [])
  field("deeplink_url", "string", [])
  field("display_url", "string", [])
  field("id", "string", [])
  field("ipad_deeplink_url", "string", [])
  field("iphone_deeplink_url", "string", [])
  field("url_tags", "string", [])
  field("website_url", "string", [])

  finish()
end
