# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAsyncRequest do
  use MetaAds.Model

  field("async_request_set", "AdAsyncRequestSet", [])
  field("created_time", "datetime", [])
  field("id", "string", [])
  field("input", "map", [])
  field("result", "map", [])
  field("scope_object_id", "string", [])
  field("status", "string", [])
  field("type", "string", [])
  field("updated_time", "datetime", [])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
