# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetFeedAdditionalDataReconsiderationOffer do
  use MetaAds.Model

  field("offer_id", "string", [])
  field("offer_name", "string", [])

  finish()
end
