# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountCampaignAttributionOptionInfo do
  use MetaAds.Model

  field("is_eligible", "bool", [])
  field("value", "string", [])

  finish()
end
