# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAssetFeedSpecAssetCustomizationRule do
  use MetaAds.Model

  field("body_label", "AdAssetFeedSpecAssetLabel", [])
  field("call_to_action_label", "AdAssetFeedSpecAssetLabel", [])
  field("call_to_action_type_label", "AdAssetFeedSpecAssetLabel", [])
  field("caption_label", "AdAssetFeedSpecAssetLabel", [])
  field("carousel_label", "AdAssetFeedSpecAssetLabel", [])
  field("customization_spec", "AdAssetCustomizationRuleCustomizationSpec", [])
  field("description_label", "AdAssetFeedSpecAssetLabel", [])
  field("image_label", "AdAssetFeedSpecAssetLabel", [])
  field("is_default", "bool", [])
  field("link_url_label", "AdAssetFeedSpecAssetLabel", [])
  field("priority", "int", [])
  field("title_label", "AdAssetFeedSpecAssetLabel", [])
  field("video_label", "AdAssetFeedSpecAssetLabel", [])

  finish()
end
