# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountAdsRecommendedAudios do
  use MetaAds.Model

  field("audio_assets", "list<int>", [])

  finish()
end
