# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountYouthAdsAdvertiser do
  use MetaAds.Model

  field("is_youth_ads_advertiser", "bool", [])

  finish()
end
