# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountCreativeStickersPost do
  use MetaAds.Model

  field("id", "string", [])
  field("status", "string", [])
  field("success", "bool", [])

  finish()
end
