# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountBankInfoList do
  use MetaAds.Model

  field("banks", "list<Object>", [])

  finish()
end
