# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountCustomAudienceLimits do
  use MetaAds.Model

  field("audience_update_quota_in_total", "int", [])
  field("audience_update_quota_left", "float", [])
  field("has_hit_audience_update_limit", "bool", [])
  field("next_audience_update_available_time", "string", [])
  field("rate_limit_reset_time", "string", [])

  finish()
end
