# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountPrepayDetails do
  use MetaAds.Model

  field("default_funding_amount", "CurrencyAmount", [])
  field("max_acceptable_amount", "CurrencyAmount", [])
  field("min_acceptable_amount", "CurrencyAmount", [])
  field("should_collect_business_details", "bool", [])

  finish()
end
