# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountMarketingMessagesSettings do
  use MetaAds.Model

  field("whatsapp_activation_status", "string", [])

  finish()
end
