# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountAdVolume do
  use MetaAds.Model

  field("actor_id", "string", [])
  field("actor_name", "string", [])
  field("ad_limit_scope_business", "Business", [])
  field("ad_limit_scope_business_manager_id", "string", [])
  field("ad_limit_set_by_page_admin", "unsigned int", [])
  field("ads_running_or_in_review_count", "unsigned int", [])
  field("ads_running_or_in_review_count_subject_to_limit_set_by_page", "unsigned int", [])
  field("current_account_ads_running_or_in_review_count", "unsigned int", [])
  field("future_limit_activation_date", "string", [])
  field("future_limit_on_ads_running_or_in_review", "unsigned int", [])
  field("limit_on_ads_running_or_in_review", "unsigned int", [])
  field("recommendations", "list<Object>", [])

  finish()
end
