# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountInsightsFeatureSettingsPost do
  use MetaAds.Model

  field("id", "string", [])

  finish()
end
