# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdAccountUser do
  use MetaAds.Model

  field("id", "string", [])
  field("name", "string", [])
  field("tasks", "list<string>", [])

  finish()
end
