# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdBidAdjustments do
  use MetaAds.Model

  field("age_range", "map<string, float>", [])
  field("page_types", "Object", [])
  field("user_groups", "string", [])

  finish()
end
