# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignPlacement do
  use MetaAds.Model

  operation(:get, "GET", "", "ad_campaign_placement", [
    %{"name" => "account_id", "required" => true, "type" => "string"},
    %{"name" => "billing_event", "required" => true, "type" => "string"},
    %{"name" => "buying_type", "required" => true, "type" => "string"},
    %{"name" => "destination_type", "required" => false, "type" => "string"},
    %{"name" => "has_dynamic_creative", "required" => false, "type" => "bool"},
    %{"name" => "metadata", "required" => false, "type" => "bool"},
    %{"name" => "objective", "required" => true, "type" => "string"},
    %{"name" => "optimization_goal", "required" => true, "type" => "string"},
    %{"name" => "promoted_object", "required" => false, "type" => "string"}
  ])

  finish()
end
