# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignFrequencyControlSpecs do
  use MetaAds.Model

  field("event", "string", [])
  field("interval_days", "unsigned int", [])
  field("max_frequency", "unsigned int", [])
  field("type", "string", [])

  finish()
end
