# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCustomDerivedMetrics do
  use MetaAds.Model

  field("ad_account_id", "string", [])
  field("business", "Business", [])
  field("creation_time", "datetime", [])
  field("creator", "Profile", [])
  field("custom_derived_metric_type", "string", [])
  field("deletion_time", "datetime", [])
  field("deletor", "Profile", [])
  field("description", "string", [])
  field("format_type", "string", [])
  field("formula", "string", [])
  field("has_attribution_windows", "bool", [])
  field("has_inline_attribution_window", "bool", [])
  field("id", "string", [])
  field("name", "string", [])
  field("permission", "string", [])
  field("saved_report_id", "string", [])
  field("scope", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
