# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignGoal do
  use MetaAds.Model

  field("engaged_audiences_audience_label_exclusions", "list<string>", [])
  field("engaged_audiences_audience_label_inclusions", "list<string>", [])
  field("engaged_audiences_exclusions", "list<string>", [])
  field("engaged_audiences_inclusions", "list<string>", [])
  field("existing_customers_audience_label_exclusions", "list<string>", [])
  field("existing_customers_audience_label_inclusions", "list<string>", [])
  field("existing_customers_exclusions", "list<string>", [])
  field("existing_customers_inclusions", "list<string>", [])
  field("is_ca_expansion_enabled", "bool", [])
  field("is_lookalike_inclusion_enabled", "bool", [])
  field("lookalike_inclusions", "list<string>", [])
  field("type", "int", [])

  finish()
end
