# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeLinkDataAppLinkSpec do
  use MetaAds.Model

  field("android", "list<AndroidAppLink>", [])
  field("ios", "list<IosAppLink>", [])
  field("ipad", "list<IosAppLink>", [])
  field("iphone", "list<IosAppLink>", [])

  finish()
end
