# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeFeatureDetails do
  use MetaAds.Model

  field("customizations", "AdCreativeFeatureCustomizations", [])
  field("enroll_status", "string", [])

  finish()
end
