# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeAutomationSpec do
  use MetaAds.Model

  field("decision_type", "string", [])
  field("enrollment_status", "string", [])

  finish()
end
