# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignBudgetSchedules do
  use MetaAds.Model

  operation(:create_budget_schedules, "POST", "budget_schedules", nil, [])
  finish()
end
