# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeVideoDataCustomOverlaySpec do
  use MetaAds.Model

  field("background_color", "string", [])

  field("background_opacity", "AdCreativeVideoDataCustomOverlaySpec_background_opacity", [
    "half",
    "solid"
  ])

  field("duration", "int", [])
  field("float_with_margin", "bool", [])
  field("full_width", "bool", [])

  field("option", "AdCreativeVideoDataCustomOverlaySpec_option", [
    "bank_transfer",
    "boleto",
    "cash_on_delivery",
    "discount_with_boleto",
    "fast_delivery",
    "free_shipping",
    "home_delivery",
    "inventory",
    "pay_at_hotel",
    "pay_on_arrival"
  ])

  field("position", "AdCreativeVideoDataCustomOverlaySpec_position", [
    "middle_center",
    "middle_left",
    "middle_right",
    "top_center",
    "top_left",
    "top_right"
  ])

  field("start", "int", [])
  field("template", "AdCreativeVideoDataCustomOverlaySpec_template", ["rectangle_with_text"])
  field("text_color", "string", [])

  finish()
end
