# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignPlacementGet do
  use MetaAds.Model

  field(
    "effective_audience_network_positions",
    "list<AdCampaignPlacementGet_effective_audience_network_positions>",
    []
  )

  field(
    "effective_device_platforms",
    "list<AdCampaignPlacementGet_effective_device_platforms>",
    []
  )

  field(
    "effective_facebook_positions",
    "list<AdCampaignPlacementGet_effective_facebook_positions>",
    []
  )

  field(
    "effective_instagram_positions",
    "list<AdCampaignPlacementGet_effective_instagram_positions>",
    []
  )

  field(
    "effective_messenger_positions",
    "list<AdCampaignPlacementGet_effective_messenger_positions>",
    []
  )

  field(
    "effective_oculus_positions",
    "list<AdCampaignPlacementGet_effective_oculus_positions>",
    []
  )

  field(
    "effective_publisher_platforms",
    "list<AdCampaignPlacementGet_effective_publisher_platforms>",
    []
  )

  field("metadata", "object", [])
  field("recommendations", "list<object>", [])

  finish()
end
