# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativePromotionMetadataSpec do
  use MetaAds.Model

  field("end_date", "int", [])
  field("id", "string", [])
  field("promotion_source", "string", [])
  field("promotion_type", "string", [])
  field("promotion_value", "float", [])
  field("required_code", "string", [])
  field("start_date", "int", [])

  finish()
end
