# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreationPackageConfig do
  use MetaAds.Model

  field("api_version", "string", [])
  field("id", "string", [])
  field("is_eligible_for_default_opt_in", "bool", [])
  field("objective", "string", [])
  field("package_id", "string", [])
  field("status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
