# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeProductData do
  use MetaAds.Model

  field("product_id", "string", [])
  field("product_source", "string", [])

  finish()
end
