# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeWAMOWhatsAppIdentitySpec do
  use MetaAds.Model

  field("wamo_whatsapp_identity_id", "string", [])
  field("whatsapp_phone_number", "string", [])

  finish()
end
