# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignGroupAdvantageState do
  use MetaAds.Model

  field("advantage_audience_state", "string", [])
  field("advantage_budget_state", "string", [])
  field("advantage_placement_state", "string", [])
  field("advantage_state", "string", [])

  finish()
end
