# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeLinkDataCustomOverlaySpec do
  use MetaAds.Model

  field("background_color", "AdCreativeLinkDataCustomOverlaySpec_background_color", [
    "background_000000",
    "background_0090ff",
    "background_00af4c",
    "background_595959",
    "background_755dde",
    "background_e50900",
    "background_f23474",
    "background_f78400",
    "background_ffffff"
  ])

  field("float_with_margin", "bool", [])

  field("font", "AdCreativeLinkDataCustomOverlaySpec_font", [
    "droid_serif_regular",
    "lato_regular",
    "noto_sans_regular",
    "nunito_sans_bold",
    "open_sans_bold",
    "pt_serif_bold",
    "roboto_condensed_regular",
    "roboto_medium"
  ])

  field("option", "AdCreativeLinkDataCustomOverlaySpec_option", [
    "bank_transfer",
    "boleto",
    "cash_on_delivery",
    "discount_with_boleto",
    "fast_delivery",
    "free_shipping",
    "home_delivery",
    "inventory",
    "pay_at_hotel",
    "pay_on_arrival"
  ])

  field("position", "AdCreativeLinkDataCustomOverlaySpec_position", [
    "bottom_left",
    "bottom_right",
    "top_left",
    "top_right"
  ])

  field("render_with_icon", "bool", [])
  field("template", "AdCreativeLinkDataCustomOverlaySpec_template", ["pill_with_text"])

  field("text_color", "AdCreativeLinkDataCustomOverlaySpec_text_color", [
    "text_000000",
    "text_007ad0",
    "text_009c2a",
    "text_646464",
    "text_755dde",
    "text_c91b00",
    "text_f23474",
    "text_f78400",
    "text_ffffff"
  ])

  finish()
end
