# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeGenerativeAssetSpec do
  use MetaAds.Model

  field("transparency_metadata", "Object", [])

  finish()
end
