# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeLinkDataTemplateVideoSpec do
  use MetaAds.Model

  field("categorization_criteria", "string", [])
  field("customization", "list<map<string, string>>", [])
  field("template_id", "string", [])

  finish()
end
