# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdConversions do
  use MetaAds.Model

  field("account_id", "string", [])
  field("adgroup_id", "string", [])
  field("campaign_id", "string", [])
  field("values", "list", [])

  finish()
end
