# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignBidConstraint do
  use MetaAds.Model

  field("roas_average_floor", "int", [])

  finish()
end
