# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeObjectStorySpec do
  use MetaAds.Model

  field("instagram_user_id", "string", [])
  field("link_data", "AdCreativeLinkData", [])
  field("page_id", "string", [])
  field("photo_data", "AdCreativePhotoData", [])
  field("product_data", "list<AdCreativeProductData>", [])
  field("template_data", "AdCreativeLinkData", [])
  field("text_data", "AdCreativeTextData", [])
  field("video_data", "AdCreativeVideoData", [])
  field("whats_app_business_phone_number", "string", [])

  finish()
end
