# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeAssetGroupsSpec do
  use MetaAds.Model

  field("groups", "list<Object>", [])
  field("origin", "string", [])
  field("origins", "list<string>", [])

  finish()
end
