# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignLearningStageInfo do
  use MetaAds.Model

  field("attribution_windows", "list<string>", [])
  field("cas_segment", "string", [])
  field("conversions", "unsigned int", [])
  field("current_budget_prediction", "Object", [])
  field("dynamic_lp_conversions_threshold", "unsigned int", [])
  field("dynamic_lp_days_threshold", "unsigned int", [])
  field("dynamic_lp_status", "string", [])
  field("is_one_to_one_cbo_budget", "bool", [])
  field("last_sig_edit_ts", "int", [])
  field("recommended_budget_prediction", "Object", [])
  field("sigedit_removal", "bool", [])
  field("status", "string", [])

  finish()
end
