# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignGroupStructureTree do
  use MetaAds.Model

  field("children", "list<AdCampaignGroupStructureTree>", [])
  field("id", "string", [])
  field("name", "string", [])
  field("status", "string", [])

  finish()
end
