# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignGroupAgencyFeeConfigForApi do
  use MetaAds.Model

  field("agency_fee_pct", "float", [])
  field("is_agency_fee_disabled", "bool", [])
  field("is_default_agency_fee", "bool", [])

  finish()
end
