# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignDeliveryStatsUnsupportedReasons do
  use MetaAds.Model

  field("reason_data", "list<map<string, string>>", [])
  field("reason_type", "string", [])

  finish()
end
