# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeFeatureCustomizations do
  use MetaAds.Model

  field("aspect_ratio_config", "Object", [])
  field("background_color", "string", [])
  field("catalog_feed_tag_name", "string", [])
  field("fb_feed_tag_name", "string", [])
  field("fb_reels_tag_name", "string", [])
  field("fb_story_tag_name", "string", [])
  field("font_name", "string", [])
  field("ig_feed_tag_name", "string", [])
  field("ig_reels_tag_name", "string", [])
  field("ig_stream_tag_name", "string", [])
  field("image_crop_style", "string", [])
  field("pe_carousel", "Object", [])
  field("recomposition_type", "Object", [])
  field("showcase_card_display", "string", [])
  field("text_extraction", "Object", [])
  field("text_style", "string", [])

  finish()
end
