# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignOptimizationEvent do
  use MetaAds.Model

  field("custom_conversion_id", "string", [])
  field("event_sequence", "unsigned int", [])
  field("event_type", "string", [])

  finish()
end
