# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeSourcingSpec do
  use MetaAds.Model

  field("ad_extensions_relevancy_spec", "Object", [])
  field("associated_product_set_id", "string", [])
  field("brand", "Object", [])
  field("destination_screenshot_spec", "Object", [])
  field("duplication_source", "string", [])
  field("dynamic_site_links_spec", "Object", [])
  field("enable_social_feedback_preservation", "bool", [])
  field("featured_offering_spec", "Object", [])
  field("intent", "Object", [])
  field("ncs_testimonial", "Object", [])
  field("pca_spec", "Object", [])
  field("product_media_metadata_spec", "Object", [])
  field("promotion_metadata_spec", "list<AdCreativePromotionMetadataSpec>", [])
  field("site_links_data_consented", "Object", [])
  field("site_links_spec", "list<AdCreativeSiteLinksSpec>", [])
  field("source_url", "string", [])
  field("website_media_spec", "Object", [])
  field("website_summary_spec", "Object", [])

  finish()
end
