# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignCallingSettings do
  use MetaAds.Model

  field("call_forwarding", "string", [])
  field("call_transcript", "string", [])

  finish()
end
