# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeShopSpec do
  use MetaAds.Model

  field("collection_id", "string", [])
  field("landing_view", "string", [])
  field("shop_id", "string", [])

  finish()
end
