# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeFeatureActionMetadata do
  use MetaAds.Model

  field("type", "string", [])

  finish()
end
