# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeLinkDataImageLayerSpec do
  use MetaAds.Model

  field("blending_mode", "AdCreativeLinkDataImageLayerSpec_blending_mode", [
    "lighten",
    "multiply",
    "normal"
  ])

  field("content", "Object", [])
  field("frame_auto_show_enroll_status", "string", [])
  field("frame_image_hash", "string", [])
  field("frame_source", "AdCreativeLinkDataImageLayerSpec_frame_source", ["custom"])
  field("image_source", "AdCreativeLinkDataImageLayerSpec_image_source", ["catalog"])

  field("layer_type", "AdCreativeLinkDataImageLayerSpec_layer_type", [
    "frame_overlay",
    "image",
    "text_overlay"
  ])

  field("opacity", "int", [])

  field("overlay_position", "AdCreativeLinkDataImageLayerSpec_overlay_position", [
    "bottom",
    "bottom_left",
    "bottom_right",
    "center",
    "left",
    "right",
    "top",
    "top_left",
    "top_right"
  ])

  field("overlay_shape", "AdCreativeLinkDataImageLayerSpec_overlay_shape", [
    "circle",
    "none",
    "pill",
    "rectangle",
    "triangle"
  ])

  field("scale", "int", [])
  field("shape_color", "string", [])
  field("text_color", "string", [])

  field("text_font", "AdCreativeLinkDataImageLayerSpec_text_font", [
    "droid_serif_regular",
    "lato_regular",
    "noto_sans_regular",
    "nunito_sans_bold",
    "open_sans_bold",
    "open_sans_condensed_bold",
    "pt_serif_bold",
    "roboto_condensed_regular",
    "roboto_medium"
  ])

  finish()
end
