# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeDestinationSpec do
  use MetaAds.Model

  field("destination_type", "string", [])
  field("native_commerce_experience", "Object", [])
  field("website", "Object", [])

  finish()
end
