# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignIssuesInfo do
  use MetaAds.Model

  field("error_code", "int", [])
  field("error_message", "string", [])
  field("error_summary", "string", [])
  field("error_type", "string", [])
  field("level", "string", [])
  field("mid", "string", [])

  finish()
end
