# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeRegionalRegulationDisclaimer do
  use MetaAds.Model

  field("australia_finserv", "Object", [])
  field("india_finserv", "Object", [])
  field("singapore_universal", "Object", [])
  field("taiwan_finserv", "Object", [])
  field("taiwan_universal", "Object", [])

  finish()
end
