# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativePostClickConfiguration do
  use MetaAds.Model

  field("post_click_item_description", "string", [])
  field("post_click_item_headline", "string", [])

  finish()
end
