# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignConversionValueExpressionSpec do
  use MetaAds.Model

  field("adjustment_sign", "string", [])
  field("adjustment_weight", "unsigned int", [])
  field("destination_type", "string", [])

  finish()
end
