# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeOmnichannelLinkSpec do
  use MetaAds.Model

  field("app", "Object", [])
  field("web", "Object", [])

  finish()
end
