# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeInsights do
  use MetaAds.Model

  field("aesthetics", "list<map<string, string>>", [])

  finish()
end
