# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeMarketingMessageStructuredSpec do
  use MetaAds.Model

  field("asset_customization", "Object", [])
  field("autoreply", "Object", [])
  field("buttons", "list<Object>", [])
  field("conversation_template_id", "string", [])
  field("footer", "string", [])
  field("greeting", "string", [])
  field("is_optimized_text", "bool", [])
  field("language", "string", [])
  field("offer", "Object", [])
  field("referenced_adgroup_id", "string", [])
  field("whats_app_business_phone_number_id", "string", [])

  finish()
end
