# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeInstagramBrandedContent do
  use MetaAds.Model

  field("sponsor_id", "string", [])

  finish()
end
