# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeFormatTransformationSpec do
  use MetaAds.Model

  field("customizations", "list<Object>", [])
  field("data_source", "list<string>", [])
  field("format", "string", [])

  finish()
end
