# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignMultiAds do
  use MetaAds.Model

  field("enroll_status", "string", [])
  field("source_type", "string", [])

  finish()
end
