# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativePhotoDataMediaElements do
  use MetaAds.Model

  field("element_id", "string", [])
  field("element_type", "string", [])
  field("x", "float", [])
  field("y", "float", [])

  finish()
end
