# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCustomizationRuleSpec do
  use MetaAds.Model

  field("caption", "string", [])
  field("customization_spec", "Object", [])
  field("description", "string", [])
  field("image_hash", "string", [])
  field("link", "string", [])
  field("message", "string", [])
  field("name", "string", [])
  field("priority", "int", [])
  field("template_url_spec", "AdCreativeTemplateURLSpec", [])
  field("video_id", "int", [])

  finish()
end
