# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignGroupStats do
  use MetaAds.Model

  field("actions", "map<string, int>", [])
  field("campaign_group_id", "string", [])
  field("clicks", "unsigned int", [])
  field("end_time", "datetime", [])
  field("impressions", "unsigned int", [])
  field("inline_actions", "map<string, int>", [])
  field("social_clicks", "unsigned int", [])
  field("social_impressions", "unsigned int", [])
  field("social_spent", "unsigned int", [])
  field("social_unique_clicks", "unsigned int", [])
  field("social_unique_impressions", "unsigned int", [])
  field("spent", "unsigned int", [])
  field("start_time", "datetime", [])
  field("unique_clicks", "unsigned int", [])
  field("unique_impressions", "unsigned int", [])

  finish()
end
