# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeLinkDataCallToActionValue do
  use MetaAds.Model

  field("android_url", "string", [])
  field("app_destination", "string", [])
  field("app_link", "string", [])
  field("application", "string", [])
  field("event_id", "string", [])
  field("ios_url", "string", [])
  field("land_on_whatsapp_catalog", "int", [])
  field("land_on_whatsapp_profile", "int", [])
  field("lead_gen_form_id", "string", [])
  field("link", "string", [])
  field("link_caption", "string", [])
  field("link_format", "string", [])
  field("object_store_urls", "list<string>", [])
  field("page", "string", [])
  field("product_link", "string", [])
  field("whatsapp_number", "string", [])

  finish()
end
