# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCampaignGroupMetricsMetadata do
  use MetaAds.Model

  field("budget_optimization", "list<string>", [])
  field("duplication_flow_tips", "list<string>", [])

  finish()
end
