# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdCreativeVideoDataMediaElements do
  use MetaAds.Model

  field("element_id", "string", [])
  field("element_type", "string", [])

  finish()
end
