# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdLabel do
  use MetaAds.Model

  field("account", "AdAccount", [])
  field("created_time", "datetime", [])
  field("id", "string", [])
  field("name", "string", [])
  field("updated_time", "datetime", [])

  operation(:get_adcreatives, "GET", "adcreatives", nil, [])
  operation(:get_ads, "GET", "ads", nil, [])
  operation(:get_adsets, "GET", "adsets", nil, [])
  operation(:get_campaigns, "GET", "campaigns", nil, [])
  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "name", "required" => true, "type" => "string"}
  ])

  finish()
end
