# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdPlacePageSet do
  use MetaAds.Model

  field("account_id", "string", [])
  field("id", "string", [])
  field("location_types", "list<string>", [])
  field("name", "string", [])
  field("pages_count", "int", [])
  field("parent_page", "Page", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
