# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdPreview do
  use MetaAds.Model

  field("body", "string", [])
  field("transformation_spec", "Object", [])

  finish()
end
