# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdRuleTrigger do
  use MetaAds.Model

  field("field", "string", [])

  field("operator", "AdRuleTrigger_operator", [
    "ALL",
    "ANY",
    "CONTAIN",
    "EQUAL",
    "GREATER_THAN",
    "IN",
    "IN_RANGE",
    "LESS_THAN",
    "NONE",
    "NOT_CONTAIN",
    "NOT_EQUAL",
    "NOT_IN",
    "NOT_IN_RANGE"
  ])

  field("type", "AdRuleTrigger_type", [
    "DELIVERY_INSIGHTS_CHANGE",
    "METADATA_CREATION",
    "METADATA_UPDATE",
    "STATS_CHANGE",
    "STATS_MILESTONE"
  ])

  field("value", "Object", [])

  finish()
end
