# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdRuleExecutionSpec do
  use MetaAds.Model

  field("execution_options", "list<AdRuleExecutionOptions>", [])

  field("execution_type", "AdRuleExecutionSpec_execution_type", [
    "ADD_INTEREST_RELAXATION",
    "ADD_QUESTIONNAIRE_INTERESTS",
    "AD_RECOMMENDATION_APPLY",
    "AUDIENCE_CONSOLIDATION",
    "AUDIENCE_CONSOLIDATION_ASK_FIRST",
    "CHANGE_BID",
    "CHANGE_BUDGET",
    "CHANGE_CAMPAIGN_BUDGET",
    "DCO",
    "INCREASE_RADIUS",
    "NOTIFICATION",
    "PAUSE",
    "PING_ENDPOINT",
    "REBALANCE_BUDGET",
    "ROTATE",
    "UNPAUSE",
    "UPDATE_CREATIVE",
    "UPDATE_LAX_BUDGET",
    "UPDATE_LAX_DURATION"
  ])

  field("is_once_off", "bool", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
