# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdRecommendation do
  use MetaAds.Model

  field("blame_field", "string", [])
  field("code", "int", [])
  field("confidence", "AdRecommendation_confidence", ["HIGH", "LOW", "MEDIUM"])
  field("importance", "AdRecommendation_importance", ["HIGH", "LOW", "MEDIUM"])
  field("message", "string", [])
  field("recommendation_data", "AdRecommendationData", [])
  field("title", "string", [])
  field("value", "string", [])

  finish()
end
