# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdRuleFilters do
  use MetaAds.Model

  field("field", "string", [])

  field("operator", "AdRuleFilters_operator", [
    "ALL",
    "ANY",
    "CONTAIN",
    "EQUAL",
    "GREATER_THAN",
    "IN",
    "IN_RANGE",
    "LESS_THAN",
    "NONE",
    "NOT_CONTAIN",
    "NOT_EQUAL",
    "NOT_IN",
    "NOT_IN_RANGE"
  ])

  field("value", "Object", [])

  finish()
end
