# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdRuleSchedule do
  use MetaAds.Model

  field("days", "list<int>", [])
  field("end_minute", "int", [])
  field("start_minute", "int", [])

  finish()
end
