# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdRuleScheduleSpec do
  use MetaAds.Model

  field("schedule", "list<AdRuleSchedule>", [])
  field("schedule_type", "string", [])

  finish()
end
