# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdSet do
  use MetaAds.Model

  field("account_id", "string", [])
  field("ad_set_goal", "AdCampaignGoal", [])
  field("adlabels", "list<AdLabel>", [])
  field("adset_schedule", "list<DayPart>", [])
  field("anchor_event_attribution_window_days", "int", [])
  field("asset_feed_id", "string", [])
  field("attribution_count_type", "string", [])
  field("attribution_spec", "list<AttributionSpec>", [])
  field("automatic_manual_state", "string", [])
  field("bid_adjustments", "AdBidAdjustments", [])
  field("bid_amount", "unsigned int", [])
  field("bid_constraints", "AdCampaignBidConstraint", [])
  field("bid_info", "map<string, unsigned int>", [])

  field("bid_strategy", "AdSet_bid_strategy", [
    "COST_CAP",
    "LOWEST_COST_WITHOUT_CAP",
    "LOWEST_COST_WITH_BID_CAP",
    "LOWEST_COST_WITH_MIN_ROAS"
  ])

  field("billing_event", "AdSet_billing_event", [
    "APP_INSTALLS",
    "CLICKS",
    "IMPRESSIONS",
    "LINK_CLICKS",
    "LISTING_INTERACTION",
    "NONE",
    "OFFER_CLAIMS",
    "PAGE_LIKES",
    "POST_ENGAGEMENT",
    "PURCHASE",
    "THRUPLAY"
  ])

  field("brand_safety_config", "BrandSafetyCampaignConfig", [])
  field("budget_remaining", "string", [])
  field("campaign", "Campaign", [])
  field("campaign_active_time", "string", [])
  field("campaign_attribution", "string", [])
  field("campaign_id", "string", [])

  field("configured_status", "AdSet_configured_status", [
    "ACTIVE",
    "ARCHIVED",
    "DELETED",
    "PAUSED"
  ])

  field("cost_bidding_mode", "string", [])
  field("created_time", "datetime", [])
  field("creative_diversity_label", "list<string>", [])
  field("creative_diversity_score", "list<string>", [])
  field("creative_sequence", "list<string>", [])
  field("creative_sequence_repetition_pattern", "string", [])
  field("daily_budget", "string", [])
  field("daily_min_spend_target", "string", [])
  field("daily_spend_cap", "string", [])
  field("destination_type", "string", [])
  field("dsa_beneficiary", "string", [])
  field("dsa_payor", "string", [])

  field("effective_status", "AdSet_effective_status", [
    "ACTIVE",
    "ARCHIVED",
    "CAMPAIGN_PAUSED",
    "DELETED",
    "IN_PROCESS",
    "PAUSED",
    "WITH_ISSUES"
  ])

  field("end_time", "datetime", [])
  field("existing_customer_budget_percentage", "unsigned int", [])
  field("frequency_control_specs", "list<AdCampaignFrequencyControlSpecs>", [])
  field("full_funnel_exploration_mode", "string", [])
  field("id", "string", [])
  field("instagram_user_id", "string", [])
  field("is_ba_skip_delayed_eligible", "bool", [])
  field("is_budget_schedule_enabled", "bool", [])
  field("is_dc_follow_optimized", "bool", [])
  field("is_dynamic_creative", "bool", [])
  field("is_incremental_attribution_enabled", "bool", [])
  field("is_organic_ad_joint_optimized", "bool", [])
  field("is_sequenced_conversion_creation", "bool", [])
  field("issues_info", "list<AdCampaignIssuesInfo>", [])
  field("learning_stage_info", "AdCampaignLearningStageInfo", [])
  field("lifetime_budget", "string", [])
  field("lifetime_imps", "int", [])
  field("lifetime_min_spend_target", "string", [])
  field("lifetime_spend_cap", "string", [])
  field("live_video_ad_campaign_config", "LiveVideoAdCampaignConfig", [])
  field("low_creative_reach", "list<string>", [])
  field("max_budget_spend_percentage", "string", [])
  field("meta_moment_maker_spec", "MetaMomentMakerConfig", [])
  field("min_budget_spend_percentage", "string", [])
  field("multi_event_conversion_attribution_window_seconds", "int", [])
  field("multi_optimization_goal_weight", "string", [])
  field("name", "string", [])

  field("optimization_goal", "AdSet_optimization_goal", [
    "ADVERTISER_SILOED_VALUE",
    "AD_RECALL_LIFT",
    "APP_INSTALLS",
    "APP_INSTALLS_AND_OFFSITE_CONVERSIONS",
    "AUTOMATIC_OBJECTIVE",
    "CONVERSATIONS",
    "DERIVED_EVENTS",
    "ENGAGED_PAGE_VIEWS",
    "ENGAGED_USERS",
    "EVENT_RESPONSES",
    "IMPRESSIONS",
    "IN_APP_VALUE",
    "LANDING_PAGE_VIEWS",
    "LEAD_GENERATION",
    "LINK_CLICKS",
    "MEANINGFUL_CALL_ATTEMPT",
    "MESSAGING_APPOINTMENT_CONVERSION",
    "MESSAGING_DEEP_CONVERSATION_AND_FOLLOW",
    "MESSAGING_PURCHASE_CONVERSION",
    "NONE",
    "OFFSITE_CONVERSIONS",
    "PAGE_LIKES",
    "POST_ENGAGEMENT",
    "PROFILE_AND_PAGE_ENGAGEMENT",
    "PROFILE_VISIT",
    "QUALITY_CALL",
    "QUALITY_LEAD",
    "REACH",
    "REMINDERS_SET",
    "SUBSCRIBERS",
    "THRUPLAY",
    "VALUE",
    "VISIT_INSTAGRAM_PROFILE"
  ])

  field("optimization_sub_event", "string", [])
  field("pacing_type", "list<string>", [])
  field("placement_soft_opt_out", "PlacementSoftOptOut", [])
  field("promoted_object", "AdPromotedObject", [])
  field("recommendations", "list<AdRecommendation>", [])
  field("recurring_budget_semantics", "bool", [])
  field("regional_regulated_categories", "list<string>", [])
  field("regional_regulation_identities", "RegionalRegulationIdentities", [])
  field("relative_value", "string", [])
  field("review_feedback", "string", [])
  field("rf_prediction_id", "string", [])
  field("source_adset", "AdSet", [])
  field("source_adset_id", "string", [])
  field("special_ad_categories", "list<string>", [])
  field("start_time", "datetime", [])
  field("status", "AdSet_status", ["ACTIVE", "ARCHIVED", "DELETED", "PAUSED"])
  field("targeting", "Targeting", [])
  field("targeting_optimization_types", "list<map<string, int>>", [])
  field("time_based_ad_rotation_id_blocks", "list<list<int>>", [])
  field("time_based_ad_rotation_intervals", "list<unsigned int>", [])
  field("trending_topics_spec", "TrendingTopicsSpec", [])
  field("updated_time", "datetime", [])
  field("use_new_app_click", "bool", [])
  field("value_rule_set_id", "string", [])
  field("value_rules_applied", "bool", [])

  operation(:get_activities, "GET", "activities", nil, [
    %{"name" => "after", "required" => false, "type" => "string"},
    %{"name" => "business_id", "required" => false, "type" => "string"},
    %{
      "name" => "category",
      "required" => false,
      "type" => "adcampaignactivities_category_enum_param",
      "values" => [
        "ACCOUNT",
        "AD",
        "AD_KEYWORDS",
        "AD_SET",
        "AUDIENCE",
        "BID",
        "BUDGET",
        "CAMPAIGN",
        "DATE",
        "STATUS",
        "TARGETING"
      ]
    },
    %{"name" => "limit", "required" => false, "type" => "int"},
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{"name" => "uid", "required" => false, "type" => "int"},
    %{"name" => "until", "required" => false, "type" => "datetime"}
  ])

  operation(:get_ad_studies, "GET", "ad_studies", nil, [])
  operation(:get_adcreatives, "GET", "adcreatives", nil, [])

  operation(:delete_adlabels, "DELETE", "adlabels", nil, [
    %{"name" => "adlabels", "required" => true, "type" => "list<Object>"},
    %{
      "name" => "execution_options",
      "required" => false,
      "type" => "list<adcampaignadlabels_execution_options_enum_param>",
      "values" => ["validate_only"]
    }
  ])

  operation(:create_adlabels, "POST", "adlabels", nil, [
    %{"name" => "adlabels", "required" => true, "type" => "list<Object>"},
    %{
      "name" => "execution_options",
      "required" => false,
      "type" => "list<adcampaignadlabels_execution_options_enum_param>",
      "values" => ["validate_only"]
    }
  ])

  operation(:get_adrules_governed, "GET", "adrules_governed", nil, [
    %{"name" => "pass_evaluation", "required" => false, "type" => "bool"}
  ])

  operation(:get_ads, "GET", "ads", nil, [
    %{
      "name" => "date_preset",
      "required" => false,
      "type" => "adcampaignads_date_preset_enum_param",
      "values" => [
        "data_maximum",
        "last_14d",
        "last_28d",
        "last_30d",
        "last_3d",
        "last_7d",
        "last_90d",
        "last_month",
        "last_quarter",
        "last_week_mon_sun",
        "last_week_sun_sat",
        "last_year",
        "maximum",
        "this_month",
        "this_quarter",
        "this_week_mon_today",
        "this_week_sun_today",
        "this_year",
        "today",
        "yesterday"
      ]
    },
    %{"name" => "effective_status", "required" => false, "type" => "list<string>"},
    %{"name" => "time_range", "required" => false, "type" => "map"},
    %{"name" => "updated_since", "required" => false, "type" => "int"}
  ])

  operation(:get_asyncadrequests, "GET", "asyncadrequests", nil, [
    %{
      "name" => "statuses",
      "required" => false,
      "type" => "list<adcampaignasyncadrequests_statuses_enum_param>",
      "values" => [
        "CANCELED",
        "CANCELED_DEPENDENCY",
        "ERROR",
        "ERROR_CONFLICTS",
        "ERROR_DEPENDENCY",
        "INITIAL",
        "IN_PROGRESS",
        "PENDING_DEPENDENCY",
        "PROCESS_BY_AD_ASYNC_ENGINE",
        "PROCESS_BY_EVENT_PROCESSOR",
        "SUCCESS",
        "USER_CANCELED",
        "USER_CANCELED_DEPENDENCY"
      ]
    }
  ])

  operation(:get_budget_schedules, "GET", "budget_schedules", nil, [
    %{"name" => "time_start", "required" => false, "type" => "datetime"},
    %{"name" => "time_stop", "required" => false, "type" => "datetime"}
  ])

  operation(:create_budget_schedules, "POST", "budget_schedules", nil, [
    %{"name" => "budget_value", "required" => true, "type" => "unsigned int"},
    %{
      "name" => "budget_value_type",
      "required" => true,
      "type" => "adcampaignbudget_schedules_budget_value_type_enum_param",
      "values" => ["ABSOLUTE", "MULTIPLIER"]
    },
    %{"name" => "time_end", "required" => true, "type" => "unsigned int"},
    %{"name" => "time_start", "required" => true, "type" => "unsigned int"}
  ])

  operation(:get_copies, "GET", "copies", nil, [
    %{
      "name" => "date_preset",
      "required" => false,
      "type" => "adcampaigncopies_date_preset_enum_param",
      "values" => [
        "data_maximum",
        "last_14d",
        "last_28d",
        "last_30d",
        "last_3d",
        "last_7d",
        "last_90d",
        "last_month",
        "last_quarter",
        "last_week_mon_sun",
        "last_week_sun_sat",
        "last_year",
        "maximum",
        "this_month",
        "this_quarter",
        "this_week_mon_today",
        "this_week_sun_today",
        "this_year",
        "today",
        "yesterday"
      ]
    },
    %{
      "name" => "effective_status",
      "required" => false,
      "type" => "list<adcampaigncopies_effective_status_enum_param>",
      "values" => [
        "ACTIVE",
        "ADSET_PAUSED",
        "ARCHIVED",
        "CAMPAIGN_PAUSED",
        "DELETED",
        "DISAPPROVED",
        "IN_PROCESS",
        "PAUSED",
        "PENDING_BILLING_INFO",
        "PENDING_REVIEW",
        "PREAPPROVED",
        "WITH_ISSUES"
      ]
    },
    %{"name" => "is_completed", "required" => false, "type" => "bool"},
    %{"name" => "time_range", "required" => false, "type" => "map"}
  ])

  operation(:create_copies, "POST", "copies", nil, [
    %{"name" => "campaign_id", "required" => false, "type" => "string"},
    %{"name" => "create_dco_adset", "required" => false, "type" => "bool"},
    %{"name" => "deep_copy", "required" => false, "type" => "bool"},
    %{"name" => "end_time", "required" => false, "type" => "datetime"},
    %{"name" => "rename_options", "required" => false, "type" => "Object"},
    %{"name" => "start_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "status_option",
      "required" => false,
      "type" => "adcampaigncopies_status_option_enum_param",
      "values" => ["ACTIVE", "INHERITED_FROM_SOURCE", "PAUSED"]
    }
  ])

  operation(:get_delivery_estimate, "GET", "delivery_estimate", nil, [
    %{
      "name" => "optimization_goal",
      "required" => false,
      "type" => "adcampaigndelivery_estimate_optimization_goal_enum_param",
      "values" => [
        "ADVERTISER_SILOED_VALUE",
        "AD_RECALL_LIFT",
        "APP_INSTALLS",
        "APP_INSTALLS_AND_OFFSITE_CONVERSIONS",
        "AUTOMATIC_OBJECTIVE",
        "CONVERSATIONS",
        "DERIVED_EVENTS",
        "ENGAGED_PAGE_VIEWS",
        "ENGAGED_USERS",
        "EVENT_RESPONSES",
        "IMPRESSIONS",
        "IN_APP_VALUE",
        "LANDING_PAGE_VIEWS",
        "LEAD_GENERATION",
        "LINK_CLICKS",
        "MEANINGFUL_CALL_ATTEMPT",
        "MESSAGING_APPOINTMENT_CONVERSION",
        "MESSAGING_DEEP_CONVERSATION_AND_FOLLOW",
        "MESSAGING_PURCHASE_CONVERSION",
        "NONE",
        "OFFSITE_CONVERSIONS",
        "PAGE_LIKES",
        "POST_ENGAGEMENT",
        "PROFILE_AND_PAGE_ENGAGEMENT",
        "PROFILE_VISIT",
        "QUALITY_CALL",
        "QUALITY_LEAD",
        "REACH",
        "REMINDERS_SET",
        "SUBSCRIBERS",
        "THRUPLAY",
        "VALUE",
        "VISIT_INSTAGRAM_PROFILE"
      ]
    },
    %{"name" => "promoted_object", "required" => false, "type" => "Object"},
    %{"name" => "targeting_spec", "required" => false, "type" => "Targeting"}
  ])

  operation(:get_insights, "GET", "insights", nil, [
    %{
      "name" => "action_attribution_windows",
      "required" => false,
      "type" => "list<adcampaigninsights_action_attribution_windows_enum_param>",
      "values" => [
        "1d_click",
        "1d_ev",
        "1d_sequenced",
        "1d_view",
        "28d_click",
        "28d_sequenced",
        "28d_view",
        "28d_view_all_conversions",
        "28d_view_first_conversion",
        "7d_click",
        "7d_sequenced",
        "7d_view",
        "7d_view_all_conversions",
        "7d_view_first_conversion",
        "custom",
        "dda",
        "default",
        "incrementality",
        "incrementality_all_conversions",
        "incrementality_first_conversion",
        "skan_click",
        "skan_click_second_postback",
        "skan_click_third_postback",
        "skan_view",
        "skan_view_second_postback",
        "skan_view_third_postback"
      ]
    },
    %{
      "name" => "action_breakdowns",
      "required" => false,
      "type" => "list<adcampaigninsights_action_breakdowns_enum_param>",
      "values" => [
        "action_canvas_component_name",
        "action_carousel_card_id",
        "action_carousel_card_name",
        "action_destination",
        "action_device",
        "action_reaction",
        "action_target_id",
        "action_type",
        "action_video_sound",
        "action_video_type",
        "conversion_destination",
        "is_business_ai_assisted",
        "matched_persona_id",
        "matched_persona_name",
        "signal_source_bucket",
        "standard_event_content_type"
      ]
    },
    %{
      "name" => "action_report_time",
      "required" => false,
      "type" => "adcampaigninsights_action_report_time_enum_param",
      "values" => ["conversion", "impression", "lifetime", "mixed"]
    },
    %{
      "name" => "breakdowns",
      "required" => false,
      "type" => "list<adcampaigninsights_breakdowns_enum_param>",
      "values" => [
        "ad_extension_domain",
        "ad_extension_url",
        "ad_format_asset",
        "affiliate_click_region",
        "affiliate_link_url",
        "age",
        "app_id",
        "body_asset",
        "breakdown_ad_objective",
        "breakdown_reporting_ad_id",
        "call_to_action_asset",
        "coarse_conversion_value",
        "comscore_market",
        "conversion_destination",
        "country",
        "creative_automation_asset_id",
        "creative_relaxation_asset_type",
        "crm_advertiser_l12_territory_ids",
        "crm_advertiser_subvertical_id",
        "crm_advertiser_vertical_id",
        "crm_ult_advertiser_id",
        "description_asset",
        "device_platform",
        "dma",
        "existing_post_id",
        "fidelity_type",
        "flexible_format_asset_type",
        "frequency_value",
        "gen_ai_asset_type",
        "gender",
        "hourly_stats_aggregated_by_advertiser_time_zone",
        "hourly_stats_aggregated_by_audience_time_zone",
        "hsid",
        "image_asset",
        "impression_device",
        "impression_view_time_advertiser_hour_v2",
        "instagram_ads_follow_type",
        "instagram_ads_instagram_media_product_type",
        "instagram_ads_time_since_creation_bucket",
        "internal_campaign_id",
        "is_auto_advance",
        "is_conversion_id_modeled",
        "is_rendered_as_delayed_skip_ad",
        "landing_destination",
        "link_url_asset",
        "marketing_messages_btn_name",
        "mdsa_landing_destination",
        "media_asset_url",
        "media_creator",
        "media_destination_url",
        "media_format",
        "media_origin_url",
        "media_text_content",
        "media_type",
        "mmm",
        "msa_seller_name",
        "overlap_segment",
        "pa_creator_ig_handle",
        "place_page_id",
        "placement_path",
        "platform_position",
        "postback_sequence_index",
        "product_brand_breakdown",
        "product_category_breakdown",
        "product_custom_label_0_breakdown",
        "product_custom_label_1_breakdown",
        "product_custom_label_2_breakdown",
        "product_custom_label_3_breakdown",
        "product_custom_label_4_breakdown",
        "product_group_content_id_breakdown",
        "product_id",
        "publisher_platform",
        "redownload",
        "reels_trending_topic",
        "region",
        "rta_ugc_topic",
        "rule_set_id",
        "rule_set_name",
        "signal_source_bucket",
        "skan_campaign_id",
        "skan_conversion_id",
        "skan_version",
        "sot_attribution_model_type",
        "sot_attribution_window",
        "sot_channel",
        "sot_event_type",
        "sot_source",
        "standard_event_content_type",
        "title_asset",
        "user_persona_id",
        "user_persona_name",
        "video_asset",
        "zip"
      ]
    },
    %{
      "name" => "date_preset",
      "required" => false,
      "type" => "adcampaigninsights_date_preset_enum_param",
      "values" => [
        "data_maximum",
        "last_14d",
        "last_28d",
        "last_30d",
        "last_3d",
        "last_7d",
        "last_90d",
        "last_month",
        "last_quarter",
        "last_week_mon_sun",
        "last_week_sun_sat",
        "last_year",
        "maximum",
        "this_month",
        "this_quarter",
        "this_week_mon_today",
        "this_week_sun_today",
        "this_year",
        "today",
        "yesterday"
      ]
    },
    %{"name" => "default_summary", "required" => false, "type" => "bool"},
    %{"name" => "export_columns", "required" => false, "type" => "list<string>"},
    %{"name" => "export_format", "required" => false, "type" => "string"},
    %{"name" => "export_name", "required" => false, "type" => "string"},
    %{"name" => "fields", "required" => false, "type" => "list<string>"},
    %{"name" => "filtering", "required" => false, "type" => "list<Object>"},
    %{"name" => "graph_cache", "required" => false, "type" => "bool"},
    %{
      "name" => "level",
      "required" => false,
      "type" => "adcampaigninsights_level_enum_param",
      "values" => ["account", "ad", "adset", "campaign"]
    },
    %{"name" => "limit", "required" => false, "type" => "int"},
    %{"name" => "product_id_limit", "required" => false, "type" => "int"},
    %{"name" => "sort", "required" => false, "type" => "list<string>"},
    %{"name" => "summary", "required" => false, "type" => "list<string>"},
    %{
      "name" => "summary_action_breakdowns",
      "required" => false,
      "type" => "list<adcampaigninsights_summary_action_breakdowns_enum_param>",
      "values" => [
        "action_canvas_component_name",
        "action_carousel_card_id",
        "action_carousel_card_name",
        "action_destination",
        "action_device",
        "action_reaction",
        "action_target_id",
        "action_type",
        "action_video_sound",
        "action_video_type",
        "conversion_destination",
        "is_business_ai_assisted",
        "matched_persona_id",
        "matched_persona_name",
        "signal_source_bucket",
        "standard_event_content_type"
      ]
    },
    %{"name" => "time_increment", "required" => false, "type" => "string"},
    %{"name" => "time_range", "required" => false, "type" => "map"},
    %{"name" => "time_ranges", "required" => false, "type" => "list<map>"},
    %{"name" => "use_account_attribution_setting", "required" => false, "type" => "bool"},
    %{"name" => "use_unified_attribution_setting", "required" => false, "type" => "bool"}
  ])

  operation(:create_insights, "POST", "insights", nil, [
    %{
      "name" => "action_attribution_windows",
      "required" => false,
      "type" => "list<adcampaigninsights_action_attribution_windows_enum_param>",
      "values" => [
        "1d_click",
        "1d_ev",
        "1d_sequenced",
        "1d_view",
        "28d_click",
        "28d_sequenced",
        "28d_view",
        "28d_view_all_conversions",
        "28d_view_first_conversion",
        "7d_click",
        "7d_sequenced",
        "7d_view",
        "7d_view_all_conversions",
        "7d_view_first_conversion",
        "custom",
        "dda",
        "default",
        "incrementality",
        "incrementality_all_conversions",
        "incrementality_first_conversion",
        "skan_click",
        "skan_click_second_postback",
        "skan_click_third_postback",
        "skan_view",
        "skan_view_second_postback",
        "skan_view_third_postback"
      ]
    },
    %{
      "name" => "action_breakdowns",
      "required" => false,
      "type" => "list<adcampaigninsights_action_breakdowns_enum_param>",
      "values" => [
        "action_canvas_component_name",
        "action_carousel_card_id",
        "action_carousel_card_name",
        "action_destination",
        "action_device",
        "action_reaction",
        "action_target_id",
        "action_type",
        "action_video_sound",
        "action_video_type",
        "conversion_destination",
        "is_business_ai_assisted",
        "matched_persona_id",
        "matched_persona_name",
        "signal_source_bucket",
        "standard_event_content_type"
      ]
    },
    %{
      "name" => "action_report_time",
      "required" => false,
      "type" => "adcampaigninsights_action_report_time_enum_param",
      "values" => ["conversion", "impression", "lifetime", "mixed"]
    },
    %{
      "name" => "breakdowns",
      "required" => false,
      "type" => "list<adcampaigninsights_breakdowns_enum_param>",
      "values" => [
        "ad_extension_domain",
        "ad_extension_url",
        "ad_format_asset",
        "affiliate_click_region",
        "affiliate_link_url",
        "age",
        "app_id",
        "body_asset",
        "breakdown_ad_objective",
        "breakdown_reporting_ad_id",
        "call_to_action_asset",
        "coarse_conversion_value",
        "comscore_market",
        "conversion_destination",
        "country",
        "creative_automation_asset_id",
        "creative_relaxation_asset_type",
        "crm_advertiser_l12_territory_ids",
        "crm_advertiser_subvertical_id",
        "crm_advertiser_vertical_id",
        "crm_ult_advertiser_id",
        "description_asset",
        "device_platform",
        "dma",
        "existing_post_id",
        "fidelity_type",
        "flexible_format_asset_type",
        "frequency_value",
        "gen_ai_asset_type",
        "gender",
        "hourly_stats_aggregated_by_advertiser_time_zone",
        "hourly_stats_aggregated_by_audience_time_zone",
        "hsid",
        "image_asset",
        "impression_device",
        "impression_view_time_advertiser_hour_v2",
        "instagram_ads_follow_type",
        "instagram_ads_instagram_media_product_type",
        "instagram_ads_time_since_creation_bucket",
        "internal_campaign_id",
        "is_auto_advance",
        "is_conversion_id_modeled",
        "is_rendered_as_delayed_skip_ad",
        "landing_destination",
        "link_url_asset",
        "marketing_messages_btn_name",
        "mdsa_landing_destination",
        "media_asset_url",
        "media_creator",
        "media_destination_url",
        "media_format",
        "media_origin_url",
        "media_text_content",
        "media_type",
        "mmm",
        "msa_seller_name",
        "overlap_segment",
        "pa_creator_ig_handle",
        "place_page_id",
        "placement_path",
        "platform_position",
        "postback_sequence_index",
        "product_brand_breakdown",
        "product_category_breakdown",
        "product_custom_label_0_breakdown",
        "product_custom_label_1_breakdown",
        "product_custom_label_2_breakdown",
        "product_custom_label_3_breakdown",
        "product_custom_label_4_breakdown",
        "product_group_content_id_breakdown",
        "product_id",
        "publisher_platform",
        "redownload",
        "reels_trending_topic",
        "region",
        "rta_ugc_topic",
        "rule_set_id",
        "rule_set_name",
        "signal_source_bucket",
        "skan_campaign_id",
        "skan_conversion_id",
        "skan_version",
        "sot_attribution_model_type",
        "sot_attribution_window",
        "sot_channel",
        "sot_event_type",
        "sot_source",
        "standard_event_content_type",
        "title_asset",
        "user_persona_id",
        "user_persona_name",
        "video_asset",
        "zip"
      ]
    },
    %{
      "name" => "date_preset",
      "required" => false,
      "type" => "adcampaigninsights_date_preset_enum_param",
      "values" => [
        "data_maximum",
        "last_14d",
        "last_28d",
        "last_30d",
        "last_3d",
        "last_7d",
        "last_90d",
        "last_month",
        "last_quarter",
        "last_week_mon_sun",
        "last_week_sun_sat",
        "last_year",
        "maximum",
        "this_month",
        "this_quarter",
        "this_week_mon_today",
        "this_week_sun_today",
        "this_year",
        "today",
        "yesterday"
      ]
    },
    %{"name" => "default_summary", "required" => false, "type" => "bool"},
    %{"name" => "export_columns", "required" => false, "type" => "list<string>"},
    %{"name" => "export_format", "required" => false, "type" => "string"},
    %{"name" => "export_name", "required" => false, "type" => "string"},
    %{"name" => "fields", "required" => false, "type" => "list<string>"},
    %{"name" => "filtering", "required" => false, "type" => "list<Object>"},
    %{"name" => "graph_cache", "required" => false, "type" => "bool"},
    %{
      "name" => "level",
      "required" => false,
      "type" => "adcampaigninsights_level_enum_param",
      "values" => ["account", "ad", "adset", "campaign"]
    },
    %{"name" => "limit", "required" => false, "type" => "int"},
    %{"name" => "product_id_limit", "required" => false, "type" => "int"},
    %{"name" => "sort", "required" => false, "type" => "list<string>"},
    %{"name" => "summary", "required" => false, "type" => "list<string>"},
    %{
      "name" => "summary_action_breakdowns",
      "required" => false,
      "type" => "list<adcampaigninsights_summary_action_breakdowns_enum_param>",
      "values" => [
        "action_canvas_component_name",
        "action_carousel_card_id",
        "action_carousel_card_name",
        "action_destination",
        "action_device",
        "action_reaction",
        "action_target_id",
        "action_type",
        "action_video_sound",
        "action_video_type",
        "conversion_destination",
        "is_business_ai_assisted",
        "matched_persona_id",
        "matched_persona_name",
        "signal_source_bucket",
        "standard_event_content_type"
      ]
    },
    %{"name" => "time_increment", "required" => false, "type" => "string"},
    %{"name" => "time_range", "required" => false, "type" => "map"},
    %{"name" => "time_ranges", "required" => false, "type" => "list<map>"},
    %{"name" => "use_account_attribution_setting", "required" => false, "type" => "bool"},
    %{"name" => "use_unified_attribution_setting", "required" => false, "type" => "bool"}
  ])

  operation(:get_message_delivery_estimate, "GET", "message_delivery_estimate", nil, [
    %{"name" => "bid_amount", "required" => false, "type" => "unsigned int"},
    %{"name" => "daily_budget", "required" => false, "type" => "unsigned int"},
    %{"name" => "is_direct_send_campaign", "required" => false, "type" => "bool"},
    %{"name" => "lifetime_budget", "required" => false, "type" => "unsigned int"},
    %{"name" => "lifetime_in_days", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "optimization_goal",
      "required" => false,
      "type" => "adcampaignmessage_delivery_estimate_optimization_goal_enum_param",
      "values" => [
        "ADVERTISER_SILOED_VALUE",
        "AD_RECALL_LIFT",
        "APP_INSTALLS",
        "APP_INSTALLS_AND_OFFSITE_CONVERSIONS",
        "AUTOMATIC_OBJECTIVE",
        "CONVERSATIONS",
        "DERIVED_EVENTS",
        "ENGAGED_PAGE_VIEWS",
        "ENGAGED_USERS",
        "EVENT_RESPONSES",
        "IMPRESSIONS",
        "IN_APP_VALUE",
        "LANDING_PAGE_VIEWS",
        "LEAD_GENERATION",
        "LINK_CLICKS",
        "MEANINGFUL_CALL_ATTEMPT",
        "MESSAGING_APPOINTMENT_CONVERSION",
        "MESSAGING_DEEP_CONVERSATION_AND_FOLLOW",
        "MESSAGING_PURCHASE_CONVERSION",
        "NONE",
        "OFFSITE_CONVERSIONS",
        "PAGE_LIKES",
        "POST_ENGAGEMENT",
        "PROFILE_AND_PAGE_ENGAGEMENT",
        "PROFILE_VISIT",
        "QUALITY_CALL",
        "QUALITY_LEAD",
        "REACH",
        "REMINDERS_SET",
        "SUBSCRIBERS",
        "THRUPLAY",
        "VALUE",
        "VISIT_INSTAGRAM_PROFILE"
      ]
    },
    %{
      "name" => "pacing_type",
      "required" => false,
      "type" => "adcampaignmessage_delivery_estimate_pacing_type_enum_param",
      "values" => [
        "DAY_PARTING",
        "DISABLED",
        "NO_PACING",
        "PROBABILISTIC_PACING",
        "PROBABILISTIC_PACING_V2",
        "STANDARD"
      ]
    },
    %{"name" => "promoted_object", "required" => false, "type" => "Object"},
    %{"name" => "targeting_spec", "required" => false, "type" => "Targeting"}
  ])

  operation(:get_targetingsentencelines, "GET", "targetingsentencelines", nil, [])
  operation(:delete, "DELETE", "", nil, [])

  operation(:get, "GET", "", nil, [
    %{"name" => "am_call_tags", "required" => false, "type" => "map"},
    %{
      "name" => "date_preset",
      "required" => false,
      "type" => "adcampaign_date_preset",
      "values" => [
        "data_maximum",
        "last_14d",
        "last_28d",
        "last_30d",
        "last_3d",
        "last_7d",
        "last_90d",
        "last_month",
        "last_quarter",
        "last_week_mon_sun",
        "last_week_sun_sat",
        "last_year",
        "maximum",
        "this_month",
        "this_quarter",
        "this_week_mon_today",
        "this_week_sun_today",
        "this_year",
        "today",
        "yesterday"
      ]
    },
    %{"name" => "from_adtable", "required" => false, "type" => "bool"},
    %{"name" => "time_range", "required" => false, "type" => "map"}
  ])

  operation(:create, "POST", "", nil, [
    %{"name" => "account_id", "required" => false, "type" => "string"},
    %{"name" => "ad_set_goal", "required" => false, "type" => "map"},
    %{"name" => "adlabels", "required" => false, "type" => "list<Object>"},
    %{"name" => "adset_schedule", "required" => false, "type" => "list<Object>"},
    %{"name" => "attribution_spec", "required" => false, "type" => "list<map>"},
    %{
      "name" => "automatic_manual_state",
      "required" => false,
      "type" => "adcampaign_automatic_manual_state",
      "values" => ["AUTOMATIC", "MANUAL", "UNSET"]
    },
    %{"name" => "bid_adjustments", "required" => false, "type" => "Object"},
    %{"name" => "bid_amount", "required" => false, "type" => "int"},
    %{"name" => "bid_constraints", "required" => false, "type" => "map<string, Object>"},
    %{
      "name" => "bid_strategy",
      "required" => false,
      "type" => "adcampaign_bid_strategy",
      "values" => [
        "COST_CAP",
        "LOWEST_COST_WITHOUT_CAP",
        "LOWEST_COST_WITH_BID_CAP",
        "LOWEST_COST_WITH_MIN_ROAS"
      ]
    },
    %{
      "name" => "billing_event",
      "required" => false,
      "type" => "adcampaign_billing_event",
      "values" => [
        "APP_INSTALLS",
        "CLICKS",
        "IMPRESSIONS",
        "LINK_CLICKS",
        "LISTING_INTERACTION",
        "NONE",
        "OFFER_CLAIMS",
        "PAGE_LIKES",
        "POST_ENGAGEMENT",
        "PURCHASE",
        "THRUPLAY"
      ]
    },
    %{"name" => "brand_safety_config", "required" => false, "type" => "map"},
    %{"name" => "budget_schedule_specs", "required" => false, "type" => "list<Object>"},
    %{"name" => "campaign_attribution", "required" => false, "type" => "Object"},
    %{"name" => "campaign_spec", "required" => false, "type" => "Object"},
    %{
      "name" => "cost_bidding_mode",
      "required" => false,
      "type" => "adcampaign_cost_bidding_mode",
      "values" => ["BALANCED", "COST_FOCUSED", "VOLUME_FOCUSED"]
    },
    %{"name" => "creative_sequence", "required" => false, "type" => "list<string>"},
    %{
      "name" => "creative_sequence_repetition_pattern",
      "required" => false,
      "type" => "adcampaign_creative_sequence_repetition_pattern",
      "values" => ["FULL_SEQUENCE", "LAST_AD"]
    },
    %{"name" => "daily_budget", "required" => false, "type" => "unsigned int"},
    %{"name" => "daily_imps", "required" => false, "type" => "unsigned int"},
    %{"name" => "daily_min_spend_target", "required" => false, "type" => "unsigned int"},
    %{"name" => "daily_spend_cap", "required" => false, "type" => "unsigned int"},
    %{"name" => "date_format", "required" => false, "type" => "string"},
    %{
      "name" => "destination_type",
      "required" => false,
      "type" => "adcampaign_destination_type",
      "values" => [
        "APP",
        "APPLINKS_AUTOMATIC",
        "FACEBOOK",
        "FACEBOOK_LIVE",
        "FACEBOOK_PAGE",
        "IMAGINE",
        "INSTAGRAM_DIRECT",
        "INSTAGRAM_LIVE",
        "INSTAGRAM_PROFILE",
        "INSTAGRAM_PROFILE_AND_FACEBOOK_PAGE",
        "MESSAGING_INSTAGRAM_DIRECT_MESSENGER",
        "MESSAGING_INSTAGRAM_DIRECT_MESSENGER_WHATSAPP",
        "MESSAGING_INSTAGRAM_DIRECT_WHATSAPP",
        "MESSAGING_MESSENGER_WHATSAPP",
        "MESSENGER",
        "ON_AD",
        "ON_EVENT",
        "ON_PAGE",
        "ON_POST",
        "ON_VIDEO",
        "SHOP_AUTOMATIC",
        "WEBSITE",
        "WHATSAPP"
      ]
    },
    %{"name" => "dsa_beneficiary", "required" => false, "type" => "string"},
    %{"name" => "dsa_payor", "required" => false, "type" => "string"},
    %{"name" => "end_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "execution_options",
      "required" => false,
      "type" => "list<adcampaign_execution_options>",
      "values" => ["include_recommendations", "validate_only"]
    },
    %{
      "name" => "existing_customer_budget_percentage",
      "required" => false,
      "type" => "unsigned int"
    },
    %{"name" => "frequency_control_specs", "required" => false, "type" => "list<Object>"},
    %{
      "name" => "full_funnel_exploration_mode",
      "required" => false,
      "type" => "adcampaign_full_funnel_exploration_mode",
      "values" => ["EXTENDED_EXPLORATION", "LIMITED_EXPLORATION", "NONE_EXPLORATION"]
    },
    %{"name" => "is_ba_skip_delayed_eligible", "required" => false, "type" => "bool"},
    %{"name" => "is_budget_schedule_enabled", "required" => false, "type" => "bool"},
    %{"name" => "is_dc_follow_optimized", "required" => false, "type" => "bool"},
    %{"name" => "is_incremental_attribution_enabled", "required" => false, "type" => "bool"},
    %{"name" => "is_sac_cfca_terms_certified", "required" => false, "type" => "bool"},
    %{"name" => "is_sequenced_conversion_creation", "required" => false, "type" => "bool"},
    %{"name" => "lifetime_budget", "required" => false, "type" => "unsigned int"},
    %{"name" => "lifetime_imps", "required" => false, "type" => "unsigned int"},
    %{"name" => "lifetime_min_spend_target", "required" => false, "type" => "unsigned int"},
    %{"name" => "lifetime_spend_cap", "required" => false, "type" => "unsigned int"},
    %{"name" => "live_video_ad_campaign_config", "required" => false, "type" => "Object"},
    %{"name" => "max_budget_spend_percentage", "required" => false, "type" => "unsigned int"},
    %{"name" => "meta_moment_maker_spec", "required" => false, "type" => "map"},
    %{"name" => "min_budget_spend_percentage", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "multi_event_conversion_attribution_window_seconds",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "multi_optimization_goal_weight",
      "required" => false,
      "type" => "adcampaign_multi_optimization_goal_weight",
      "values" => ["BALANCED", "PREFER_EVENT", "PREFER_INSTALL", "UNDEFINED"]
    },
    %{"name" => "name", "required" => false, "type" => "string"},
    %{
      "name" => "optimization_goal",
      "required" => false,
      "type" => "adcampaign_optimization_goal",
      "values" => [
        "ADVERTISER_SILOED_VALUE",
        "AD_RECALL_LIFT",
        "APP_INSTALLS",
        "APP_INSTALLS_AND_OFFSITE_CONVERSIONS",
        "AUTOMATIC_OBJECTIVE",
        "CONVERSATIONS",
        "DERIVED_EVENTS",
        "ENGAGED_PAGE_VIEWS",
        "ENGAGED_USERS",
        "EVENT_RESPONSES",
        "IMPRESSIONS",
        "IN_APP_VALUE",
        "LANDING_PAGE_VIEWS",
        "LEAD_GENERATION",
        "LINK_CLICKS",
        "MEANINGFUL_CALL_ATTEMPT",
        "MESSAGING_APPOINTMENT_CONVERSION",
        "MESSAGING_DEEP_CONVERSATION_AND_FOLLOW",
        "MESSAGING_PURCHASE_CONVERSION",
        "NONE",
        "OFFSITE_CONVERSIONS",
        "PAGE_LIKES",
        "POST_ENGAGEMENT",
        "PROFILE_AND_PAGE_ENGAGEMENT",
        "PROFILE_VISIT",
        "QUALITY_CALL",
        "QUALITY_LEAD",
        "REACH",
        "REMINDERS_SET",
        "SUBSCRIBERS",
        "THRUPLAY",
        "VALUE",
        "VISIT_INSTAGRAM_PROFILE"
      ]
    },
    %{
      "name" => "optimization_sub_event",
      "required" => false,
      "type" => "adcampaign_optimization_sub_event",
      "values" => [
        "NONE",
        "POST_INTERACTION",
        "TRAVEL_INTENT",
        "TRAVEL_INTENT_BUCKET_01",
        "TRAVEL_INTENT_BUCKET_02",
        "TRAVEL_INTENT_BUCKET_03",
        "TRAVEL_INTENT_BUCKET_04",
        "TRAVEL_INTENT_BUCKET_05",
        "TRAVEL_INTENT_NO_DESTINATION_INTENT",
        "TRIP_CONSIDERATION",
        "VIDEO_SOUND_ON"
      ]
    },
    %{"name" => "pacing_type", "required" => false, "type" => "list<string>"},
    %{"name" => "placement_soft_opt_out", "required" => false, "type" => "Object"},
    %{"name" => "promoted_object", "required" => false, "type" => "Object"},
    %{"name" => "rb_prediction_id", "required" => false, "type" => "string"},
    %{
      "name" => "regional_regulated_categories",
      "required" => false,
      "type" => "list<adcampaign_regional_regulated_categories>",
      "values" => [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "24"
      ]
    },
    %{"name" => "regional_regulation_identities", "required" => false, "type" => "map"},
    %{"name" => "relative_value", "required" => false, "type" => "float"},
    %{"name" => "rf_prediction_id", "required" => false, "type" => "string"},
    %{"name" => "start_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "status",
      "required" => false,
      "type" => "adcampaign_status",
      "values" => ["ACTIVE", "ARCHIVED", "DELETED", "PAUSED"]
    },
    %{"name" => "targeting", "required" => false, "type" => "Targeting"},
    %{
      "name" => "time_based_ad_rotation_id_blocks",
      "required" => false,
      "type" => "list<list<unsigned int>>"
    },
    %{
      "name" => "time_based_ad_rotation_intervals",
      "required" => false,
      "type" => "list<unsigned int>"
    },
    %{"name" => "time_start", "required" => false, "type" => "datetime"},
    %{"name" => "time_stop", "required" => false, "type" => "datetime"},
    %{"name" => "trending_topics_spec", "required" => false, "type" => "map"},
    %{
      "name" => "tune_for_category",
      "required" => false,
      "type" => "adcampaign_tune_for_category",
      "values" => [
        "CREDIT",
        "EMPLOYMENT",
        "FINANCIAL_PRODUCTS_SERVICES",
        "HOUSING",
        "ISSUES_ELECTIONS_POLITICS",
        "NONE",
        "ONLINE_GAMBLING_AND_GAMING"
      ]
    },
    %{"name" => "value_rule_set_id", "required" => false, "type" => "string"},
    %{"name" => "value_rules_applied", "required" => false, "type" => "bool"}
  ])

  finish()
end
