# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdgroupMetadata do
  use MetaAds.Model

  field("ad_standard_enhancements_edit_source", "int", [])
  field("adgroup_creation_source", "string", [])
  field("adgroup_edit_source", "string", [])
  field("adgroup_media_source", "string", [])
  field("carousel_style", "string", [])
  field("carousel_with_static_card_style", "string", [])
  field("is_pca_unified_format_ad", "bool", [])

  finish()
end
