# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsReportBuilderMMMReport do
  use MetaAds.Model

  field("async_status", "string", [])
  field("export_format", "string", [])
  field("export_name", "string", [])
  field("export_type", "string", [])
  field("has_seen", "bool", [])
  field("id", "string", [])
  field("mmm_status", "string", [])
  field("time_start", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
