# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsImageCrops do
  use MetaAds.Model

  field("100x100", "list<list>", [])
  field("100x72", "list<list>", [])
  field("191x100", "list<list>", [])
  field("300x400", "list<list>", [])
  field("400x150", "list<list>", [])
  field("400x500", "list<list>", [])
  field("600x360", "list<list>", [])
  field("90x160", "list<list>", [])

  finish()
end
