# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsPaymentCycle do
  use MetaAds.Model

  field("account_id", "string", [])
  field("created_time", "datetime", [])
  field("multiplier", "unsigned int", [])
  field("requested_threshold_amount", "unsigned int", [])
  field("threshold_amount", "unsigned int", [])
  field("updated_time", "datetime", [])

  finish()
end
