# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsReportBuilder do
  use MetaAds.Model

  field("headers", "Object", [])
  field("rows", "list<Object>", [])
  field("skan_readiness_status", "list<map<string, string>>", [])

  finish()
end
