# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsConversionGoal do
  use MetaAds.Model

  field("ad_account_id", "string", [])
  field("conversion_event_value_source", "string", [])
  field("description", "string", [])
  field("goal_creation_method", "string", [])
  field("id", "string", [])
  field("name", "string", [])
  field("performance_goal", "string", [])
  field("update_status", "string", [])

  operation(:get_conversion_events, "GET", "conversion_events", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
