# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsSignalDiagnosticIssue do
  use MetaAds.Model

  field("data_source_id", "AdsPixel", [])
  field("data_source_type", "string", [])
  field("diagnostic_type", "string", [])
  field("event_name", "string", [])
  field("traffic_anomaly_drop_percentage", "float", [])
  field("traffic_anomaly_drop_timestamp", "datetime", [])

  finish()
end
