# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsNamingTemplate do
  use MetaAds.Model

  field("api_fields", "list<list<map<string, list<map<string, string>>>>>", [])
  field("api_version", "string", [])
  field("field_order", "list<string>", [])
  field("id", "string", [])

  field("level", "AdsNamingTemplate_level", [
    "ADGROUP",
    "AD_ACCOUNT",
    "CAMPAIGN",
    "CAMPAIGN_GROUP",
    "OPPORTUNITIES",
    "PRIVACY_INFO_CENTER",
    "PRODUCT",
    "TOPLINE",
    "UNIQUE_ADCREATIVE"
  ])

  field("separator", "string", [])
  field("template_version", "string", [])
  field("user_defined_fields", "list<list<map<string, list<string>>>>", [])
  field("value_separator", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
