# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsPixelEventSuggestionRule do
  use MetaAds.Model

  field("7d_volume", "int", [])
  field("dismissed", "bool", [])
  field("end_time", "datetime", [])
  field("event_type", "string", [])
  field("rank", "int", [])
  field("rule", "string", [])
  field("sample_urls", "list<string>", [])
  field("start_time", "datetime", [])

  finish()
end
