# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsReportBuilderExportCore do
  use MetaAds.Model

  field("async_percent_completion", "int", [])
  field("async_report_url", "string", [])
  field("async_status", "string", [])
  field("client_creation_value", "string", [])
  field("expiry_time", "datetime", [])
  field("export_download_time", "datetime", [])
  field("export_format", "string", [])
  field("export_name", "string", [])
  field("export_type", "string", [])
  field("has_seen", "bool", [])
  field("id", "string", [])
  field("is_sharing", "bool", [])
  field("link_sharing_expiration_time", "datetime", [])
  field("link_sharing_uri", "string", [])
  field("time_completed", "datetime", [])
  field("time_start", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
