# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsPixelEventLastFiredTime do
  use MetaAds.Model

  field("event", "string", [])
  field("last_fired_time", "int", [])

  finish()
end
