# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsValueAdjustmentRuleCollection do
  use MetaAds.Model

  field("id", "string", [])
  field("is_default_setting", "bool", [])
  field("last_attach_time", "datetime", [])
  field("name", "string", [])
  field("product_type", "string", [])
  field("status", "string", [])

  operation(:create_delete_rule_set, "POST", "delete_rule_set", nil, [
    %{
      "name" => "status",
      "required" => false,
      "type" => "adsvalueadjustmentrulecollectiondelete_rule_set_status_enum_param",
      "values" => ["ACTIVE", "DELETED", "DRAFT"]
    }
  ])

  operation(:get_rules, "GET", "rules", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{
      "name" => "entry_point",
      "required" => false,
      "type" => "adsvalueadjustmentrulecollection_entry_point",
      "values" => [
        "ADVERTISING_SETTINGS",
        "L2_AUDIENCE",
        "L2_CONVERSION_LOCATION",
        "L2_GLOBAL",
        "L2_NCA_GOAL",
        "L2_PLACEMENT"
      ]
    },
    %{"name" => "is_default_setting", "required" => false, "type" => "bool"},
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "rules", "required" => true, "type" => "list<map>"}
  ])

  finish()
end
