# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsPixelCAPIIntegrationQuality do
  use MetaAds.Model

  field("acr", "Object", [])
  field("data_freshness", "Object", [])
  field("dedupe_key_feedback", "list<Object>", [])
  field("event_ad_sets", "list<Object>", [])
  field("event_coverage", "Object", [])
  field("event_match_quality", "Object", [])
  field("event_name", "string", [])
  field("event_potential_aly_acr_increase", "Object", [])
  field("event_spend", "Object", [])

  finish()
end
