# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsGuidanceQEExposure do
  use MetaAds.Model

  field("account_exposed", "bool", [])

  finish()
end
