# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsTextSuggestions do
  use MetaAds.Model

  field("ad_account_id", "string", [])
  field("bodies", "list<Object>", [])
  field("descriptions", "list<Object>", [])
  field("inactive_session_tally", "int", [])
  field("long", "list<Object>", [])
  field("short", "list<Object>", [])
  field("titles", "list<Object>", [])

  finish()
end
