# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AdsPixelMicrodataStats do
  use MetaAds.Model

  field("allowed_domains", "list<string>", [])
  field("errors_stats_for_time_ranges", "list<Object>", [])
  field("has_valid_events", "bool", [])
  field("suggested_allowed_domains_count_max", "int", [])
  field("suggested_trusted_domains", "list<string>", [])

  finish()
end
