# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AgeRange do
  use MetaAds.Model

  field("max", "unsigned int", [])
  field("min", "unsigned int", [])

  finish()
end
