# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AgencyClientDeclaration do
  use MetaAds.Model

  field("agency_representing_client", "unsigned int", [])
  field("client_based_in_france", "unsigned int", [])
  field("client_city", "string", [])
  field("client_country_code", "string", [])
  field("client_email_address", "string", [])
  field("client_name", "string", [])
  field("client_postal_code", "string", [])
  field("client_province", "string", [])
  field("client_street", "string", [])
  field("client_street2", "string", [])
  field("has_written_mandate_from_advertiser", "unsigned int", [])
  field("is_client_paying_invoices", "unsigned int", [])

  finish()
end
