# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AIGeneratedProductImage do
  use MetaAds.Model

  field("flagged_for_manual_review", "bool", [])
  field("transformed_image_url", "string", [])

  finish()
end
