# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Album do
  use MetaAds.Model

  field("backdated_time", "datetime", [])
  field("backdated_time_granularity", "string", [])
  field("can_backdate", "bool", [])
  field("can_upload", "bool", [])
  field("count", "unsigned int", [])
  field("cover_photo", "Photo", [])
  field("created_time", "datetime", [])
  field("description", "string", [])
  field("edit_link", "string", [])
  field("event", "Event", [])
  field("from", "Object", [])
  field("id", "string", [])
  field("is_user_facing", "bool", [])
  field("link", "string", [])
  field("location", "string", [])
  field("modified_major", "datetime", [])
  field("name", "string", [])
  field("photo_count", "unsigned int", [])
  field("place", "Place", [])
  field("privacy", "string", [])
  field("type", "string", [])
  field("updated_time", "datetime", [])
  field("video_count", "unsigned int", [])

  operation(:get_comments, "GET", "comments", nil, [
    %{
      "name" => "filter",
      "required" => false,
      "type" => "albumcomments_filter_enum_param",
      "values" => ["stream", "toplevel"]
    },
    %{
      "name" => "live_filter",
      "required" => false,
      "type" => "albumcomments_live_filter_enum_param",
      "values" => ["filter_low_quality", "no_filter"]
    },
    %{
      "name" => "order",
      "required" => false,
      "type" => "albumcomments_order_enum_param",
      "values" => ["chronological", "reverse_chronological"]
    },
    %{"name" => "since", "required" => false, "type" => "datetime"}
  ])

  operation(:create_comments, "POST", "comments", nil, [
    %{"name" => "attachment_id", "required" => false, "type" => "string"},
    %{"name" => "attachment_share_url", "required" => false, "type" => "string"},
    %{"name" => "attachment_url", "required" => false, "type" => "string"},
    %{
      "name" => "comment_privacy_value",
      "required" => false,
      "type" => "albumcomments_comment_privacy_value_enum_param",
      "values" => [
        "DECLINED_BY_ADMIN_ASSISTANT",
        "DEFAULT_PRIVACY",
        "FRIENDS_AND_POST_OWNER",
        "FRIENDS_ONLY",
        "GRAPHQL_MULTIPLE_VALUE_HACK_DO_NOT_USE",
        "OWNER_OR_COMMENTER",
        "PENDING_APPROVAL",
        "PRIVATE_CONVERSATION_PARTICIPANTS_ONLY",
        "REMOVED_BY_ADMIN_ASSISTANT",
        "SIDE_CONVERSATION",
        "SIDE_CONVERSATION_AND_POST_OWNER",
        "SPOTLIGHT_TAB"
      ]
    },
    %{"name" => "facepile_mentioned_ids", "required" => false, "type" => "list<string>"},
    %{"name" => "feedback_source", "required" => false, "type" => "string"},
    %{"name" => "is_offline", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "object_id", "required" => false, "type" => "string"},
    %{"name" => "parent_comment_id", "required" => false, "type" => "Object"},
    %{"name" => "text", "required" => false, "type" => "string"},
    %{"name" => "tracking", "required" => false, "type" => "string"}
  ])

  operation(:get_likes, "GET", "likes", nil, [])

  operation(:create_likes, "POST", "likes", nil, [
    %{"name" => "attribution_id_v2", "required" => false, "type" => "string"},
    %{"name" => "feedback_source", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "notify", "required" => false, "type" => "bool"},
    %{"name" => "tracking", "required" => false, "type" => "string"}
  ])

  operation(:get_photos, "GET", "photos", nil, [])

  operation(:create_photos, "POST", "photos", nil, [
    %{"name" => "aid", "required" => false, "type" => "string"},
    %{"name" => "allow_spherical_photo", "required" => false, "type" => "bool"},
    %{"name" => "alt_text_custom", "required" => false, "type" => "string"},
    %{"name" => "android_key_hash", "required" => false, "type" => "string"},
    %{"name" => "application_id", "required" => false, "type" => "string"},
    %{"name" => "attempt", "required" => false, "type" => "unsigned int"},
    %{"name" => "audience_exp", "required" => false, "type" => "bool"},
    %{"name" => "backdated_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "backdated_time_granularity",
      "required" => false,
      "type" => "albumphotos_backdated_time_granularity_enum_param",
      "values" => ["day", "hour", "min", "month", "none", "year"]
    },
    %{"name" => "caption", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_point", "required" => false, "type" => "string"},
    %{"name" => "composer_session_id", "required" => false, "type" => "string"},
    %{"name" => "direct_share_status", "required" => false, "type" => "unsigned int"},
    %{"name" => "feed_targeting", "required" => false, "type" => "Object"},
    %{"name" => "filter_type", "required" => false, "type" => "unsigned int"},
    %{"name" => "full_res_is_coming_later", "required" => false, "type" => "bool"},
    %{
      "name" => "initial_view_heading_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "initial_view_pitch_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "initial_view_vertical_fov_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{"name" => "ios_bundle_id", "required" => false, "type" => "string"},
    %{"name" => "is_explicit_location", "required" => false, "type" => "bool"},
    %{"name" => "is_explicit_place", "required" => false, "type" => "bool"},
    %{"name" => "manual_privacy", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "no_story", "required" => false, "type" => "bool"},
    %{"name" => "offline_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "og_action_type_id", "required" => false, "type" => "string"},
    %{"name" => "og_icon_id", "required" => false, "type" => "string"},
    %{"name" => "og_object_id", "required" => false, "type" => "string"},
    %{"name" => "og_phrase", "required" => false, "type" => "string"},
    %{"name" => "og_set_profile_badge", "required" => false, "type" => "bool"},
    %{"name" => "og_suggestion_mechanism", "required" => false, "type" => "string"},
    %{"name" => "place", "required" => false, "type" => "Object"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{"name" => "profile_id", "required" => false, "type" => "int"},
    %{"name" => "provenance_info", "required" => false, "type" => "map"},
    %{"name" => "provenance_metadata", "required" => false, "type" => "map"},
    %{"name" => "proxied_app_id", "required" => false, "type" => "string"},
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "qn", "required" => false, "type" => "string"},
    %{"name" => "spherical_metadata", "required" => false, "type" => "map"},
    %{"name" => "sponsor_id", "required" => false, "type" => "string"},
    %{"name" => "sponsor_relationship", "required" => false, "type" => "unsigned int"},
    %{"name" => "tags", "required" => false, "type" => "list<Object>"},
    %{"name" => "target_id", "required" => false, "type" => "int"},
    %{"name" => "targeting", "required" => false, "type" => "Object"},
    %{"name" => "time_since_original_post", "required" => false, "type" => "unsigned int"},
    %{"name" => "uid", "required" => false, "type" => "int"},
    %{
      "name" => "unpublished_content_type",
      "required" => false,
      "type" => "albumphotos_unpublished_content_type_enum_param",
      "values" => [
        "ADS_POST",
        "DRAFT",
        "INLINE_CREATED",
        "PUBLISHED",
        "PUBLISH_PENDING",
        "REVIEWABLE_BRANDED_CONTENT",
        "SCHEDULED",
        "SCHEDULED_RECURRING"
      ]
    },
    %{"name" => "url", "required" => false, "type" => "string"},
    %{"name" => "user_selected_tags", "required" => false, "type" => "bool"},
    %{"name" => "vault_image_id", "required" => false, "type" => "string"}
  ])

  operation(:get_picture, "GET", "picture", nil, [
    %{"name" => "redirect", "required" => false, "type" => "bool"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "albumpicture_type_enum_param",
      "values" => ["album", "small", "thumbnail"]
    }
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
