# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ALMGuidance do
  use MetaAds.Model

  field("ad_account_id", "string", [])
  field("guidances", "list<Object>", [])
  field("opportunity_score", "float", [])
  field("parent_advertiser_id", "string", [])
  field("parent_advertiser_name", "string", [])

  finish()
end
