# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ALMAdAccountInfo do
  use MetaAds.Model

  field("ad_account_id", "string", [])
  field("id", "string", [])
  field("managed_by", "string", [])
  field("owned_by", "string", [])
  field("parent_advertiser_id", "string", [])
  field("sub_vertical", "string", [])
  field("tag", "list<string>", [])
  field("user_ids", "list<string>", [])
  field("vertical", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
