# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ALMEvent do
  use MetaAds.Model

  field("ad_account_ids", "list<string>", [])
  field("campaign_ids", "list<string>", [])
  field("channel", "string", [])
  field("event", "string", [])
  field("event_time", "datetime", [])
  field("guidance", "string", [])
  field("guidance_detail", "string", [])
  field("guidance_type", "string", [])
  field("id", "string", [])
  field("parent_advertiser_ids", "list<string>", [])
  field("reseller_business_id", "string", [])
  field("solution_id", "string", [])
  field("sub_channel", "string", [])
  field("user_id", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
