# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ALMGuidanceMetrics do
  use MetaAds.Model

  field("ad_account_id", "string", [])
  field("adopted_objects", "list<Object>", [])
  field("guidance_name", "string", [])
  field("guidance_type", "string", [])
  field("l28_adoption", "int", [])
  field("l28_available", "int", [])
  field("l28_click", "int", [])
  field("l28_conversion", "int", [])
  field("l28_has_click", "bool", [])
  field("l28_has_impression", "bool", [])
  field("l28_impression", "int", [])
  field("l28_is_actioned", "bool", [])
  field("l28_is_adopted", "bool", [])
  field("l28_is_available", "bool", [])
  field("l28_is_pitched", "bool", [])
  field("l28_pitch", "int", [])
  field("l28d_adopted_revenue", "float", [])
  field("last_actioned_ds", "string", [])
  field("last_adopted_ds", "string", [])
  field("last_pitch_ds", "string", [])
  field("parent_advertiser_id", "string", [])
  field("report_ds", "string", [])

  finish()
end
