# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AnalyticsEntityUserConfig do
  use MetaAds.Model

  field("dismissed_notices", "list<string>", [])

  finish()
end
