# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AnalyticsSegment do
  use MetaAds.Model

  field("custom_audience_ineligiblity_reasons", "list<string>", [])
  field("description", "string", [])
  field("estimated_custom_audience_size", "unsigned int", [])
  field("event_info_rules", "list<Object>", [])
  field("event_rules", "list<Object>", [])
  field("filter_set", "string", [])
  field("has_demographic_rules", "bool", [])
  field("id", "string", [])
  field("is_all_user", "bool", [])
  field("is_eligible_for_push_campaign", "bool", [])
  field("is_internal", "bool", [])
  field("name", "string", [])
  field("percentile_rules", "list<Object>", [])
  field("time_last_seen", "unsigned int", [])
  field("time_last_updated", "unsigned int", [])
  field("user_property_rules", "list<Object>", [])
  field("web_param_rules", "list<Object>", [])

  operation(:get, "GET", "", nil, [
    %{"name" => "async_task_id", "required" => false, "type" => "string"},
    %{"name" => "end_date", "required" => false, "type" => "int"},
    %{"name" => "start_date", "required" => false, "type" => "int"}
  ])

  finish()
end
