# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AnalyticsUserConfig do
  use MetaAds.Model

  field("demo_app_nux_config", "Object", [])
  field("flags", "list<map<string, string>>", [])
  field("id", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
