# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AnalyticsConfig do
  use MetaAds.Model

  field("analytics_access_for_authorized_ad_account", "bool", [])
  field("breakdowns_config", "list<Object>", [])
  field("builtin_fields_config", "list<Object>", [])
  field("deprecated_events_config", "list<Object>", [])
  field("events_config", "list<Object>", [])
  field("ios_purchase_validation_secret", "string", [])
  field("is_any_role_able_to_see_restricted_insights", "bool", [])
  field("is_implicit_purchase_logging_on_android_supported", "bool", [])
  field("is_implicit_purchase_logging_on_ios_supported", "bool", [])
  field("is_track_ios_app_uninstall_supported", "bool", [])
  field("journey_backfill_status", "string", [])
  field("journey_conversion_events", "list<string>", [])
  field("journey_enabled", "bool", [])
  field("journey_impacting_change_time", "datetime", [])
  field("journey_timeout", "string", [])
  field("latest_sdk_versions", "map<string, string>", [])
  field("log_android_implicit_purchase_events", "bool", [])
  field("log_automatic_analytics_events", "bool", [])
  field("log_implicit_purchase_events", "bool", [])
  field("prev_journey_conversion_events", "list<string>", [])
  field("query_approximation_accuracy_level", "string", [])
  field("query_currency", "string", [])
  field("query_timezone", "string", [])
  field("recent_events_update_time", "datetime", [])
  field("session_timeout_interval", "unsigned int", [])
  field("track_ios_app_uninstall", "bool", [])

  finish()
end
