# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AppRequestFormerRecipient do
  use MetaAds.Model

  field("id", "string", [])
  field("recipient_id", "string", [])

  finish()
end
