# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AppRequest do
  use MetaAds.Model

  field("action_type", "string", [])
  field("application", "Application", [])
  field("created_time", "datetime", [])
  field("data", "string", [])
  field("from", "Object", [])
  field("id", "string", [])
  field("message", "string", [])
  field("object", "Object", [])
  field("to", "Object", [])

  operation(:delete, "DELETE", "", nil, [
    %{"name" => "ids", "required" => true, "type" => "list<string>"}
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
