# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AREffect do
  use MetaAds.Model

  field("creation_time", "datetime", [])
  field("id", "string", [])
  field("last_modified_time", "datetime", [])
  field("name", "string", [])
  field("status", "string", [])
  field("surfaces", "list<string>", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
