# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ArticlesAndPublicationsItemDelete do
  use MetaAds.Model

  field("success", "bool", [])

  finish()
end
