# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AsyncRequest do
  use MetaAds.Model

  field("id", "int", [])
  field("result", "string", [])
  field("status", "int", [])
  field("type", "int", [])

  finish()
end
