# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AudioIsrc do
  use MetaAds.Model

  field("all_kg_featured_artists", "string", [])
  field("all_kg_main_artists", "string", [])
  field("artist_profile_picture_url", "string", [])
  field("canonical_audio_asset", "AudioAsset", [])
  field("id", "string", [])
  field("isrc", "string", [])
  field("publishing_rights_data", "Object", [])
  field("top_searchable_artist_id", "string", [])
  field("top_searchable_artist_name", "string", [])
  field("top_searchable_artist_profile_pic_url", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
