# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AudiencePermissionForActions do
  use MetaAds.Model

  field("can_edit", "bool", [])
  field("can_see_insight", "bool", [])
  field("can_share", "bool", [])
  field("subtype_supports_lookalike", "bool", [])
  field("supports_recipient_lookalike", "bool", [])

  finish()
end
