# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AudienceOverlap do
  use MetaAds.Model

  field("estimated_reach", "int", [])
  field("id", "string", [])
  field("name", "string", [])
  field("overlap", "int", [])

  finish()
end
