# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AudienceFunnel do
  use MetaAds.Model

  field("audience_type_param_name", "string", [])
  field("audience_type_param_tags", "list<map<string, string>>", [])
  field("custom_audience_groups_info", "list<map<string, list<string>>>", [])

  finish()
end
