# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.AudioCopyright do
  use MetaAds.Model

  field("audio_asset", "AudioAsset", [])
  field("creation_time", "datetime", [])
  field("displayed_matches_count", "int", [])
  field("id", "string", [])
  field("in_conflict", "bool", [])
  field("isrc", "string", [])
  field("match_rule", "VideoCopyrightRule", [])
  field("ownership_countries", "list<string>", [])
  field("ownership_details", "list<map<string, Object>>", [])
  field("reference_file_status", "string", [])
  field("ridge_monitoring_status", "string", [])
  field("tags", "list<string>", [])
  field("update_time", "datetime", [])
  field("whitelisted_fb_users", "list<Object>", [])
  field("whitelisted_ig_users", "list<string>", [])

  operation(:get_update_records, "GET", "update_records", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
