# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BCPCampaign do
  use MetaAds.Model

  field("ads_permission_required", "bool", [])
  field("application_deadline", "string", [])
  field("campaign_goal", "string", [])
  field("campaign_goal_other", "string", [])
  field("content_delivery_deadline", "string", [])
  field("content_delivery_start_date", "string", [])
  field("content_requirements", "list<map<string, unsigned int>>", [])
  field("content_requirements_description", "string", [])
  field("currency", "string", [])
  field("deal_negotiation_type", "string", [])
  field("description", "string", [])
  field("has_free_product", "bool", [])
  field("id", "string", [])
  field("name", "string", [])
  field("payment_amount_for_ads", "unsigned int", [])
  field("payment_amount_for_content", "unsigned int", [])
  field("payment_description", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
