# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BidSchedule do
  use MetaAds.Model

  field("ad_object_id", "string", [])
  field("bid_recurrence_type", "string", [])
  field("bid_timezone", "string", [])
  field("bid_value", "int", [])
  field("id", "string", [])
  field("status", "string", [])
  field("time_end", "datetime", [])
  field("time_start", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
