# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BlindPig do
  use MetaAds.Model

  field("id", "string", [])
  field("name", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
