# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BlockedUserInfo do
  use MetaAds.Model

  field("block_time", "datetime", [])
  field("block_type", "string", [])
  field("fbid", "string", [])
  field("name", "string", [])
  field("username", "string", [])

  finish()
end
