# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BrandSafetyCampaignConfig do
  use MetaAds.Model

  field("comment_moderation_filter", "string", [])
  field("fb_comment_moderation_filter", "string", [])
  field("ig_comment_moderation_filter", "string", [])
  field("threads_comment_moderation_filter", "string", [])

  finish()
end
