# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BrandSafetyBlockListUsage do
  use MetaAds.Model

  field("current_usage", "int", [])
  field("new_usage", "int", [])
  field("platform", "string", [])
  field("position", "string", [])
  field("threshold", "int", [])

  finish()
end
