# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BrandedContentShadowIGMediaID do
  use MetaAds.Model

  field("eligibility_errors", "list<string>", [])
  field("has_permission_for_partnership_ad", "bool", [])
  field("id", "string", [])
  field("is_creator_allowlisted", "bool", [])
  field("linked_products", "list<ProductItem>", [])
  field("owner_id", "string", [])
  field("permalink", "string", [])
  field("product_suggestions", "list<ProductItem>", [])
  field("recommended_campaign_objectives", "list<string>", [])

  finish()
end
