# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BrandedContentFBPromodeUser do
  use MetaAds.Model

  field("delegate_page_for_ads_only_id", "string", [])
  field("is_iabp", "bool", [])
  field("is_managed", "bool", [])
  field("name", "string", [])
  field("profile_picture_url", "string", [])

  finish()
end
