# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessRoleRequest do
  use MetaAds.Model

  field("created_by", "Object", [])
  field("created_time", "datetime", [])
  field("email", "string", [])
  field("expiration_time", "datetime", [])
  field("expiry_time", "datetime", [])
  field("finance_role", "string", [])
  field("id", "string", [])
  field("invite_link", "string", [])
  field("invited_user_type", "list<string>", [])
  field("ip_role", "string", [])
  field("owner", "Business", [])
  field("role", "string", [])
  field("status", "string", [])
  field("tasks", "list<string>", [])
  field("updated_by", "Object", [])
  field("updated_time", "datetime", [])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{
      "name" => "role",
      "required" => false,
      "type" => "businessrolerequest_role",
      "values" => [
        "ADMIN",
        "ADS_RIGHTS_REVIEWER",
        "DEFAULT",
        "DEVELOPER",
        "EMPLOYEE",
        "FINANCE_ANALYST",
        "FINANCE_EDIT",
        "FINANCE_EDITOR",
        "FINANCE_VIEW",
        "MANAGE",
        "PARTNER_CENTER_ADMIN",
        "PARTNER_CENTER_ANALYST",
        "PARTNER_CENTER_EDUCATION",
        "PARTNER_CENTER_MARKETING",
        "PARTNER_CENTER_OPERATIONS"
      ]
    },
    %{
      "name" => "tasks",
      "required" => false,
      "type" => "list<businessrolerequest_tasks>",
      "values" => [
        "ADMIN",
        "ADS_RIGHTS_REVIEWER",
        "DEFAULT",
        "DEVELOPER",
        "EMPLOYEE",
        "FINANCE_ANALYST",
        "FINANCE_EDIT",
        "FINANCE_EDITOR",
        "FINANCE_VIEW",
        "MANAGE",
        "PARTNER_CENTER_ADMIN",
        "PARTNER_CENTER_ANALYST",
        "PARTNER_CENTER_EDUCATION",
        "PARTNER_CENTER_MARKETING",
        "PARTNER_CENTER_OPERATIONS"
      ]
    }
  ])

  finish()
end
