# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessRequest do
  use MetaAds.Model

  field("accessor", "Business", [])
  field("creation_time", "datetime", [])
  field("id", "string", [])
  field("object_id", "string", [])
  field("object_type", "string", [])
  field("permitted_tasks", "list<string>", [])
  field("request_status", "string", [])
  field("request_type", "string", [])
  field("requestor", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
