# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessObjectTransferOwnershipAgreement do
  use MetaAds.Model

  field("id", "string", [])
  field("receiving_business", "Business", [])
  field("requesting_business", "Business", [])
  field("status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
