# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessAdAccountRequest do
  use MetaAds.Model

  field("ad_account", "AdAccount", [])
  field("id", "string", [])

  finish()
end
