# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessUser do
  use MetaAds.Model

  field("business", "Business", [])
  field("business_role_request", "BusinessRoleRequest", [])
  field("email", "string", [])
  field("finance_permission", "string", [])
  field("first_name", "string", [])
  field("id", "string", [])
  field("ip_permission", "string", [])
  field("last_name", "string", [])
  field("marked_for_removal", "bool", [])
  field("name", "string", [])
  field("pending_email", "string", [])
  field("role", "string", [])
  field("tasks", "list<string>", [])
  field("title", "string", [])
  field("two_fac_status", "string", [])

  operation(:get_assigned_ad_accounts, "GET", "assigned_ad_accounts", nil, [])

  operation(:get_assigned_business_asset_groups, "GET", "assigned_business_asset_groups", nil, [
    %{"name" => "contained_asset_id", "required" => false, "type" => "string"}
  ])

  operation(:get_assigned_pages, "GET", "assigned_pages", nil, [
    %{"name" => "pages", "required" => false, "type" => "list<unsigned int>"}
  ])

  operation(:get_assigned_product_catalogs, "GET", "assigned_product_catalogs", nil, [])

  operation(
    :get_assigned_whatsapp_business_accounts,
    "GET",
    "assigned_whatsapp_business_accounts",
    nil,
    []
  )

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "clear_pending_email", "required" => false, "type" => "bool"},
    %{"name" => "email", "required" => false, "type" => "string"},
    %{"name" => "first_name", "required" => false, "type" => "string"},
    %{"name" => "last_name", "required" => false, "type" => "string"},
    %{"name" => "pending_email", "required" => false, "type" => "string"},
    %{
      "name" => "role",
      "required" => false,
      "type" => "businessuser_role",
      "values" => [
        "ADMIN",
        "ADS_RIGHTS_REVIEWER",
        "DEFAULT",
        "DEVELOPER",
        "EMPLOYEE",
        "FINANCE_ANALYST",
        "FINANCE_EDIT",
        "FINANCE_EDITOR",
        "FINANCE_VIEW",
        "MANAGE",
        "PARTNER_CENTER_ADMIN",
        "PARTNER_CENTER_ANALYST",
        "PARTNER_CENTER_EDUCATION",
        "PARTNER_CENTER_MARKETING",
        "PARTNER_CENTER_OPERATIONS"
      ]
    },
    %{"name" => "skip_verification_email", "required" => false, "type" => "bool"},
    %{
      "name" => "tasks",
      "required" => false,
      "type" => "list<businessuser_tasks>",
      "values" => [
        "ADMIN",
        "ADS_RIGHTS_REVIEWER",
        "DEFAULT",
        "DEVELOPER",
        "EMPLOYEE",
        "FINANCE_ANALYST",
        "FINANCE_EDIT",
        "FINANCE_EDITOR",
        "FINANCE_VIEW",
        "MANAGE",
        "PARTNER_CENTER_ADMIN",
        "PARTNER_CENTER_ANALYST",
        "PARTNER_CENTER_EDUCATION",
        "PARTNER_CENTER_MARKETING",
        "PARTNER_CENTER_OPERATIONS"
      ]
    },
    %{"name" => "title", "required" => false, "type" => "string"}
  ])

  finish()
end
