# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessFranchiseConfig do
  use MetaAds.Model

  field("active_partner_count", "int", [])
  field("agency_business", "Business", [])
  field("agency_business_asset_group", "BusinessAssetGroup", [])
  field("brand_name", "string", [])
  field("business", "Business", [])
  field("business_vertical", "string", [])
  field("id", "string", [])
  field("partner_count", "int", [])
  field("pending_agency_business", "string", [])
  field("program_count", "int", [])
  field("shared_business_asset_group", "BusinessAssetGroup", [])
  field("shared_creative_folder_count", "int", [])
  field("shared_custom_audience_count", "int", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
