# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessCreativeInsights do
  use MetaAds.Model

  field("actions", "list<AdsActionStats>", [])
  field("age", "string", [])
  field("country", "string", [])
  field("date_end", "string", [])
  field("date_start", "string", [])
  field("device_platform", "string", [])
  field("gender", "string", [])
  field("impressions", "int", [])
  field("inline_link_clicks", "int", [])
  field("objective", "string", [])
  field("optimization_goal", "string", [])
  field("platform_position", "string", [])
  field("publisher_platform", "string", [])
  field("quality_ranking", "string", [])
  field("video_play_actions", "list<AdsActionStats>", [])
  field("video_thruplay_watched_actions", "list<AdsActionStats>", [])

  finish()
end
