# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessApplicationRequest do
  use MetaAds.Model

  field("application", "Application", [])
  field("id", "string", [])

  finish()
end
