# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessObject do
  use MetaAds.Model

  field("asset", "Object", [])
  field("asset_type", "string", [])
  field("id", "string", [])
  field("name", "string", [])
  field("picture", "string", [])

  finish()
end
