# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessImage do
  use MetaAds.Model

  field("business", "Business", [])
  field("creation_time", "datetime", [])
  field("hash", "string", [])
  field("height", "int", [])
  field("id", "string", [])
  field("media_library_url", "string", [])
  field("name", "string", [])
  field("url", "string", [])
  field("url_128", "string", [])
  field("width", "int", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
