# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessPartnerPremiumOptions do
  use MetaAds.Model

  field("enable_basket_insight", "bool", [])
  field("enable_extended_audience_retargeting", "bool", [])
  field("retailer_custom_audience_config", "Object", [])

  finish()
end
