# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessVideo do
  use MetaAds.Model

  field("business", "Business", [])
  field("id", "string", [])
  field("media_library_url", "string", [])
  field("name", "string", [])
  field("video", "AdVideo", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
