# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessAgreement do
  use MetaAds.Model

  field("id", "string", [])
  field("request_status", "string", [])

  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "asset_id", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "request_status",
      "required" => false,
      "type" => "businessagreement_request_status",
      "values" => [
        "APPROVE",
        "CANCELED",
        "DECLINE",
        "EXPIRED",
        "IN_PROGRESS",
        "MMA_DIRECT_ASSETS_APPROVED",
        "MMA_DIRECT_ASSETS_DECLINED",
        "MMA_DIRECT_ASSETS_EXPIRED",
        "MMA_DIRECT_ASSETS_PENDING",
        "PENDING",
        "PENDING_EMAIL_VERIFICATION",
        "PENDING_INTEGRITY_REVIEW"
      ]
    }
  ])

  finish()
end
