# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.BusinessManagedPartnerEligibility do
  use MetaAds.Model

  field("is_eligible", "bool", [])
  field("reason_code", "string", [])
  field("reason_description", "string", [])

  finish()
end
