# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CampaignGroupBrandConfiguration do
  use MetaAds.Model

  field("brand_product_name", "string", [])
  field("locale", "string", [])
  field("vertical", "string", [])

  finish()
end
