# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CanvasTemplate do
  use MetaAds.Model

  field("channels", "list<map<string, list<map<string, string>>>>", [])
  field("description", "string", [])
  field("document", "Canvas", [])
  field("id", "string", [])
  field("is_multi_tab_supportable", "bool", [])
  field("is_new", "bool", [])
  field("name", "string", [])
  field("objectives", "list<map<Object, Object>>", [])
  field("owner_id", "User", [])
  field("required_capabilities", "list<string>", [])
  field("snapshot_photo", "Photo", [])
  field("status", "string", [])
  field("sub_verticals", "list<string>", [])
  field("verticals", "list<map<string, string>>", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
