# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CanvasCollectionThumbnail do
  use MetaAds.Model

  field("element_child_index", "int", [])
  field("element_id", "string", [])
  field("photo", "Photo", [])

  finish()
end
