# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CatalogItemChannelsToIntegrityStatus do
  use MetaAds.Model

  field("channels", "list<string>", [])
  field("rejection_information", "Object", [])

  finish()
end
