# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CatalogSmartPixelSettings do
  use MetaAds.Model

  field("allowed_domains", "list<string>", [])
  field("available_property_filters", "list<string>", [])
  field("catalog", "ProductCatalog", [])
  field("cbb_custom_override_filters", "list<Object>", [])
  field("cbb_default_filter", "list<map<string, list<string>>>", [])
  field("defaults", "list<map<string, string>>", [])
  field("filters", "list<map<string, list<string>>>", [])
  field("id", "string", [])
  field("is_cbb_enabled", "bool", [])
  field("is_create_enabled", "bool", [])
  field("is_delete_enabled", "bool", [])
  field("is_update_enabled", "bool", [])
  field("microdata_format_precedence", "list<string>", [])
  field("pixel", "AdsPixel", [])
  field("property_filter", "list<string>", [])
  field("trusted_domains", "list<string>", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
