# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CatalogItemAppLinks do
  use MetaAds.Model

  field("android", "list<AndroidAppLink>", [])
  field("ios", "list<IosAppLink>", [])
  field("ipad", "list<IosAppLink>", [])
  field("iphone", "list<IosAppLink>", [])
  field("web", "WebAppLink", [])
  field("windows", "list<WindowsAppLink>", [])
  field("windows_phone", "list<WindowsPhoneAppLink>", [])
  field("windows_universal", "list<WindowsAppLink>", [])

  finish()
end
