# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CatalogItemRejectionReasons do
  use MetaAds.Model

  field("capability", "string", [])
  field("rejection_information", "list<Object>", [])

  finish()
end
