# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CatalogSubscribedApps do
  use MetaAds.Model

  operation(:delete_subscribed_apps, "DELETE", "subscribed_apps", nil, [])
  finish()
end
