# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CatalogDuplicateData do
  use MetaAds.Model

  field("best_catalog_id", "string", [])
  field("is_duplicated_catalog", "bool", [])

  finish()
end
