# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CatalogCollection do
  use MetaAds.Model

  field("description", "string", [])
  field("title", "string", [])
  field("url", "string", [])

  finish()
end
