# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CatalogGenericIngestionSessionErrorsGet do
  use MetaAds.Model

  field("data", "list<object>", [])

  finish()
end
