# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CollaborativeAdsShareSettings do
  use MetaAds.Model

  field("agency_business", "Business", [])
  field("id", "string", [])
  field("product_catalog_proxy_id", "string", [])
  field("utm_campaign", "string", [])
  field("utm_medium", "string", [])
  field("utm_source", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
