# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ColumnSuggestions do
  use MetaAds.Model

  field("explanations", "Object", [])
  field("format", "list<string>", [])
  field("objective", "list<string>", [])
  field("optimization_goals", "list<string>", [])

  finish()
end
