# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Comment do
  use MetaAds.Model

  field("admin_creator", "User", [])
  field("application", "Application", [])
  field("attachment", "Object", [])
  field("can_comment", "bool", [])
  field("can_hide", "bool", [])
  field("can_like", "bool", [])
  field("can_remove", "bool", [])
  field("can_reply_privately", "bool", [])
  field("comment_count", "unsigned int", [])
  field("created_time", "datetime", [])
  field("from", "Object", [])
  field("id", "string", [])
  field("is_hidden", "bool", [])
  field("is_private", "bool", [])
  field("like_count", "unsigned int", [])
  field("live_broadcast_timestamp", "unsigned int", [])
  field("message", "string", [])
  field("message_tags", "list<EntityAtTextRange>", [])
  field("object", "Object", [])
  field("parent", "Comment", [])
  field("permalink_url", "string", [])
  field("private_reply_conversation", "Object", [])
  field("user_likes", "bool", [])

  operation(:get_comments, "GET", "comments", nil, [
    %{
      "name" => "filter",
      "required" => false,
      "type" => "commentcomments_filter_enum_param",
      "values" => ["stream", "toplevel"]
    },
    %{
      "name" => "live_filter",
      "required" => false,
      "type" => "commentcomments_live_filter_enum_param",
      "values" => ["filter_low_quality", "no_filter"]
    },
    %{
      "name" => "order",
      "required" => false,
      "type" => "commentcomments_order_enum_param",
      "values" => ["chronological", "reverse_chronological"]
    },
    %{"name" => "since", "required" => false, "type" => "datetime"}
  ])

  operation(:create_comments, "POST", "comments", nil, [
    %{"name" => "attachment_id", "required" => false, "type" => "string"},
    %{"name" => "attachment_share_url", "required" => false, "type" => "string"},
    %{"name" => "attachment_url", "required" => false, "type" => "string"},
    %{
      "name" => "comment_privacy_value",
      "required" => false,
      "type" => "commentcomments_comment_privacy_value_enum_param",
      "values" => [
        "DECLINED_BY_ADMIN_ASSISTANT",
        "DEFAULT_PRIVACY",
        "FRIENDS_AND_POST_OWNER",
        "FRIENDS_ONLY",
        "GRAPHQL_MULTIPLE_VALUE_HACK_DO_NOT_USE",
        "OWNER_OR_COMMENTER",
        "PENDING_APPROVAL",
        "PRIVATE_CONVERSATION_PARTICIPANTS_ONLY",
        "REMOVED_BY_ADMIN_ASSISTANT",
        "SIDE_CONVERSATION",
        "SIDE_CONVERSATION_AND_POST_OWNER",
        "SPOTLIGHT_TAB"
      ]
    },
    %{"name" => "facepile_mentioned_ids", "required" => false, "type" => "list<string>"},
    %{"name" => "feedback_source", "required" => false, "type" => "string"},
    %{"name" => "is_offline", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "object_id", "required" => false, "type" => "string"},
    %{"name" => "parent_comment_id", "required" => false, "type" => "Object"},
    %{"name" => "text", "required" => false, "type" => "string"},
    %{"name" => "tracking", "required" => false, "type" => "string"}
  ])

  operation(:delete_likes, "DELETE", "likes", nil, [
    %{"name" => "attribution_id_v2", "required" => false, "type" => "string"},
    %{"name" => "feedback_source", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "tracking", "required" => false, "type" => "string"}
  ])

  operation(:get_likes, "GET", "likes", nil, [])

  operation(:create_likes, "POST", "likes", nil, [
    %{"name" => "attribution_id_v2", "required" => false, "type" => "string"},
    %{"name" => "feedback_source", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "tracking", "required" => false, "type" => "string"}
  ])

  operation(:get_reactions, "GET", "reactions", nil, [
    %{
      "name" => "type",
      "required" => false,
      "type" => "commentreactions_type_enum_param",
      "values" => [
        "ANGRY",
        "CARE",
        "FIRE",
        "HAHA",
        "HUNDRED",
        "LIKE",
        "LOVE",
        "NONE",
        "PRIDE",
        "SAD",
        "THANKFUL",
        "WOW"
      ]
    }
  ])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "attachment_id", "required" => false, "type" => "string"},
    %{"name" => "attachment_share_url", "required" => false, "type" => "string"},
    %{"name" => "attachment_url", "required" => false, "type" => "string"},
    %{"name" => "is_hidden", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"}
  ])

  finish()
end
