# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CommerceMerchantSettingsSetupStatus do
  use MetaAds.Model

  field("deals_setup", "string", [])
  field("marketplace_approval_status", "string", [])
  field("marketplace_approval_status_details", "Object", [])
  field("payment_setup", "string", [])
  field("review_status", "Object", [])
  field("shop_setup", "string", [])

  finish()
end
