# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CommerceOrder do
  use MetaAds.Model

  field("buyer_details", "Object", [])
  field("channel", "string", [])
  field("contains_bopis_items", "bool", [])
  field("created", "string", [])
  field("estimated_payment_details", "Object", [])
  field("id", "string", [])
  field("is_group_buy", "bool", [])
  field("is_test_order", "bool", [])
  field("last_updated", "string", [])
  field("merchant_order_id", "string", [])
  field("order_status", "Object", [])
  field("selected_shipping_option", "Object", [])
  field("ship_by_date", "string", [])
  field("shipping_address", "Object", [])

  operation(:create_shipments, "POST", "shipments", nil, [
    %{"name" => "external_redemption_link", "required" => false, "type" => "string"},
    %{"name" => "external_shipment_id", "required" => false, "type" => "string"},
    %{"name" => "fulfillment", "required" => false, "type" => "map"},
    %{"name" => "idempotency_key", "required" => true, "type" => "string"},
    %{"name" => "items", "required" => false, "type" => "list<map>"},
    %{"name" => "merchant_order_reference", "required" => false, "type" => "string"},
    %{"name" => "shipment_origin_postal_code", "required" => false, "type" => "string"},
    %{"name" => "shipping_tax_details", "required" => false, "type" => "map"},
    %{"name" => "should_use_default_fulfillment_location", "required" => false, "type" => "bool"},
    %{"name" => "tracking_info", "required" => false, "type" => "map"}
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
