# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CommerceMerchantSettings do
  use MetaAds.Model

  field("checkout_config", "string", [])
  field("contact_email", "string", [])
  field("display_name", "string", [])
  field("facebook_channel", "Object", [])
  field("id", "string", [])
  field("instagram_channel", "Object", [])
  field("korea_ftc_listing", "string", [])
  field("merchant_page", "Profile", [])
  field("merchant_status", "string", [])
  field("offsite_iab_checkout_enabled_countries", "list<string>", [])
  field("payment_provider", "string", [])
  field("privacy_policy_localized", "string", [])
  field("shops_ads_setup", "Object", [])
  field("terms", "string", [])

  operation(:get_commerce_orders, "GET", "commerce_orders", nil, [
    %{
      "name" => "filters",
      "required" => false,
      "type" => "list<commercemerchantsettingscommerce_orders_filters_enum_param>",
      "values" => [
        "HAS_CANCELLATIONS",
        "HAS_FULFILLMENTS",
        "HAS_REFUNDS",
        "NO_CANCELLATIONS",
        "NO_REFUNDS",
        "NO_SHIPMENTS"
      ]
    },
    %{
      "name" => "state",
      "required" => false,
      "type" => "list<commercemerchantsettingscommerce_orders_state_enum_param>",
      "values" => ["COMPLETED", "CREATED", "FB_PROCESSING", "IN_PROGRESS"]
    },
    %{"name" => "updated_after", "required" => false, "type" => "datetime"},
    %{"name" => "updated_before", "required" => false, "type" => "datetime"}
  ])

  operation(:get_commerce_payouts, "GET", "commerce_payouts", nil, [
    %{"name" => "end_time", "required" => false, "type" => "datetime"},
    %{"name" => "start_time", "required" => false, "type" => "datetime"}
  ])

  operation(:get_order_management_apps, "GET", "order_management_apps", nil, [])
  operation(:get_product_catalogs, "GET", "product_catalogs", nil, [])
  operation(:get_setup_status, "GET", "setup_status", nil, [])

  operation(:create_shipping_profiles, "POST", "shipping_profiles", nil, [
    %{"name" => "handling_time", "required" => false, "type" => "map"},
    %{"name" => "is_default", "required" => false, "type" => "bool"},
    %{"name" => "is_default_shipping_profile", "required" => false, "type" => "bool"},
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "reference_id", "required" => false, "type" => "string"},
    %{"name" => "shipping_destinations", "required" => true, "type" => "list<map>"}
  ])

  operation(:get_shops, "GET", "shops", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "checkout_config", "required" => false, "type" => "map"},
    %{"name" => "korea_ftc_listing", "required" => false, "type" => "string"},
    %{
      "name" => "merchant_status",
      "required" => false,
      "type" => "commercemerchantsettings_merchant_status",
      "values" => ["ENABLED", "EXTERNALLY_DISABLED"]
    },
    %{"name" => "privacy_policy_localized", "required" => false, "type" => "map"}
  ])

  finish()
end
