# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CommerceOrderTransactionDetail do
  use MetaAds.Model

  field("merchant_order_id", "string", [])
  field("net_payment_amount", "Object", [])
  field("order_created", "string", [])
  field("order_details", "CommerceOrder", [])
  field("order_id", "string", [])
  field("payout_reference_id", "string", [])
  field("postal_code", "string", [])
  field("processing_fee", "Object", [])
  field("state", "string", [])
  field("tax_rate", "string", [])
  field("transaction_date", "string", [])
  field("transaction_type", "string", [])
  field("transfer_id", "string", [])

  finish()
end
