# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ContactsMessengerSyncConfig do
  use MetaAds.Model

  field("enabled", "bool", [])

  finish()
end
