# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ContentDeliveryReport do
  use MetaAds.Model

  field("content_id", "string", [])
  field("creator_id", "string", [])
  field("estimated_impressions", "unsigned int", [])

  finish()
end
