# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ContentBlockList do
  use MetaAds.Model

  field("business", "Business", [])
  field("id", "string", [])
  field("name", "string", [])

  operation(:get_applied_ad_accounts, "GET", "applied_ad_accounts", nil, [])
  operation(:get_facebook_content, "GET", "facebook_content", nil, [])
  operation(:get_instagram_content, "GET", "instagram_content", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
