# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ContentPublishingLimitResponse do
  use MetaAds.Model

  field("config", "Object", [])
  field("quota_usage", "int", [])

  finish()
end
