# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ConversionHealthKPI do
  use MetaAds.Model

  field("health_indicator", "string", [])
  field("impacted_browsers_match_rate", "float", [])
  field("impacted_browsers_match_rate_mom_trend", "float", [])
  field("impacted_browsers_traffic_share", "float", [])
  field("impacted_browsers_traffic_share_mom_trend", "float", [])
  field("match_rate", "float", [])
  field("match_rate_mom_trend", "float", [])
  field("match_rate_vertical_benchmark", "float", [])
  field("match_rate_vs_benchmark_mom_trend", "float", [])

  finish()
end
