# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CopyrightOwnershipTransfer do
  use MetaAds.Model

  field("assets", "list<Object>", [])
  field("has_ownership_been_updated", "bool", [])
  field("id", "string", [])
  field("num_assets", "int", [])
  field("receiving_rights_holder_owner", "Object", [])
  field("sending_rights_holder_owner", "Object", [])
  field("status", "string", [])
  field("transfer_territories", "list<string>", [])
  field("transfer_time", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
