# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CopyrightReferenceContainer do
  use MetaAds.Model

  field("content_type", "string", [])
  field("copyright_creation_time", "datetime", [])
  field("download_hd_url", "string", [])
  field("duration_in_sec", "float", [])
  field("id", "string", [])
  field("iswc", "string", [])
  field("metadata", "Object", [])
  field("playable_video_uri", "string", [])
  field("published_time", "datetime", [])
  field("thumbnail_url", "string", [])
  field("title", "string", [])
  field("universal_content_id", "string", [])
  field("writer_names", "list<string>", [])

  finish()
end
