# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CopyrightMediaMisuse do
  use MetaAds.Model

  field("audio_segments", "list<Object>", [])
  field("creation_time", "datetime", [])
  field("disabled_audio_segments", "list<Object>", [])
  field("disabled_video_segments", "list<Object>", [])
  field("entire_file_issue", "bool", [])
  field("entire_file_issue_reasons", "list<string>", [])
  field("expiration_time", "datetime", [])
  field("id", "string", [])
  field("media_asset_id", "string", [])
  field("reasons", "list<string>", [])
  field("requested_audio_segments", "list<Object>", [])
  field("requested_video_segments", "list<Object>", [])
  field("resolution_type", "string", [])
  field("status", "string", [])
  field("update_time", "datetime", [])
  field("video_copyright", "VideoCopyright", [])
  field("video_segments", "list<Object>", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
