# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CopyrightAttributionInsights do
  use MetaAds.Model

  field("l7_attribution_page_view", "int", [])
  field("l7_attribution_page_view_delta", "float", [])
  field("l7_attribution_video_view", "int", [])
  field("l7_attribution_video_view_delta", "float", [])
  field("metrics_ending_date", "string", [])

  finish()
end
