# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CPASSetupPageStructureProgress do
  use MetaAds.Model

  field("id", "string", [])
  field("issues", "list<Object>", [])
  field("name", "string", [])

  finish()
end
