# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CPASBusinessSetupConfig do
  use MetaAds.Model

  field("accepted_collab_ads_tos", "bool", [])
  field("business", "Business", [])
  field("business_capabilities_status", "list<map<string, string>>", [])
  field("capabilities_compliance_status", "list<map<string, Object>>", [])
  field("id", "string", [])

  operation(:get_ad_accounts, "GET", "ad_accounts", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
