# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CPASMerchantConfig do
  use MetaAds.Model

  field("accepted_tos", "bool", [])
  field("beta_features", "list<string>", [])
  field("business_outcomes_status", "list<map<string, string>>", [])
  field("id", "string", [])
  field("is_test_merchant", "bool", [])
  field("outcomes_compliance_status", "list<map<string, Object>>", [])
  field("qualified_to_onboard", "bool", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
