# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CPASParentCatalogSettings do
  use MetaAds.Model

  field("attribution_windows", "list<string>", [])
  field("default_currency", "string", [])
  field("disable_use_as_parent_catalog", "bool", [])
  field("id", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
