# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CreativeAudiencePairingPersona do
  use MetaAds.Model

  field("age_max", "int", [])
  field("age_min", "int", [])
  field("genders", "list<unsigned int>", [])

  finish()
end
