# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CreativeHistory do
  use MetaAds.Model

  field("creative_fingerprint", "int", [])
  field("time_ranges", "list<Object>", [])

  finish()
end
