# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CreatorAssetCreative do
  use MetaAds.Model

  field("id", "string", [])
  field("image_url", "string", [])
  field("moderation_status", "string", [])
  field("product_item_retailer_id", "string", [])
  field("product_url", "string", [])
  field("retailer_id", "string", [])
  field("video_url", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
