# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CreativeMulticellTestConfig do
  use MetaAds.Model

  field("budget_percentage", "int", [])
  field("budget_source", "string", [])
  field("configured_cell_count", "int", [])
  field("daily_budget", "int", [])
  field("entry_source", "string", [])
  field("lead_gen_forms", "string", [])
  field("lifetime_budget", "int", [])
  field("use_existing_daily_budget", "bool", [])

  finish()
end
