# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CreditCard do
  use MetaAds.Model

  field("billing_address", "Object", [])
  field("card_cobadging", "string", [])
  field("card_holder_name", "string", [])
  field("card_type", "string", [])
  field("credential_id", "int", [])
  field("default_receiving_method_products", "list<string>", [])
  field("expiry_month", "string", [])
  field("expiry_year", "string", [])
  field("id", "string", [])
  field("is_cvv_tricky_bin", "bool", [])
  field("is_enabled", "bool", [])
  field("is_last_used", "bool", [])
  field("is_network_tokenized_in_india", "bool", [])
  field("is_soft_disabled", "bool", [])
  field("is_user_verified", "bool", [])
  field("is_zip_verified", "bool", [])
  field("last4", "string", [])
  field("readable_card_type", "string", [])
  field("time_created", "datetime", [])
  field("time_created_ts", "int", [])
  field("type", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
