# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CRMAddress do
  use MetaAds.Model

  field("city", "string", [])
  field("cnpj_tax_id", "string", [])
  field("country", "string", [])
  field("id", "string", [])
  field("postal_code", "string", [])
  field("registration_label", "string", [])
  field("registration_number", "string", [])
  field("state", "string", [])
  field("street1", "string", [])
  field("street2", "string", [])
  field("street3", "string", [])
  field("street4", "string", [])
  field("validation_status", "string", [])
  field("vat_tax_id", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
