# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CTWAWhatsAppNumbersInfo do
  use MetaAds.Model

  field("can_manage_wa_flows", "bool", [])
  field("formatted_whatsapp_number", "string", [])
  field("is_business_number", "bool", [])
  field("is_calling_enabled", "bool", [])
  field("number_country_prefix", "string", [])
  field("page_whatsapp_number_id", "string", [])
  field("waba_id", "string", [])
  field("whatsapp_number", "string", [])
  field("whatsapp_smb_device", "string", [])

  finish()
end
