# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomConversionActivities do
  use MetaAds.Model

  field("app_id", "unsigned int", [])
  field("data", "string", [])
  field("event_type", "string", [])
  field("timestamp", "datetime", [])

  finish()
end
