# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomAudienceIntegrityFlagsAndAppealStatus do
  use MetaAds.Model

  field("closeout_time", "unsigned int", [])
  field("days_until_enforcement", "unsigned int", [])
  field("flagged_fields", "list<string>", [])
  field("is_enforcement_rolled_out", "bool", [])
  field("latest_appeal_requestor", "string", [])
  field("latest_appeal_time", "unsigned int", [])
  field("restriction_status", "string", [])

  finish()
end
