# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomAudienceCapabilities do
  use MetaAds.Model

  field("capabilities", "map", [])

  finish()
end
