# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomAudienceSharingStatus do
  use MetaAds.Model

  field("sharing_relationship_id", "unsigned int", [])
  field("status", "string", [])

  finish()
end
