# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomAudiencesTOS do
  use MetaAds.Model

  field("content", "string", [])
  field("id", "string", [])
  field("type", "string", [])

  finish()
end
