# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomAudienceMatchRateInsights do
  use MetaAds.Model

  field("email_quality", "string", [])
  field("email_upload_volume_pct", "float", [])
  field("is_eligible", "bool", [])
  field("madid_quality", "string", [])
  field("madid_upload_volume_pct", "float", [])
  field("match_rate_score", "float", [])
  field("phone_quality", "string", [])
  field("phone_upload_volume_pct", "float", [])

  finish()
end
