# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomAudienceHealth do
  use MetaAds.Model

  field("health", "list<Object>", [])

  finish()
end
