# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomAudiencesharedAccountInfo do
  use MetaAds.Model

  field("account_id", "string", [])
  field("account_name", "string", [])
  field("business_id", "string", [])
  field("business_name", "string", [])
  field("sharing_status", "string", [])

  finish()
end
