# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomAudienceSalts do
  use MetaAds.Model

  field("app_id", "int", [])
  field("public_key", "string", [])
  field("salts", "list<Object>", [])
  field("user_id", "int", [])

  finish()
end
