# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.CustomUserSettings do
  use MetaAds.Model

  field("page_level_persistent_menu", "list<Object>", [])
  field("user_level_persistent_menu", "list<Object>", [])

  finish()
end
