# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.DeliveryStatus do
  use MetaAds.Model

  field("status", "string", [])
  field("substatuses", "list<string>", [])

  finish()
end
