# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.DeliveryCheckExtraInfo do
  use MetaAds.Model

  field("adgroup_ids", "list<string>", [])
  field("campaign_ids", "list<string>", [])
  field("countries", "list<string>", [])

  finish()
end
