# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.DeliveryCheck do
  use MetaAds.Model

  field("check_name", "string", [])
  field("description", "string", [])
  field("extra_info", "DeliveryCheckExtraInfo", [])
  field("summary", "string", [])

  finish()
end
