# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.DraftPost do
  use MetaAds.Model

  field("admin_creator", "User", [])
  field("creation_time", "datetime", [])
  field("feed_audience_description", "string", [])
  field("feed_targeting", "Targeting", [])
  field("id", "string", [])
  field("is_post_in_good_state", "bool", [])
  field("message", "string", [])
  field("modified_time", "datetime", [])
  field("og_action_summary", "string", [])
  field("permalink_url", "string", [])
  field("place", "Place", [])
  field("privacy_description", "string", [])
  field("scheduled_failure_notice", "string", [])
  field("scheduled_publish_time", "datetime", [])
  field("story_token", "string", [])
  field("thumbnail", "string", [])
  field("video_id", "string", [])

  finish()
end
