# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.DynamicItemDisplayBundle do
  use MetaAds.Model

  field("additional_urls", "list<map<string, string>>", [])
  field("description", "string", [])
  field("id", "string", [])
  field("name", "string", [])
  field("product_set", "ProductSet", [])
  field("text_tokens", "list<map<string, string>>", [])
  field("url", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
