# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.DynamicVideoMetadata do
  use MetaAds.Model

  field("id", "string", [])
  field("tags", "list<string>", [])
  field("url", "string", [])
  field("video", "AdVideo", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
