# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.DynamicItemDisplayBundleFolder do
  use MetaAds.Model

  field("categorization_criteria", "string", [])
  field("id", "string", [])
  field("name", "string", [])
  field("product_catalog", "ProductCatalog", [])
  field("product_set", "ProductSet", [])
  field("valid_labels", "list<map<string, list<string>>>", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
