# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.DynamicPostChildAttachment do
  use MetaAds.Model

  field("description", "string", [])
  field("image_url", "string", [])
  field("link", "string", [])
  field("place_id", "string", [])
  field("product_id", "string", [])
  field("title", "string", [])

  finish()
end
