# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.EducationExperience do
  use MetaAds.Model

  field("classes", "list<Experience>", [])
  field("concentration", "list<Page>", [])
  field("degree", "Page", [])
  field("id", "string", [])
  field("school", "Page", [])
  field("type", "string", [])
  field("with", "list<User>", [])
  field("year", "Page", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
