# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Engagement do
  use MetaAds.Model

  field("count", "unsigned int", [])
  field("count_string", "string", [])
  field("count_string_with_like", "string", [])
  field("count_string_without_like", "string", [])
  field("social_sentence", "string", [])
  field("social_sentence_with_like", "string", [])
  field("social_sentence_without_like", "string", [])

  finish()
end
