# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.EntWithSponsor do
  use MetaAds.Model

  field("has_audio_swapped_fb_copy", "bool", [])
  field("id", "string", [])
  field("is_branded_content", "bool", [])
  field("owner_linked_instagram_user_v1_id", "string", [])
  field("owner_picture", "string", [])
  field("post_id", "string", [])
  field("post_info", "Post", [])
  field("promotable_id", "string", [])

  finish()
end
