# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.EntityAtTextRange do
  use MetaAds.Model

  field("id", "string", [])
  field("length", "unsigned int", [])
  field("name", "string", [])
  field("object", "Profile", [])
  field("offset", "unsigned int", [])
  field("type", "EntityAtTextRange_type", ["application", "event", "group", "page", "user"])

  finish()
end
