# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.EventRegistrationSetting do
  use MetaAds.Model

  field("id", "string", [])
  field("questions", "string", [])
  field("target_type", "string", [])
  field("ticket_tier_ids", "list<string>", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
