# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Event do
  use MetaAds.Model

  field("attending_count", "int", [])
  field("can_guests_invite", "bool", [])

  field("category", "Event_category", [
    "CLASSIC_LITERATURE",
    "COMEDY",
    "CRAFTS",
    "DANCE",
    "DRINKS",
    "FITNESS_AND_WORKOUTS",
    "FOODS",
    "GAMES",
    "GARDENING",
    "HEALTHY_LIVING_AND_SELF_CARE",
    "HEALTH_AND_MEDICAL",
    "HOME_AND_GARDEN",
    "MUSIC_AND_AUDIO",
    "PARTIES",
    "PROFESSIONAL_NETWORKING",
    "RELIGIONS",
    "SHOPPING_EVENT",
    "SOCIAL_ISSUES",
    "SPORTS",
    "THEATER",
    "TV_AND_MOVIES",
    "VISUAL_ARTS"
  ])

  field("cover", "CoverPhoto", [])
  field("created_time", "datetime", [])
  field("declined_count", "int", [])
  field("description", "string", [])
  field("discount_code_enabled", "bool", [])
  field("end_time", "string", [])
  field("event_times", "list<ChildEvent>", [])
  field("guest_list_enabled", "bool", [])
  field("id", "string", [])
  field("interested_count", "int", [])
  field("is_canceled", "bool", [])
  field("is_draft", "bool", [])
  field("is_online", "bool", [])
  field("is_page_owned", "bool", [])
  field("maybe_count", "int", [])
  field("name", "string", [])
  field("noreply_count", "int", [])

  field("online_event_format", "Event_online_event_format", [
    "fb_live",
    "horizon_event",
    "messenger_room",
    "none",
    "other",
    "third_party"
  ])

  field("online_event_third_party_url", "string", [])
  field("owner", "Object", [])
  field("parent_group", "Group", [])
  field("place", "Place", [])
  field("registration_setting", "EventRegistrationSetting", [])
  field("scheduled_publish_time", "string", [])
  field("start_time", "string", [])
  field("ticket_setting", "EventTicketSetting", [])
  field("ticket_uri", "string", [])
  field("ticket_uri_start_sales_time", "string", [])
  field("ticketing_privacy_uri", "string", [])
  field("ticketing_terms_uri", "string", [])
  field("timezone", "string", [])

  field("type", "Event_type", [
    "community",
    "friends",
    "group",
    "messenger_community",
    "private",
    "public",
    "work_company"
  ])

  field("updated_time", "datetime", [])

  operation(:get_comments, "GET", "comments", nil, [])
  operation(:get_feed, "GET", "feed", nil, [])
  operation(:get_live_videos, "GET", "live_videos", nil, [])

  operation(:create_live_videos, "POST", "live_videos", nil, [
    %{"name" => "content_tags", "required" => false, "type" => "list<string>"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "enable_backup_ingest", "required" => false, "type" => "bool"},
    %{"name" => "encoding_settings", "required" => false, "type" => "string"},
    %{"name" => "event_params", "required" => false, "type" => "Object"},
    %{"name" => "fisheye_video_cropped", "required" => false, "type" => "bool"},
    %{"name" => "front_z_rotation", "required" => false, "type" => "float"},
    %{"name" => "is_audio_only", "required" => false, "type" => "bool"},
    %{"name" => "is_spherical", "required" => false, "type" => "bool"},
    %{"name" => "original_fov", "required" => false, "type" => "unsigned int"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{
      "name" => "projection",
      "required" => false,
      "type" => "eventlive_videos_projection_enum_param",
      "values" => ["CUBEMAP", "EQUIRECTANGULAR", "HALF_EQUIRECTANGULAR"]
    },
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "schedule_custom_profile_image", "required" => false, "type" => "file"},
    %{
      "name" => "spatial_audio_format",
      "required" => false,
      "type" => "eventlive_videos_spatial_audio_format_enum_param",
      "values" => ["ambiX_4"]
    },
    %{
      "name" => "status",
      "required" => false,
      "type" => "eventlive_videos_status_enum_param",
      "values" => [
        "LIVE_NOW",
        "SCHEDULED_CANCELED",
        "SCHEDULED_LIVE",
        "SCHEDULED_UNPUBLISHED",
        "UNPUBLISHED"
      ]
    },
    %{
      "name" => "stereoscopic_mode",
      "required" => false,
      "type" => "eventlive_videos_stereoscopic_mode_enum_param",
      "values" => ["LEFT_RIGHT", "MONO", "MULTI_VIEW", "TOP_BOTTOM"]
    },
    %{"name" => "stop_on_delete_stream", "required" => false, "type" => "bool"},
    %{
      "name" => "stream_type",
      "required" => false,
      "type" => "eventlive_videos_stream_type_enum_param",
      "values" => ["AMBIENT", "REGULAR"]
    },
    %{"name" => "title", "required" => false, "type" => "string"}
  ])

  operation(:get_photos, "GET", "photos", nil, [])
  operation(:get_picture, "GET", "picture", nil, [])
  operation(:get_posts, "GET", "posts", nil, [])
  operation(:get_roles, "GET", "roles", nil, [])
  operation(:get_ticket_tiers, "GET", "ticket_tiers", nil, [])
  operation(:get_videos, "GET", "videos", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
