# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.EventTicketSetting do
  use MetaAds.Model

  field("id", "string", [])
  field("ticket_delivery_type", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
