# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Experience do
  use MetaAds.Model

  field("description", "string", [])
  field("from", "Object", [])
  field("id", "string", [])
  field("name", "string", [])
  field("with", "list<User>", [])

  finish()
end
