# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ExtendedCreditAllocationConfig do
  use MetaAds.Model

  field("currency_amount", "CurrencyAmount", [])
  field("id", "string", [])
  field("liability_type", "string", [])
  field("owning_business", "Business", [])
  field("owning_credential", "ExtendedCredit", [])
  field("partition_type", "string", [])
  field("receiving_business", "Business", [])
  field("receiving_credential", "ExtendedCredit", [])
  field("request_status", "string", [])
  field("send_bill_to", "string", [])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "amount", "required" => false, "type" => "Object"}
  ])

  finish()
end
