# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ExtendedCreditInvoiceGroup do
  use MetaAds.Model

  field("auto_enroll", "bool", [])
  field("bill_to_address", "CRMAddress", [])
  field("customer_po_number", "string", [])
  field("email", "ExtendedCreditEmail", [])
  field("emails", "list<string>", [])
  field("id", "string", [])
  field("liable_address", "CRMAddress", [])
  field("name", "string", [])
  field("sold_to_address", "CRMAddress", [])

  operation(:delete_ad_accounts, "DELETE", "ad_accounts", nil, [
    %{"name" => "ad_account_id", "required" => true, "type" => "string"}
  ])

  operation(:get_ad_accounts, "GET", "ad_accounts", nil, [])

  operation(:create_ad_accounts, "POST", "ad_accounts", nil, [
    %{"name" => "ad_account_id", "required" => true, "type" => "string"}
  ])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "emails", "required" => false, "type" => "list<string>"},
    %{"name" => "name", "required" => false, "type" => "string"}
  ])

  finish()
end
