# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ExtendedCredit do
  use MetaAds.Model

  field("allocated_amount", "CurrencyAmount", [])
  field("balance", "CurrencyAmount", [])
  field("credit_available", "CurrencyAmount", [])
  field("credit_type", "string", [])
  field("id", "string", [])
  field("is_access_revoked", "bool", [])
  field("is_automated_experience", "bool", [])
  field("legal_entity_name", "string", [])
  field("liable_address", "CRMAddress", [])
  field("liable_biz_name", "string", [])
  field("max_balance", "CurrencyAmount", [])
  field("online_max_balance", "CurrencyAmount", [])
  field("owner_business", "Business", [])
  field("owner_business_name", "string", [])
  field("partition_from", "string", [])
  field("receiving_credit_allocation_config", "ExtendedCreditAllocationConfig", [])
  field("send_bill_to_address", "CRMAddress", [])
  field("send_bill_to_biz_name", "string", [])
  field("sold_to_address", "CRMAddress", [])

  operation(:get_extended_credit_invoice_groups, "GET", "extended_credit_invoice_groups", nil, [])

  operation(
    :create_extended_credit_invoice_groups,
    "POST",
    "extended_credit_invoice_groups",
    nil,
    [
      %{"name" => "emails", "required" => true, "type" => "list<string>"},
      %{"name" => "name", "required" => true, "type" => "string"}
    ]
  )

  operation(
    :get_owning_credit_allocation_configs,
    "GET",
    "owning_credit_allocation_configs",
    nil,
    [%{"name" => "receiving_business_id", "required" => false, "type" => "string"}]
  )

  operation(
    :create_owning_credit_allocation_configs,
    "POST",
    "owning_credit_allocation_configs",
    nil,
    [
      %{"name" => "amount", "required" => false, "type" => "Object"},
      %{
        "name" => "liability_type",
        "required" => false,
        "type" => "extendedcreditowning_credit_allocation_configs_liability_type_enum_param",
        "values" => ["", "MSA", "Normal", "Sequential"]
      },
      %{
        "name" => "partition_type",
        "required" => false,
        "type" => "extendedcreditowning_credit_allocation_configs_partition_type_enum_param",
        "values" => ["AUTH", "FIXED", "FIXED_WITHOUT_PARTITION"]
      },
      %{"name" => "receiving_business_id", "required" => true, "type" => "string"},
      %{
        "name" => "send_bill_to",
        "required" => false,
        "type" => "extendedcreditowning_credit_allocation_configs_send_bill_to_enum_param",
        "values" => ["", "Advertiser", "Agency"]
      }
    ]
  )

  operation(:create_whatsapp_credit_attach, "POST", "whatsapp_credit_attach", nil, [
    %{"name" => "waba_currency", "required" => true, "type" => "string"},
    %{"name" => "waba_id", "required" => true, "type" => "string"}
  ])

  operation(:create_whatsapp_credit_sharing, "POST", "whatsapp_credit_sharing", nil, [
    %{"name" => "receiving_business_id", "required" => true, "type" => "string"}
  ])

  operation(
    :create_whatsapp_credit_sharing_and_attach,
    "POST",
    "whatsapp_credit_sharing_and_attach",
    nil,
    [
      %{"name" => "waba_currency", "required" => true, "type" => "string"},
      %{"name" => "waba_id", "required" => true, "type" => "string"}
    ]
  )

  operation(:get, "GET", "", nil, [])
  finish()
end
