# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ExtendedCreditApplication do
  use MetaAds.Model

  field("billing_country", "string", [])
  field("city", "string", [])
  field("cnpj", "string", [])
  field("country", "string", [])
  field("display_currency", "string", [])
  field("duns_number", "string", [])
  field("id", "string", [])
  field("invoice_email_address", "string", [])
  field("is_umi", "bool", [])
  field("legal_entity_name", "string", [])
  field("original_online_limit", "CurrencyAmount", [])
  field("phone_number", "string", [])
  field("postal_code", "string", [])
  field("product_types", "list<string>", [])
  field("proposed_credit_limit", "CurrencyAmount", [])
  field("registration_number", "string", [])
  field("run_id", "string", [])
  field("state", "string", [])
  field("status", "string", [])
  field("street1", "string", [])
  field("street2", "string", [])
  field("submitter", "User", [])
  field("tax_exempt_status", "string", [])
  field("tax_id", "string", [])
  field("terms", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
