# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ExternalEventSourceCPASEventsDebuggingInfo do
  use MetaAds.Model

  field("counts", "int", [])
  field("diagnostic", "string", [])
  field("event_name", "string", [])

  finish()
end
