# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.FBImageCopyrightMatch do
  use MetaAds.Model

  field("added_to_dashboard_time", "datetime", [])
  field("applied_actions", "list<map<string, Object>>", [])
  field("audit_log", "list<Object>", [])
  field("available_ui_actions", "list<string>", [])
  field("expiration_days", "int", [])
  field("generic_match_data", "list<Object>", [])
  field("id", "string", [])
  field("is_business_page_match", "bool", [])
  field("last_modified_time", "datetime", [])
  field("match_data", "list<Object>", [])
  field("match_status", "string", [])
  field("ownership_countries", "VideoCopyrightGeoGate", [])
  field("reference_owner", "Profile", [])
  field("time_to_appeal", "int", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
