# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.FranchiseProgram do
  use MetaAds.Model

  field("business_asset_group", "BusinessAssetGroup", [])
  field("creator_business", "Business", [])
  field("description", "string", [])
  field("end_date", "datetime", [])
  field("id", "string", [])
  field("name", "string", [])
  field("program_access_type", "string", [])
  field("program_approval_type", "string", [])
  field("program_image_link", "string", [])
  field("program_url", "string", [])
  field("shared_custom_audience", "CustomAudience", [])
  field("start_date", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
