# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.FranchiseProgramMember do
  use MetaAds.Model

  field("business", "Business", [])
  field("end_date", "datetime", [])
  field("id", "string", [])
  field("join_date", "datetime", [])
  field("member_ad_account", "AdAccount", [])
  field("member_user", "User", [])
  field("membership_status", "string", [])
  field("page", "Page", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
