# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.FundingSourceDetailsCouponTiering do
  use MetaAds.Model

  field("coupon_tiering_new", "Object", [])
  field("coupon_tiering_reactivation", "Object", [])

  finish()
end
