# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.GeoGatingPolicy do
  use MetaAds.Model

  field("after_schedule", "string", [])
  field("exclude_country", "list<string>", [])
  field("id", "string", [])
  field("include_country", "list<string>", [])
  field("name", "string", [])
  field("valid_from", "datetime", [])
  field("valid_until", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
