# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Group do
  use MetaAds.Model

  field("archived", "bool", [])
  field("cover", "CoverPhoto", [])
  field("created_time", "datetime", [])
  field("description", "string", [])
  field("email", "string", [])
  field("icon", "string", [])
  field("id", "string", [])
  field("install", "Object", [])
  field("link", "string", [])
  field("member_count", "unsigned int", [])
  field("member_request_count", "unsigned int", [])
  field("name", "string", [])
  field("parent", "Object", [])
  field("permissions", "list<string>", [])
  field("privacy", "string", [])
  field("purpose", "string", [])
  field("subdomain", "string", [])
  field("updated_time", "datetime", [])
  field("venue", "Location", [])

  operation(:delete_admins, "DELETE", "admins", nil, [
    %{"name" => "uid", "required" => true, "type" => "int"}
  ])

  operation(:create_admins, "POST", "admins", nil, [
    %{"name" => "uid", "required" => true, "type" => "int"}
  ])

  operation(:get_albums, "GET", "albums", nil, [])
  operation(:get_docs, "GET", "docs", nil, [])
  operation(:get_events, "GET", "events", nil, [])

  operation(:get_feed, "GET", "feed", nil, [
    %{"name" => "include_hidden", "required" => false, "type" => "bool"},
    %{"name" => "q", "required" => false, "type" => "string"},
    %{"name" => "show_expired", "required" => false, "type" => "bool"},
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{"name" => "until", "required" => false, "type" => "datetime"},
    %{"name" => "with", "required" => false, "type" => "string"}
  ])

  operation(:create_feed, "POST", "feed", nil, [
    %{"name" => "actions", "required" => false, "type" => "Object"},
    %{"name" => "album_id", "required" => false, "type" => "string"},
    %{"name" => "android_key_hash", "required" => false, "type" => "string"},
    %{"name" => "application_id", "required" => false, "type" => "string"},
    %{"name" => "asked_fun_fact_prompt_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "asset3d_id", "required" => false, "type" => "string"},
    %{"name" => "associated_id", "required" => false, "type" => "string"},
    %{"name" => "attach_place_suggestion", "required" => false, "type" => "bool"},
    %{"name" => "attached_media", "required" => false, "type" => "list<Object>"},
    %{"name" => "audience_exp", "required" => false, "type" => "bool"},
    %{"name" => "backdated_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "backdated_time_granularity",
      "required" => false,
      "type" => "groupfeed_backdated_time_granularity_enum_param",
      "values" => ["day", "hour", "min", "month", "none", "year"]
    },
    %{"name" => "breaking_news", "required" => false, "type" => "bool"},
    %{"name" => "breaking_news_expiration", "required" => false, "type" => "unsigned int"},
    %{"name" => "call_to_action", "required" => false, "type" => "Object"},
    %{"name" => "caption", "required" => false, "type" => "string"},
    %{"name" => "child_attachments", "required" => false, "type" => "list<Object>"},
    %{"name" => "client_mutation_id", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_picker", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_point", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_time", "required" => false, "type" => "unsigned int"},
    %{"name" => "composer_session_events_log", "required" => false, "type" => "string"},
    %{"name" => "composer_session_id", "required" => false, "type" => "string"},
    %{"name" => "composer_source_surface", "required" => false, "type" => "string"},
    %{"name" => "composer_type", "required" => false, "type" => "string"},
    %{"name" => "connection_class", "required" => false, "type" => "string"},
    %{"name" => "content_attachment", "required" => false, "type" => "string"},
    %{"name" => "coordinates", "required" => false, "type" => "Object"},
    %{"name" => "cta_link", "required" => false, "type" => "string"},
    %{"name" => "cta_type", "required" => false, "type" => "string"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "direct_share_status", "required" => false, "type" => "unsigned int"},
    %{"name" => "expanded_height", "required" => false, "type" => "unsigned int"},
    %{"name" => "expanded_width", "required" => false, "type" => "unsigned int"},
    %{"name" => "feed_targeting", "required" => false, "type" => "Object"},
    %{
      "name" => "formatting",
      "required" => false,
      "type" => "groupfeed_formatting_enum_param",
      "values" => ["MARKDOWN", "PLAINTEXT"]
    },
    %{"name" => "fun_fact_prompt_id", "required" => false, "type" => "string"},
    %{"name" => "fun_fact_toastee_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "height", "required" => false, "type" => "unsigned int"},
    %{"name" => "home_checkin_city_id", "required" => false, "type" => "Object"},
    %{"name" => "image_crops", "required" => false, "type" => "map"},
    %{"name" => "implicit_with_tags", "required" => false, "type" => "list<int>"},
    %{"name" => "instant_game_entry_point_data", "required" => false, "type" => "string"},
    %{"name" => "ios_bundle_id", "required" => false, "type" => "string"},
    %{"name" => "is_backout_draft", "required" => false, "type" => "bool"},
    %{"name" => "is_boost_intended", "required" => false, "type" => "bool"},
    %{"name" => "is_explicit_location", "required" => false, "type" => "bool"},
    %{"name" => "is_explicit_share", "required" => false, "type" => "bool"},
    %{"name" => "is_group_linking_post", "required" => false, "type" => "bool"},
    %{"name" => "is_photo_container", "required" => false, "type" => "bool"},
    %{"name" => "link", "required" => false, "type" => "string"},
    %{"name" => "location_source_id", "required" => false, "type" => "string"},
    %{"name" => "manual_privacy", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "multi_share_end_card", "required" => false, "type" => "bool"},
    %{"name" => "multi_share_optimized", "required" => false, "type" => "bool"},
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "object_attachment", "required" => false, "type" => "string"},
    %{"name" => "og_action_type_id", "required" => false, "type" => "string"},
    %{"name" => "og_hide_object_attachment", "required" => false, "type" => "bool"},
    %{"name" => "og_icon_id", "required" => false, "type" => "string"},
    %{"name" => "og_object_id", "required" => false, "type" => "string"},
    %{"name" => "og_phrase", "required" => false, "type" => "string"},
    %{"name" => "og_set_profile_badge", "required" => false, "type" => "bool"},
    %{"name" => "og_suggestion_mechanism", "required" => false, "type" => "string"},
    %{"name" => "page_recommendation", "required" => false, "type" => "string"},
    %{"name" => "picture", "required" => false, "type" => "string"},
    %{"name" => "place", "required" => false, "type" => "Object"},
    %{
      "name" => "place_attachment_setting",
      "required" => false,
      "type" => "groupfeed_place_attachment_setting_enum_param",
      "values" => ["1", "2"]
    },
    %{"name" => "place_list", "required" => false, "type" => "string"},
    %{"name" => "place_list_data", "required" => false, "type" => "list"},
    %{
      "name" => "post_surfaces_blacklist",
      "required" => false,
      "type" => "list<groupfeed_post_surfaces_blacklist_enum_param>",
      "values" => ["1", "2", "3", "4", "5"]
    },
    %{
      "name" => "posting_to_redspace",
      "required" => false,
      "type" => "groupfeed_posting_to_redspace_enum_param",
      "values" => ["disabled", "enabled"]
    },
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{"name" => "prompt_id", "required" => false, "type" => "string"},
    %{"name" => "prompt_tracking_string", "required" => false, "type" => "string"},
    %{"name" => "properties", "required" => false, "type" => "Object"},
    %{"name" => "proxied_app_id", "required" => false, "type" => "string"},
    %{"name" => "publish_event_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "quote", "required" => false, "type" => "string"},
    %{"name" => "ref", "required" => false, "type" => "list<string>"},
    %{"name" => "referenceable_image_ids", "required" => false, "type" => "list<string>"},
    %{"name" => "referral_id", "required" => false, "type" => "string"},
    %{"name" => "scheduled_publish_time", "required" => false, "type" => "datetime"},
    %{"name" => "source", "required" => false, "type" => "string"},
    %{"name" => "sponsor_id", "required" => false, "type" => "string"},
    %{"name" => "sponsor_relationship", "required" => false, "type" => "unsigned int"},
    %{"name" => "suggested_place_id", "required" => false, "type" => "Object"},
    %{"name" => "tags", "required" => false, "type" => "list<int>"},
    %{
      "name" => "target_surface",
      "required" => false,
      "type" => "groupfeed_target_surface_enum_param",
      "values" => ["STORY", "TIMELINE"]
    },
    %{"name" => "targeting", "required" => false, "type" => "Object"},
    %{"name" => "text_format_metadata", "required" => false, "type" => "string"},
    %{"name" => "text_format_preset_id", "required" => false, "type" => "string"},
    %{"name" => "text_only_place", "required" => false, "type" => "string"},
    %{"name" => "thumbnail", "required" => false, "type" => "file"},
    %{"name" => "time_since_original_post", "required" => false, "type" => "unsigned int"},
    %{"name" => "title", "required" => false, "type" => "string"},
    %{"name" => "tracking_info", "required" => false, "type" => "string"},
    %{
      "name" => "unpublished_content_type",
      "required" => false,
      "type" => "groupfeed_unpublished_content_type_enum_param",
      "values" => [
        "ADS_POST",
        "DRAFT",
        "INLINE_CREATED",
        "PUBLISHED",
        "PUBLISH_PENDING",
        "REVIEWABLE_BRANDED_CONTENT",
        "SCHEDULED",
        "SCHEDULED_RECURRING"
      ]
    },
    %{"name" => "user_selected_tags", "required" => false, "type" => "bool"},
    %{"name" => "video_start_time_ms", "required" => false, "type" => "unsigned int"},
    %{"name" => "viewer_coordinates", "required" => false, "type" => "Object"},
    %{"name" => "width", "required" => false, "type" => "unsigned int"}
  ])

  operation(:get_files, "GET", "files", nil, [])
  operation(:get_groups, "GET", "groups", nil, [])

  operation(:create_groups, "POST", "groups", nil, [
    %{"name" => "admin", "required" => false, "type" => "int"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "group_icon_id", "required" => false, "type" => "string"},
    %{
      "name" => "group_type",
      "required" => false,
      "type" => "groupgroups_group_type_enum_param",
      "values" => [
        "CASUAL",
        "COWORKERS",
        "CUSTOM",
        "FOR_SALE",
        "FOR_WORK",
        "GAME",
        "HEALTH_SUPPORT",
        "JOBS",
        "LEARNING",
        "NONE",
        "PARENTING",
        "STREAMER",
        "WORK_AGENT_TO_AGENT",
        "WORK_ANNOUNCEMENT",
        "WORK_DEMO_GROUP",
        "WORK_DISCUSSION",
        "WORK_EPHEMERAL",
        "WORK_FEEDBACK",
        "WORK_FOR_SALE",
        "WORK_GARDEN",
        "WORK_INTEGRITY",
        "WORK_LEARNING",
        "WORK_MENTORSHIP",
        "WORK_MULTI_COMPANY",
        "WORK_RECRUITING",
        "WORK_SOCIAL",
        "WORK_STAGES",
        "WORK_TEAM",
        "WORK_TEAMWORK"
      ]
    },
    %{
      "name" => "join_setting",
      "required" => false,
      "type" => "groupgroups_join_setting_enum_param",
      "values" => ["ADMIN_ONLY", "ANYONE", "NONE"]
    },
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "parent_id", "required" => false, "type" => "string"},
    %{
      "name" => "post_permissions",
      "required" => false,
      "type" => "groupgroups_post_permissions_enum_param",
      "values" => ["ADMIN_ONLY", "ANYONE", "NONE"]
    },
    %{"name" => "post_requires_admin_approval", "required" => false, "type" => "bool"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{"name" => "ref", "required" => false, "type" => "string"}
  ])

  operation(:get_live_videos, "GET", "live_videos", nil, [
    %{
      "name" => "broadcast_status",
      "required" => false,
      "type" => "list<grouplive_videos_broadcast_status_enum_param>",
      "values" => [
        "LIVE",
        "LIVE_STOPPED",
        "PROCESSING",
        "SCHEDULED_CANCELED",
        "SCHEDULED_EXPIRED",
        "SCHEDULED_LIVE",
        "SCHEDULED_UNPUBLISHED",
        "UNPUBLISHED",
        "VOD"
      ]
    },
    %{
      "name" => "source",
      "required" => false,
      "type" => "grouplive_videos_source_enum_param",
      "values" => ["owner", "target"]
    }
  ])

  operation(:create_live_videos, "POST", "live_videos", nil, [
    %{"name" => "content_tags", "required" => false, "type" => "list<string>"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "enable_backup_ingest", "required" => false, "type" => "bool"},
    %{"name" => "encoding_settings", "required" => false, "type" => "string"},
    %{"name" => "event_params", "required" => false, "type" => "Object"},
    %{"name" => "fisheye_video_cropped", "required" => false, "type" => "bool"},
    %{"name" => "front_z_rotation", "required" => false, "type" => "float"},
    %{"name" => "is_audio_only", "required" => false, "type" => "bool"},
    %{"name" => "is_spherical", "required" => false, "type" => "bool"},
    %{"name" => "original_fov", "required" => false, "type" => "unsigned int"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{
      "name" => "projection",
      "required" => false,
      "type" => "grouplive_videos_projection_enum_param",
      "values" => ["CUBEMAP", "EQUIRECTANGULAR", "HALF_EQUIRECTANGULAR"]
    },
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "schedule_custom_profile_image", "required" => false, "type" => "file"},
    %{
      "name" => "spatial_audio_format",
      "required" => false,
      "type" => "grouplive_videos_spatial_audio_format_enum_param",
      "values" => ["ambiX_4"]
    },
    %{
      "name" => "status",
      "required" => false,
      "type" => "grouplive_videos_status_enum_param",
      "values" => [
        "LIVE_NOW",
        "SCHEDULED_CANCELED",
        "SCHEDULED_LIVE",
        "SCHEDULED_UNPUBLISHED",
        "UNPUBLISHED"
      ]
    },
    %{
      "name" => "stereoscopic_mode",
      "required" => false,
      "type" => "grouplive_videos_stereoscopic_mode_enum_param",
      "values" => ["LEFT_RIGHT", "MONO", "MULTI_VIEW", "TOP_BOTTOM"]
    },
    %{"name" => "stop_on_delete_stream", "required" => false, "type" => "bool"},
    %{
      "name" => "stream_type",
      "required" => false,
      "type" => "grouplive_videos_stream_type_enum_param",
      "values" => ["AMBIENT", "REGULAR"]
    },
    %{"name" => "title", "required" => false, "type" => "string"}
  ])

  operation(:delete_members, "DELETE", "members", nil, [
    %{"name" => "email", "required" => false, "type" => "string"},
    %{"name" => "member", "required" => false, "type" => "int"}
  ])

  operation(:create_members, "POST", "members", nil, [
    %{"name" => "email", "required" => false, "type" => "string"},
    %{"name" => "from", "required" => false, "type" => "int"},
    %{"name" => "member", "required" => false, "type" => "int"},
    %{"name" => "rate", "required" => false, "type" => "unsigned int"},
    %{"name" => "source", "required" => false, "type" => "string"}
  ])

  operation(:get_opted_in_members, "GET", "opted_in_members", nil, [])

  operation(:create_photos, "POST", "photos", nil, [
    %{"name" => "aid", "required" => false, "type" => "string"},
    %{"name" => "allow_spherical_photo", "required" => false, "type" => "bool"},
    %{"name" => "alt_text_custom", "required" => false, "type" => "string"},
    %{"name" => "android_key_hash", "required" => false, "type" => "string"},
    %{"name" => "application_id", "required" => false, "type" => "string"},
    %{"name" => "attempt", "required" => false, "type" => "unsigned int"},
    %{"name" => "audience_exp", "required" => false, "type" => "bool"},
    %{"name" => "backdated_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "backdated_time_granularity",
      "required" => false,
      "type" => "groupphotos_backdated_time_granularity_enum_param",
      "values" => ["day", "hour", "min", "month", "none", "year"]
    },
    %{"name" => "caption", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_point", "required" => false, "type" => "string"},
    %{"name" => "composer_session_id", "required" => false, "type" => "string"},
    %{"name" => "direct_share_status", "required" => false, "type" => "unsigned int"},
    %{"name" => "feed_targeting", "required" => false, "type" => "Object"},
    %{"name" => "filter_type", "required" => false, "type" => "unsigned int"},
    %{"name" => "full_res_is_coming_later", "required" => false, "type" => "bool"},
    %{
      "name" => "initial_view_heading_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "initial_view_pitch_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "initial_view_vertical_fov_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{"name" => "ios_bundle_id", "required" => false, "type" => "string"},
    %{"name" => "is_explicit_location", "required" => false, "type" => "bool"},
    %{"name" => "is_explicit_place", "required" => false, "type" => "bool"},
    %{"name" => "manual_privacy", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "no_story", "required" => false, "type" => "bool"},
    %{"name" => "offline_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "og_action_type_id", "required" => false, "type" => "string"},
    %{"name" => "og_icon_id", "required" => false, "type" => "string"},
    %{"name" => "og_object_id", "required" => false, "type" => "string"},
    %{"name" => "og_phrase", "required" => false, "type" => "string"},
    %{"name" => "og_set_profile_badge", "required" => false, "type" => "bool"},
    %{"name" => "og_suggestion_mechanism", "required" => false, "type" => "string"},
    %{"name" => "place", "required" => false, "type" => "Object"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{"name" => "profile_id", "required" => false, "type" => "int"},
    %{"name" => "provenance_info", "required" => false, "type" => "map"},
    %{"name" => "provenance_metadata", "required" => false, "type" => "map"},
    %{"name" => "proxied_app_id", "required" => false, "type" => "string"},
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "qn", "required" => false, "type" => "string"},
    %{"name" => "spherical_metadata", "required" => false, "type" => "map"},
    %{"name" => "sponsor_id", "required" => false, "type" => "string"},
    %{"name" => "sponsor_relationship", "required" => false, "type" => "unsigned int"},
    %{"name" => "tags", "required" => false, "type" => "list<Object>"},
    %{"name" => "target_id", "required" => false, "type" => "int"},
    %{"name" => "targeting", "required" => false, "type" => "Object"},
    %{"name" => "time_since_original_post", "required" => false, "type" => "unsigned int"},
    %{"name" => "uid", "required" => false, "type" => "int"},
    %{
      "name" => "unpublished_content_type",
      "required" => false,
      "type" => "groupphotos_unpublished_content_type_enum_param",
      "values" => [
        "ADS_POST",
        "DRAFT",
        "INLINE_CREATED",
        "PUBLISHED",
        "PUBLISH_PENDING",
        "REVIEWABLE_BRANDED_CONTENT",
        "SCHEDULED",
        "SCHEDULED_RECURRING"
      ]
    },
    %{"name" => "url", "required" => false, "type" => "string"},
    %{"name" => "user_selected_tags", "required" => false, "type" => "bool"},
    %{"name" => "vault_image_id", "required" => false, "type" => "string"}
  ])

  operation(:get_picture, "GET", "picture", nil, [
    %{"name" => "height", "required" => false, "type" => "int"},
    %{"name" => "redirect", "required" => false, "type" => "bool"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "grouppicture_type_enum_param",
      "values" => ["album", "large", "normal", "small", "square"]
    },
    %{"name" => "width", "required" => false, "type" => "int"}
  ])

  operation(:get_videos, "GET", "videos", nil, [
    %{
      "name" => "type",
      "required" => false,
      "type" => "groupvideos_type_enum_param",
      "values" => ["tagged", "uploaded"]
    }
  ])

  operation(:create_videos, "POST", "videos", nil, [
    %{"name" => "application_id", "required" => false, "type" => "string"},
    %{"name" => "asked_fun_fact_prompt_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "audio_story_wave_animation_handle", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_picker", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_point", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_time", "required" => false, "type" => "unsigned int"},
    %{"name" => "composer_session_events_log", "required" => false, "type" => "string"},
    %{"name" => "composer_session_id", "required" => false, "type" => "string"},
    %{"name" => "composer_source_surface", "required" => false, "type" => "string"},
    %{"name" => "composer_type", "required" => false, "type" => "string"},
    %{
      "name" => "container_type",
      "required" => false,
      "type" => "groupvideos_container_type_enum_param",
      "values" => [
        "ACO_VIDEO_VARIATION",
        "ADS_AI_GENERATED",
        "AD_BREAK_PREVIEW",
        "AD_DERIVATIVE",
        "AD_LIBRARY_WATERMARK",
        "AI_INTERACTIVE_EMBODIMENT",
        "ALBUM_MULTIMEDIA_POST",
        "ALOHA_SUPERFRAME",
        "APP_REREVIEW_SCREENCAST",
        "APP_REVIEW_SCREENCAST",
        "ASSET_MANAGER",
        "ATLAS_VIDEO",
        "AUDIO_BROADCAST",
        "AUDIO_COMMENT",
        "BROADCAST",
        "CANVAS",
        "CMS_MEDIA_MANAGER",
        "CONTAINED_POST_ATTACHMENT",
        "CONTAINED_POST_AUDIO_BROADCAST",
        "CONTAINED_POST_COPYRIGHT_REFERENCE_BROADCAST",
        "COPYRIGHT_REFERENCE_BROADCAST",
        "COPYRIGHT_REFERENCE_IG_XPOST_VIDEO",
        "COPYRIGHT_REFERENCE_VIDEO",
        "CREATION_ML_PRECREATION",
        "CREATOR_FAN_CHALLENGE",
        "CREATOR_STOREFRONT_PERSONALIZED_VIDEO",
        "CREATOR_STOREFRONT_PROMOTIONAL_VIDEO",
        "DATAGENIX_VIDEO",
        "DCO_AD_ASSET_FEED",
        "DCO_AUTOGEN_VIDEO",
        "DCO_TRIMMED_VIDEO",
        "DIM_SUM",
        "DIRECTED_POST_ATTACHMENT",
        "DIRECT_INBOX",
        "DOUBLE_PROD_EXPERIMENT",
        "DROPS_SHOPPING_EVENT_PAGE",
        "DYNAMIC_ITEM_VIDEO",
        "DYNAMIC_TEMPLATE_VIDEO",
        "EVENT_COVER_VIDEO",
        "EVENT_TOUR",
        "FACECAST_DVR",
        "FB_AVATAR_ANIMATED_SATP",
        "FB_COLLECTIBLE_VIDEO",
        "FB_MSGR_STATUS_MEDIA_ELEMENT",
        "FB_QUICKSNAP_VIDEO",
        "FB_SHORTS",
        "FB_SHORTS_CONTENT_REMIXABLE",
        "FB_SHORTS_GROUP_POST",
        "FB_SHORTS_LINKED_PRODUCT",
        "FB_SHORTS_PMV_POST",
        "FB_SHORTS_POST",
        "FB_SHORTS_REMIX_POST",
        "FUNDRAISER_COVER_VIDEO",
        "GAME_CLIP",
        "GIF_TO_VIDEO",
        "GOODWILL_ANNIVERSARY_DEPRECATED",
        "GOODWILL_ANNIVERSARY_PROMOTION_DEPRECATED",
        "GOODWILL_VIDEO_CONTAINED_SHARE",
        "GOODWILL_VIDEO_PROMOTION",
        "GOODWILL_VIDEO_SHARE",
        "GOODWILL_VIDEO_TOKEN_REQUIRED",
        "GROUP_POST",
        "HEURISTIC_CLUSTER_VIDEO",
        "HIGHLIGHT_CLIP_VIDEO",
        "HORIZON_WORLDS_TV",
        "HUDDLE_BROADCAST",
        "IG_REELS_XPV",
        "INSPIRATION_VIDEO",
        "INSTAGRAM_VIDEO_COPY",
        "INSTANT_APPLICATION_PREVIEW",
        "INSTANT_ARTICLE",
        "ISSUE_MODULE",
        "LEARN",
        "LEGACY",
        "LEGACY_CONTAINED_POST_BROADCAST",
        "LIVE_AUDIO_ROOM_BROADCAST",
        "LIVE_CLIP_PREVIEW",
        "LIVE_CLIP_WORKCHAT",
        "LIVE_CREATIVE_KIT_VIDEO",
        "LIVE_PHOTO",
        "LOOK_NOW_DEPRECATED",
        "MARKETPLACE_LISTING_VIDEO",
        "MARKETPLACE_PRE_RECORDED_VIDEO",
        "MOMENTS_VIDEO",
        "MUSIC_CLIP",
        "MUSIC_CLIP_IN_COMMENT",
        "MUSIC_CLIP_IN_FB_MSGR_STATUS",
        "MUSIC_CLIP_IN_LIGHTWEIGHT_STATUS",
        "MUSIC_CLIP_IN_MAPLE_POST",
        "MUSIC_CLIP_IN_MSGR_NOTE",
        "MUSIC_CLIP_IN_POLL_OPTION",
        "MUSIC_CLIP_ON_DATING_PROFILE",
        "NEO_ASYNC_GAME_VIDEO",
        "NEW_CONTAINED_POST_BROADCAST",
        "NO_STORY",
        "OCULUS_CREATOR_PORTAL",
        "OCULUS_VENUES_BROADCAST",
        "ORIGINALITY_SELF_ADVOCACY",
        "PAGES_COVER_VIDEO",
        "PAGE_REVIEW_SCREENCAST",
        "PAGE_SLIDESHOW_VIDEO",
        "PAID_CONTENT_PREVIEW",
        "PAID_CONTENT_VIDEO",
        "PAID_CONTENT_VIDEO__POST",
        "PIXELCLOUD",
        "PODCAST_HIGHLIGHT",
        "PODCAST_ML_PREVIEW_NO_NEWSFEED_STORY",
        "PODCAST_RSS",
        "PODCAST_RSS_EPHEMERAL",
        "PODCAST_RSS_NO_NEWSFEED_STORY",
        "PODCAST_VOICES",
        "PODCAST_VOICES_NO_NEWSFEED_STORY",
        "PREMIERE_SOURCE",
        "PREMIUM_MUSIC_VIDEO_CLIP",
        "PREMIUM_MUSIC_VIDEO_CROPPED_CLIP",
        "PREMIUM_MUSIC_VIDEO_NO_NEWSFEED_STORY",
        "PREMIUM_MUSIC_VIDEO_WITH_NEWSFEED_STORY",
        "PRIVATE_GALLERY_VIDEO",
        "PRODUCT_VIDEO",
        "PROFILE_COVER_VIDEO",
        "PROFILE_INTRO_CARD",
        "PROFILE_VIDEO",
        "QUICK_CLIP_WORKPLACE_POST",
        "QUICK_PROMOTION",
        "SHOWREEL_NATIVE_DUMMY_VIDEO",
        "SLIDESHOW_ANIMOTO",
        "SLIDESHOW_SHAKR",
        "SLIDESHOW_VARIATION_VIDEO",
        "SOUND_PLATFORM_STREAM",
        "SRT_ATTACHMENT",
        "STORIES_VIDEO",
        "STORYLINE",
        "STORYLINE_WITH_EXTERNAL_MUSIC",
        "STORY_ARCHIVE_VIDEO",
        "STORY_CARD_TEMPLATE",
        "STREAM_HIGHLIGHTS_VIDEO",
        "TAROT_DIGEST",
        "TEMPORARY",
        "TEMPORARY_UNLISTED",
        "TEMP_VIDEO_COPYRIGHT_SCAN",
        "UNLISTED",
        "UNLISTED_OCULUS",
        "VIDEO_COMMENT",
        "VIDEO_COMPOSITION_VARIATION",
        "VIDEO_CREATIVE_EDITOR_AUTOGEN_AD_VIDEO",
        "VIDEO_SUPERRES",
        "VU_GENERATED_VIDEO",
        "WOODHENGE",
        "WORK_KNOWLEDGE_VIDEO",
        "YOUR_DAY"
      ]
    },
    %{
      "name" => "content_category",
      "required" => false,
      "type" => "groupvideos_content_category_enum_param",
      "values" => [
        "BEAUTY_FASHION",
        "BUSINESS",
        "CARS_TRUCKS",
        "COMEDY",
        "CUTE_ANIMALS",
        "ENTERTAINMENT",
        "FAMILY",
        "FOOD_HEALTH",
        "HOME",
        "LIFESTYLE",
        "MUSIC",
        "NEWS",
        "OTHER",
        "POLITICS",
        "SCIENCE",
        "SPORTS",
        "TECHNOLOGY",
        "VIDEO_GAMING"
      ]
    },
    %{"name" => "creative_tools", "required" => false, "type" => "string"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "edit_description_spec", "required" => false, "type" => "map"},
    %{"name" => "embeddable", "required" => false, "type" => "bool"},
    %{"name" => "end_offset", "required" => false, "type" => "unsigned int"},
    %{"name" => "fbuploader_video_file_chunk", "required" => false, "type" => "string"},
    %{"name" => "file_size", "required" => false, "type" => "unsigned int"},
    %{"name" => "file_url", "required" => false, "type" => "string"},
    %{"name" => "fisheye_video_cropped", "required" => false, "type" => "bool"},
    %{
      "name" => "formatting",
      "required" => false,
      "type" => "groupvideos_formatting_enum_param",
      "values" => ["MARKDOWN", "PLAINTEXT"]
    },
    %{"name" => "fov", "required" => false, "type" => "unsigned int"},
    %{"name" => "front_z_rotation", "required" => false, "type" => "float"},
    %{"name" => "fun_fact_prompt_id", "required" => false, "type" => "string"},
    %{"name" => "fun_fact_toastee_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "guide", "required" => false, "type" => "list<list<unsigned int>>"},
    %{"name" => "guide_enabled", "required" => false, "type" => "bool"},
    %{"name" => "initial_heading", "required" => false, "type" => "unsigned int"},
    %{"name" => "initial_pitch", "required" => false, "type" => "unsigned int"},
    %{"name" => "instant_game_entry_point_data", "required" => false, "type" => "string"},
    %{"name" => "is_ai_generated", "required" => false, "type" => "bool"},
    %{"name" => "is_boost_intended", "required" => false, "type" => "bool"},
    %{"name" => "is_explicit_share", "required" => false, "type" => "bool"},
    %{"name" => "is_group_linking_post", "required" => false, "type" => "bool"},
    %{"name" => "is_partnership_ad", "required" => false, "type" => "bool"},
    %{"name" => "is_voice_clip", "required" => false, "type" => "bool"},
    %{"name" => "location_source_id", "required" => false, "type" => "string"},
    %{"name" => "manual_privacy", "required" => false, "type" => "bool"},
    %{"name" => "og_action_type_id", "required" => false, "type" => "string"},
    %{"name" => "og_icon_id", "required" => false, "type" => "string"},
    %{"name" => "og_object_id", "required" => false, "type" => "string"},
    %{"name" => "og_phrase", "required" => false, "type" => "string"},
    %{"name" => "og_suggestion_mechanism", "required" => false, "type" => "string"},
    %{"name" => "original_fov", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "original_projection_type",
      "required" => false,
      "type" => "groupvideos_original_projection_type_enum_param",
      "values" => ["cubemap", "equirectangular", "half_equirectangular"]
    },
    %{"name" => "partnership_ad_ad_code", "required" => false, "type" => "string"},
    %{"name" => "publish_event_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "referenced_sticker_id", "required" => false, "type" => "string"},
    %{"name" => "replace_video_id", "required" => false, "type" => "string"},
    %{"name" => "scheduled_publish_time", "required" => false, "type" => "unsigned int"},
    %{"name" => "selected_audio_spec", "required" => false, "type" => "map"},
    %{"name" => "slideshow_spec", "required" => false, "type" => "map"},
    %{"name" => "source", "required" => false, "type" => "string"},
    %{"name" => "source_instagram_media_id", "required" => false, "type" => "string"},
    %{"name" => "spherical", "required" => false, "type" => "bool"},
    %{"name" => "start_offset", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "swap_mode",
      "required" => false,
      "type" => "groupvideos_swap_mode_enum_param",
      "values" => ["replace"]
    },
    %{"name" => "text_format_metadata", "required" => false, "type" => "string"},
    %{"name" => "thumb", "required" => false, "type" => "file"},
    %{"name" => "time_since_original_post", "required" => false, "type" => "unsigned int"},
    %{"name" => "title", "required" => false, "type" => "string"},
    %{"name" => "transcode_setting_properties", "required" => false, "type" => "string"},
    %{
      "name" => "unpublished_content_type",
      "required" => false,
      "type" => "groupvideos_unpublished_content_type_enum_param",
      "values" => [
        "ADS_POST",
        "DRAFT",
        "INLINE_CREATED",
        "PUBLISHED",
        "PUBLISH_PENDING",
        "REVIEWABLE_BRANDED_CONTENT",
        "SCHEDULED",
        "SCHEDULED_RECURRING"
      ]
    },
    %{
      "name" => "upload_phase",
      "required" => false,
      "type" => "groupvideos_upload_phase_enum_param",
      "values" => ["cancel", "finish", "start", "transfer"]
    },
    %{"name" => "upload_session_id", "required" => false, "type" => "string"},
    %{"name" => "upload_setting_properties", "required" => false, "type" => "string"},
    %{"name" => "video_file_chunk", "required" => false, "type" => "string"},
    %{"name" => "video_id_original", "required" => false, "type" => "string"},
    %{"name" => "video_start_time_ms", "required" => false, "type" => "unsigned int"},
    %{"name" => "waterfall_id", "required" => false, "type" => "string"}
  ])

  operation(:get, "GET", "", nil, [
    %{
      "name" => "icon_size",
      "required" => false,
      "type" => "group_icon_size",
      "values" => ["16", "34", "50", "68"]
    }
  ])

  operation(:create, "POST", "", nil, [
    %{"name" => "cover", "required" => false, "type" => "string"},
    %{"name" => "cover_url", "required" => false, "type" => "string"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "focus_x", "required" => false, "type" => "float"},
    %{"name" => "focus_y", "required" => false, "type" => "float"},
    %{"name" => "group_icon", "required" => false, "type" => "string"},
    %{"name" => "is_official_group", "required" => false, "type" => "bool"},
    %{
      "name" => "join_setting",
      "required" => false,
      "type" => "group_join_setting",
      "values" => ["ADMIN_ONLY", "ANYONE", "NONE"]
    },
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "no_feed_story", "required" => false, "type" => "bool"},
    %{"name" => "offset_y", "required" => false, "type" => "int"},
    %{
      "name" => "post_permissions",
      "required" => false,
      "type" => "group_post_permissions",
      "values" => ["ADMIN_ONLY", "ANYONE", "NONE"]
    },
    %{"name" => "post_requires_admin_approval", "required" => false, "type" => "bool"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{
      "name" => "purpose",
      "required" => false,
      "type" => "group_purpose",
      "values" => [
        "CASUAL",
        "COWORKERS",
        "CUSTOM",
        "FOR_SALE",
        "FOR_WORK",
        "GAME",
        "HEALTH_SUPPORT",
        "JOBS",
        "LEARNING",
        "NONE",
        "PARENTING",
        "STREAMER",
        "WORK_AGENT_TO_AGENT",
        "WORK_ANNOUNCEMENT",
        "WORK_DEMO_GROUP",
        "WORK_DISCUSSION",
        "WORK_EPHEMERAL",
        "WORK_FEEDBACK",
        "WORK_FOR_SALE",
        "WORK_GARDEN",
        "WORK_INTEGRITY",
        "WORK_LEARNING",
        "WORK_MENTORSHIP",
        "WORK_MULTI_COMPANY",
        "WORK_RECRUITING",
        "WORK_SOCIAL",
        "WORK_STAGES",
        "WORK_TEAM",
        "WORK_TEAMWORK"
      ]
    },
    %{"name" => "update_view_time", "required" => false, "type" => "bool"}
  ])

  finish()
end
