# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Group do
  use MetaAds.Model

  field("archived", "bool", [])
  field("cover", "CoverPhoto", [])
  field("created_time", "datetime", [])
  field("description", "string", [])
  field("email", "string", [])
  field("icon", "string", [])
  field("id", "string", [])
  field("install", "Object", [])
  field("link", "string", [])
  field("member_count", "unsigned int", [])
  field("member_request_count", "unsigned int", [])
  field("name", "string", [])
  field("parent", "Object", [])
  field("permissions", "list<string>", [])
  field("privacy", "string", [])
  field("purpose", "string", [])
  field("subdomain", "string", [])
  field("updated_time", "datetime", [])
  field("venue", "Location", [])

  operation(:delete_admins, "DELETE", "admins", nil, [
    %{"name" => "uid", "required" => true, "type" => "int"}
  ])

  operation(:create_admins, "POST", "admins", nil, [
    %{"name" => "uid", "required" => true, "type" => "int"}
  ])

  operation(:get_albums, "GET", "albums", nil, [])
  operation(:get_docs, "GET", "docs", nil, [])
  operation(:get_events, "GET", "events", nil, [])

  operation(:get_feed, "GET", "feed", nil, [
    %{"name" => "include_hidden", "required" => false, "type" => "bool"},
    %{"name" => "q", "required" => false, "type" => "string"},
    %{"name" => "show_expired", "required" => false, "type" => "bool"},
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{"name" => "until", "required" => false, "type" => "datetime"},
    %{"name" => "with", "required" => false, "type" => "string"}
  ])

  operation(:get_files, "GET", "files", nil, [])
  operation(:get_groups, "GET", "groups", nil, [])

  operation(:create_groups, "POST", "groups", nil, [
    %{"name" => "admin", "required" => false, "type" => "int"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "group_icon_id", "required" => false, "type" => "string"},
    %{
      "name" => "group_type",
      "required" => false,
      "type" => "groupgroups_group_type_enum_param",
      "values" => [
        "CASUAL",
        "COWORKERS",
        "CUSTOM",
        "FOR_SALE",
        "FOR_WORK",
        "GAME",
        "HEALTH_SUPPORT",
        "JOBS",
        "LEARNING",
        "NONE",
        "PARENTING",
        "STREAMER",
        "WORK_AGENT_TO_AGENT",
        "WORK_ANNOUNCEMENT",
        "WORK_DEMO_GROUP",
        "WORK_DISCUSSION",
        "WORK_EPHEMERAL",
        "WORK_FEEDBACK",
        "WORK_FOR_SALE",
        "WORK_GARDEN",
        "WORK_INTEGRITY",
        "WORK_LEARNING",
        "WORK_MENTORSHIP",
        "WORK_MULTI_COMPANY",
        "WORK_RECRUITING",
        "WORK_SOCIAL",
        "WORK_STAGES",
        "WORK_TEAM",
        "WORK_TEAMWORK"
      ]
    },
    %{
      "name" => "join_setting",
      "required" => false,
      "type" => "groupgroups_join_setting_enum_param",
      "values" => ["ADMIN_ONLY", "ANYONE", "NONE"]
    },
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "parent_id", "required" => false, "type" => "string"},
    %{
      "name" => "post_permissions",
      "required" => false,
      "type" => "groupgroups_post_permissions_enum_param",
      "values" => ["ADMIN_ONLY", "ANYONE", "NONE"]
    },
    %{"name" => "post_requires_admin_approval", "required" => false, "type" => "bool"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{"name" => "ref", "required" => false, "type" => "string"}
  ])

  operation(:get_live_videos, "GET", "live_videos", nil, [
    %{
      "name" => "broadcast_status",
      "required" => false,
      "type" => "list<grouplive_videos_broadcast_status_enum_param>",
      "values" => [
        "LIVE",
        "LIVE_STOPPED",
        "PROCESSING",
        "SCHEDULED_CANCELED",
        "SCHEDULED_EXPIRED",
        "SCHEDULED_LIVE",
        "SCHEDULED_UNPUBLISHED",
        "UNPUBLISHED",
        "VOD"
      ]
    },
    %{
      "name" => "source",
      "required" => false,
      "type" => "grouplive_videos_source_enum_param",
      "values" => ["owner", "target"]
    }
  ])

  operation(:delete_members, "DELETE", "members", nil, [
    %{"name" => "email", "required" => false, "type" => "string"},
    %{"name" => "member", "required" => false, "type" => "int"}
  ])

  operation(:create_members, "POST", "members", nil, [
    %{"name" => "email", "required" => false, "type" => "string"},
    %{"name" => "from", "required" => false, "type" => "int"},
    %{"name" => "member", "required" => false, "type" => "int"},
    %{"name" => "rate", "required" => false, "type" => "unsigned int"},
    %{"name" => "source", "required" => false, "type" => "string"}
  ])

  operation(:get_opted_in_members, "GET", "opted_in_members", nil, [])

  operation(:create_photos, "POST", "photos", nil, [
    %{"name" => "aid", "required" => false, "type" => "string"},
    %{"name" => "allow_spherical_photo", "required" => false, "type" => "bool"},
    %{"name" => "alt_text_custom", "required" => false, "type" => "string"},
    %{"name" => "android_key_hash", "required" => false, "type" => "string"},
    %{"name" => "application_id", "required" => false, "type" => "string"},
    %{"name" => "attempt", "required" => false, "type" => "unsigned int"},
    %{"name" => "audience_exp", "required" => false, "type" => "bool"},
    %{"name" => "backdated_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "backdated_time_granularity",
      "required" => false,
      "type" => "groupphotos_backdated_time_granularity_enum_param",
      "values" => ["day", "hour", "min", "month", "none", "year"]
    },
    %{"name" => "caption", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_point", "required" => false, "type" => "string"},
    %{"name" => "composer_session_id", "required" => false, "type" => "string"},
    %{"name" => "direct_share_status", "required" => false, "type" => "unsigned int"},
    %{"name" => "feed_targeting", "required" => false, "type" => "Object"},
    %{"name" => "filter_type", "required" => false, "type" => "unsigned int"},
    %{"name" => "full_res_is_coming_later", "required" => false, "type" => "bool"},
    %{
      "name" => "initial_view_heading_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "initial_view_pitch_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "initial_view_vertical_fov_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{"name" => "ios_bundle_id", "required" => false, "type" => "string"},
    %{"name" => "is_explicit_location", "required" => false, "type" => "bool"},
    %{"name" => "is_explicit_place", "required" => false, "type" => "bool"},
    %{"name" => "manual_privacy", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "no_story", "required" => false, "type" => "bool"},
    %{"name" => "offline_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "og_action_type_id", "required" => false, "type" => "string"},
    %{"name" => "og_icon_id", "required" => false, "type" => "string"},
    %{"name" => "og_object_id", "required" => false, "type" => "string"},
    %{"name" => "og_phrase", "required" => false, "type" => "string"},
    %{"name" => "og_set_profile_badge", "required" => false, "type" => "bool"},
    %{"name" => "og_suggestion_mechanism", "required" => false, "type" => "string"},
    %{"name" => "place", "required" => false, "type" => "Object"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{"name" => "profile_id", "required" => false, "type" => "int"},
    %{"name" => "provenance_info", "required" => false, "type" => "map"},
    %{"name" => "provenance_metadata", "required" => false, "type" => "map"},
    %{"name" => "proxied_app_id", "required" => false, "type" => "string"},
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "qn", "required" => false, "type" => "string"},
    %{"name" => "spherical_metadata", "required" => false, "type" => "map"},
    %{"name" => "sponsor_id", "required" => false, "type" => "string"},
    %{"name" => "sponsor_relationship", "required" => false, "type" => "unsigned int"},
    %{"name" => "tags", "required" => false, "type" => "list<Object>"},
    %{"name" => "target_id", "required" => false, "type" => "int"},
    %{"name" => "targeting", "required" => false, "type" => "Object"},
    %{"name" => "time_since_original_post", "required" => false, "type" => "unsigned int"},
    %{"name" => "uid", "required" => false, "type" => "int"},
    %{
      "name" => "unpublished_content_type",
      "required" => false,
      "type" => "groupphotos_unpublished_content_type_enum_param",
      "values" => [
        "ADS_POST",
        "DRAFT",
        "INLINE_CREATED",
        "PUBLISHED",
        "PUBLISH_PENDING",
        "REVIEWABLE_BRANDED_CONTENT",
        "SCHEDULED",
        "SCHEDULED_RECURRING"
      ]
    },
    %{"name" => "url", "required" => false, "type" => "string"},
    %{"name" => "user_selected_tags", "required" => false, "type" => "bool"},
    %{"name" => "vault_image_id", "required" => false, "type" => "string"}
  ])

  operation(:get_picture, "GET", "picture", nil, [
    %{"name" => "height", "required" => false, "type" => "int"},
    %{"name" => "redirect", "required" => false, "type" => "bool"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "grouppicture_type_enum_param",
      "values" => ["album", "large", "normal", "small", "square"]
    },
    %{"name" => "width", "required" => false, "type" => "int"}
  ])

  operation(:get_videos, "GET", "videos", nil, [
    %{
      "name" => "type",
      "required" => false,
      "type" => "groupvideos_type_enum_param",
      "values" => ["tagged", "uploaded"]
    }
  ])

  operation(:get, "GET", "", nil, [
    %{
      "name" => "icon_size",
      "required" => false,
      "type" => "group_icon_size",
      "values" => ["16", "34", "50", "68"]
    }
  ])

  operation(:create, "POST", "", nil, [
    %{"name" => "cover", "required" => false, "type" => "string"},
    %{"name" => "cover_url", "required" => false, "type" => "string"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "focus_x", "required" => false, "type" => "float"},
    %{"name" => "focus_y", "required" => false, "type" => "float"},
    %{"name" => "group_icon", "required" => false, "type" => "string"},
    %{"name" => "is_official_group", "required" => false, "type" => "bool"},
    %{
      "name" => "join_setting",
      "required" => false,
      "type" => "group_join_setting",
      "values" => ["ADMIN_ONLY", "ANYONE", "NONE"]
    },
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "no_feed_story", "required" => false, "type" => "bool"},
    %{"name" => "offset_y", "required" => false, "type" => "int"},
    %{
      "name" => "post_permissions",
      "required" => false,
      "type" => "group_post_permissions",
      "values" => ["ADMIN_ONLY", "ANYONE", "NONE"]
    },
    %{"name" => "post_requires_admin_approval", "required" => false, "type" => "bool"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{
      "name" => "purpose",
      "required" => false,
      "type" => "group_purpose",
      "values" => [
        "CASUAL",
        "COWORKERS",
        "CUSTOM",
        "FOR_SALE",
        "FOR_WORK",
        "GAME",
        "HEALTH_SUPPORT",
        "JOBS",
        "LEARNING",
        "NONE",
        "PARENTING",
        "STREAMER",
        "WORK_AGENT_TO_AGENT",
        "WORK_ANNOUNCEMENT",
        "WORK_DEMO_GROUP",
        "WORK_DISCUSSION",
        "WORK_EPHEMERAL",
        "WORK_FEEDBACK",
        "WORK_FOR_SALE",
        "WORK_GARDEN",
        "WORK_INTEGRITY",
        "WORK_LEARNING",
        "WORK_MENTORSHIP",
        "WORK_MULTI_COMPANY",
        "WORK_RECRUITING",
        "WORK_SOCIAL",
        "WORK_STAGES",
        "WORK_TEAM",
        "WORK_TEAMWORK"
      ]
    },
    %{"name" => "update_view_time", "required" => false, "type" => "bool"}
  ])

  finish()
end
