# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.HighDemandPeriodTimeSuggestionWeeklySegment do
  use MetaAds.Model

  field("days", "list<string>", [])
  field("end_minute", "int", [])
  field("start_minute", "int", [])
  field("timezone_type", "string", [])

  finish()
end
