# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.HighDemandPeriodGet do
  use MetaAds.Model

  field("ad_object_id", "string", [])
  field("budget_value", "int", [])
  field("budget_value_type", "string", [])
  field("id", "string", [])
  field("recurrence_type", "string", [])
  field("time_end", "string", [])
  field("time_start", "string", [])
  field("weekly_schedule", "list<object>", [])

  finish()
end
