# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.HomeListingGet do
  use MetaAds.Model

  field("ac_type", "HomeListingGet_ac_type", ["CENTRAL", "EMPTY_VALUE", "NONE", "OTHER"])
  field("additional_fees_description", "string", [])
  field("address", "object", [])
  field("agent_company", "string", [])
  field("agent_email", "string", [])
  field("agent_fb_page_id", "object", [])
  field("agent_name", "string", [])
  field("agent_phone", "string", [])
  field("applinks", "object", [])
  field("area_size", "int", [])
  field("area_unit", "HomeListingGet_area_unit", ["EMPTY_VALUE", "SQFT", "SQM"])

  field("availability", "HomeListingGet_availability", [
    "AVAILABLE_SOON",
    "FOR_RENT",
    "FOR_SALE",
    "OFF_MARKET",
    "RECENTLY_SOLD",
    "SALE_PENDING"
  ])

  field("capabilities", "list<HomeListingGet_capabilities>", [])
  field("capabilities_disabled_by_user", "list<string>", [])

  field(
    "capabilities_rendering_catalog_manager",
    "list<HomeListingGet_capabilities_rendering_catalog_manager>",
    []
  )

  field("capability_to_rejection_reason", "list<object>", [])
  field("catalog_item_overrides", "object", [])
  field("channels_to_integrity_status", "object", [])
  field("co_2_emission_rating_eu", "object", [])
  field("currency", "string", [])
  field("custom_label_0", "string", [])
  field("custom_label_1", "string", [])
  field("custom_label_2", "string", [])
  field("custom_label_3", "string", [])
  field("custom_label_4", "string", [])
  field("custom_number_0", "int", [])
  field("custom_number_1", "int", [])
  field("custom_number_2", "int", [])
  field("custom_number_3", "int", [])
  field("custom_number_4", "int", [])
  field("days_on_market", "int", [])
  field("description", "string", [])
  field("enabled_capability_to_review_status", "list<object>", [])
  field("energy_rating_eu", "object", [])

  field("furnish_type", "HomeListingGet_furnish_type", [
    "EMPTY_VALUE",
    "FURNISHED",
    "SEMIFURNISHED",
    "UNFURNISHED"
  ])

  field("group_id", "string", [])

  field("heating_type", "HomeListingGet_heating_type", [
    "CENTRAL",
    "ELECTRIC",
    "EMPTY_VALUE",
    "GAS",
    "NONE",
    "OTHER",
    "RADIATOR"
  ])

  field("home_listing_id", "string", [])
  field("id", "int", [])

  field("image_fetch_status", "HomeListingGet_image_fetch_status", [
    "DIRECT_UPLOAD",
    "FETCHED",
    "FETCH_FAILED",
    "NO_STATUS",
    "OUTDATED",
    "PARTIAL_FETCH"
  ])

  field("images", "list<string>", [])
  field("is_blackholed", "bool", [])

  field("laundry_type", "HomeListingGet_laundry_type", [
    "EMPTY_VALUE",
    "IN_BUILDING",
    "IN_UNIT",
    "NONE",
    "OTHER"
  ])

  field("listing_type", "HomeListingGet_listing_type", [
    "EMPTY_VALUE",
    "FORECLOSED",
    "FOR_RENT_BY_AGENT",
    "FOR_RENT_BY_OWNER",
    "FOR_SALE_BY_AGENT",
    "FOR_SALE_BY_OWNER",
    "NEW_CONSTRUCTION",
    "NEW_LISTING",
    "OTHER"
  ])

  field("max_currency", "string", [])
  field("max_price", "string", [])
  field("min_currency", "string", [])
  field("min_price", "string", [])
  field("name", "string", [])
  field("num_baths", "float", [])
  field("num_beds", "float", [])
  field("num_rooms", "float", [])
  field("num_units", "int", [])
  field("override_details", "object", [])

  field("parking_type", "HomeListingGet_parking_type", [
    "EMPTY_VALUE",
    "GARAGE",
    "NONE",
    "OFF_STREET",
    "OTHER",
    "STREET"
  ])

  field("partner_verification", "HomeListingGet_partner_verification", [
    "EMPTY_VALUE",
    "NONE",
    "VERIFIED"
  ])

  field("pet_policy", "string", [])
  field("price", "string", [])
  field("product_feed", "object", [])

  field("property_type", "HomeListingGet_property_type", [
    "APARTMENT",
    "APARTMENT_ROOM",
    "BUILDER_FLOOR",
    "BUNGALOW",
    "CONDO",
    "CONDO_ROOM",
    "EMPTY_VALUE",
    "HOUSE",
    "HOUSE_IN_CONDOMINIUM",
    "HOUSE_IN_VILLA",
    "HOUSE_ROOM",
    "LAND",
    "LOFT",
    "MANUFACTURED",
    "OTHER",
    "OTHER_ROOM",
    "PENTHOUSE",
    "SINGLE_FAMILY_HOME",
    "STUDIO",
    "TOWNHOUSE",
    "TOWNHOUSE_ROOM"
  ])

  field("sanitized_images", "list<string>", [])
  field("sanitized_previews", "list<string>", [])
  field("securitydeposit_currency", "string", [])
  field("securitydeposit_price", "string", [])
  field("tags", "list<string>", [])
  field("unit_price", "object", [])
  field("url", "string", [])
  field("url_shimmed", "string", [])
  field("validation_errors", "object", [])
  field("videos_metadata", "object", [])

  field("visibility", "HomeListingGet_visibility", [
    "ACTIVE",
    "ARCHIVED",
    "HIDDEN",
    "LEGACY_PUBLIC",
    "PUBLISHED",
    "STAGING",
    "VISIBLE_ONLY_WITH_OVERRIDES",
    "WHITELIST_ONLY"
  ])

  field("year_built", "int", [])

  finish()
end
