# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Hours do
  use MetaAds.Model

  field("id", "string", [])
  field("permanent_status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
