# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGBoostMediaAd do
  use MetaAds.Model

  field("ad_id", "string", [])
  field("ad_status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
