# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGComment do
  use MetaAds.Model

  field("from", "IGCommentFromUser", [])
  field("hidden", "bool", [])
  field("id", "string", [])
  field("legacy_instagram_comment_id", "string", [])
  field("like_count", "int", [])
  field("media", "IGMedia", [])
  field("parent_id", "string", [])
  field("text", "string", [])
  field("timestamp", "datetime", [])
  field("user", "IGUser", [])
  field("username", "string", [])

  operation(:get_replies, "GET", "replies", nil, [])

  operation(:create_replies, "POST", "replies", nil, [
    %{"name" => "message", "required" => false, "type" => "string"}
  ])

  operation(:delete, "DELETE", "", nil, [
    %{"name" => "ad_id", "required" => false, "type" => "string"}
  ])

  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "ad_id", "required" => false, "type" => "string"},
    %{"name" => "hide", "required" => true, "type" => "bool"}
  ])

  finish()
end
