# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGMediaForIGOnlyAPI do
  use MetaAds.Model

  field("alt_text", "string", [])
  field("caption", "string", [])
  field("comments_count", "int", [])
  field("current_live_viewer_count", "int", [])
  field("id", "string", [])
  field("is_ai_generated", "bool", [])
  field("is_comment_enabled", "bool", [])
  field("is_shared_to_feed", "bool", [])
  field("like_count", "int", [])
  field("media_product_type", "string", [])
  field("media_type", "string", [])
  field("media_url", "string", [])
  field("owner", "User", [])
  field("permalink", "string", [])
  field("shortcode", "string", [])
  field("thumbnail_url", "string", [])
  field("timestamp", "datetime", [])
  field("username", "string", [])

  operation(:get_children, "GET", "children", nil, [])
  operation(:get_comments, "GET", "comments", nil, [])

  operation(:create_comments, "POST", "comments", nil, [
    %{"name" => "message", "required" => false, "type" => "string"}
  ])

  operation(:get_insights, "GET", "insights", nil, [
    %{
      "name" => "breakdown",
      "required" => false,
      "type" => "list<mediainsights_breakdown_enum_param>",
      "values" => ["action_type", "follow_type", "story_navigation_action_type", "surface_type"]
    },
    %{
      "name" => "metric",
      "required" => true,
      "type" => "list<mediainsights_metric_enum_param>",
      "values" => [
        "comments",
        "crossposted_views",
        "facebook_views",
        "follows",
        "ig_reels_avg_watch_time",
        "ig_reels_video_view_total_time",
        "impressions",
        "likes",
        "link_clicks",
        "navigation",
        "profile_activity",
        "profile_visits",
        "quotes",
        "reach",
        "reels_skip_rate",
        "replies",
        "reposts",
        "saved",
        "shares",
        "thread_replies",
        "thread_shares",
        "threads_media_clicks",
        "threads_reposts",
        "threads_views",
        "total_comments",
        "total_interactions",
        "total_likes",
        "total_views",
        "views"
      ]
    },
    %{
      "name" => "period",
      "required" => false,
      "type" => "list<mediainsights_period_enum_param>",
      "values" => ["day", "days_28", "lifetime", "month", "total_over_range", "week"]
    }
  ])

  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "comment_enabled", "required" => true, "type" => "bool"}
  ])

  finish()
end
