# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGMediaBoostEligibilityInfo do
  use MetaAds.Model

  field("boost_ineligible_reason", "string", [])
  field("eligible_to_boost", "bool", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
