# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGResumableVideoUploadStatus do
  use MetaAds.Model

  field("processing_phase", "VideoStatusProcessingPhase", [])
  field("uploading_phase", "VideoStatusUploadingPhase", [])

  finish()
end
