# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGShoppingReviewStatusOnsiteEligibility do
  use MetaAds.Model

  field("is_eligible", "bool", [])
  field("reasons", "list<IGShoppingReviewStatusReasonWithHelpMessage>", [])

  finish()
end
