# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGUserMessengerProfile do
  use MetaAds.Model

  field("ice_breakers", "list<Object>", [])
  field("persistent_menu", "list<Object>", [])

  finish()
end
