# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGUserSubscribedAppsData do
  use MetaAds.Model

  field("app_id", "string", [])
  field("subscribed_fields", "list<string>", [])

  finish()
end
