# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGUserExportForCAM do
  use MetaAds.Model

  field("age_bucket", "string", [])
  field("badges", "list<string>", [])
  field("biography", "string", [])
  field("category", "string", [])
  field("country", "string", [])
  field("email", "string", [])
  field("gender", "string", [])
  field("has_brand_partnership_experience", "bool", [])
  field("id", "string", [])
  field("is_account_verified", "bool", [])
  field("is_creator_following_brand", "bool", [])
  field("is_paid_partnership_messages_enabled", "bool", [])
  field("messaging_id", "string", [])
  field("onboarded_status", "bool", [])
  field("page_id", "string", [])
  field("page_name", "string", [])
  field("past_brand_partnership_partners", "list<string>", [])
  field("platforms", "list<string>", [])
  field("portfolio_url", "string", [])
  field("profile_picture_url", "string", [])
  field("username", "string", [])

  operation(:get_branded_content_media, "GET", "branded_content_media", nil, [])

  operation(:get_insights, "GET", "insights", nil, [
    %{
      "name" => "breakdown",
      "required" => false,
      "type" => "iguserexportforcaminsights_breakdown_enum_param",
      "values" => ["AGE", "FOLLOW_TYPE", "GENDER", "MEDIA_TYPE", "TOP_CITIES", "TOP_COUNTRIES"]
    },
    %{
      "name" => "metrics",
      "required" => false,
      "type" => "list<iguserexportforcaminsights_metrics_enum_param>",
      "values" => [
        "CREATOR_ENGAGED_ACCOUNTS",
        "CREATOR_REACH",
        "REELS_HOOK_RATE",
        "REELS_INTERACTION_RATE",
        "TOTAL_FOLLOWERS"
      ]
    },
    %{
      "name" => "period",
      "required" => false,
      "type" => "iguserexportforcaminsights_period_enum_param",
      "values" => ["DAY", "OVERALL"]
    },
    %{
      "name" => "platform",
      "required" => false,
      "type" => "list<iguserexportforcaminsights_platform_enum_param>",
      "values" => ["ANY", "BOTH", "FACEBOOK", "INSTAGRAM"]
    },
    %{
      "name" => "time_range",
      "required" => false,
      "type" => "iguserexportforcaminsights_time_range_enum_param",
      "values" => ["LAST_14_DAYS", "LAST_90_DAYS", "LIFETIME", "THIS_MONTH", "THIS_WEEK"]
    }
  ])

  operation(:get_past_partnership_ads_media, "GET", "past_partnership_ads_media", nil, [])
  operation(:get_recent_media, "GET", "recent_media", nil, [])
  finish()
end
