# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGUser do
  use MetaAds.Model

  field("biography", "string", [])
  field("business_discovery", "IGUser", [])
  field("collaborative_media_search", "ShadowIGUserCollaborativeMedia", [])
  field("followers_count", "int", [])
  field("follows_count", "int", [])
  field("has_profile_pic", "bool", [])
  field("id", "string", [])
  field("ig_id", "int", [])
  field("is_published", "bool", [])
  field("legacy_instagram_user_id", "string", [])
  field("media_count", "int", [])
  field("mentioned_comment", "IGComment", [])
  field("mentioned_media", "IGMedia", [])
  field("mini_shop_storefront", "Shop", [])
  field("name", "string", [])
  field("owner_business", "Business", [])
  field("profile_picture_url", "string", [])
  field("shopping_product_tag_eligibility", "bool", [])
  field("shopping_review_status", "string", [])
  field("username", "string", [])
  field("website", "string", [])

  operation(:get_agencies, "GET", "agencies", nil, [])

  operation(:get_authorized_adaccounts, "GET", "authorized_adaccounts", nil, [
    %{"name" => "business", "required" => true, "type" => "string"}
  ])

  operation(:create_authorized_adaccounts, "POST", "authorized_adaccounts", nil, [
    %{"name" => "account_id", "required" => true, "type" => "string"},
    %{"name" => "business", "required" => true, "type" => "string"}
  ])

  operation(:get_available_catalogs, "GET", "available_catalogs", nil, [])

  operation(:get_branded_content_ad_permissions, "GET", "branded_content_ad_permissions", nil, [
    %{"name" => "creator_username", "required" => false, "type" => "string"}
  ])

  operation(
    :create_branded_content_ad_permissions,
    "POST",
    "branded_content_ad_permissions",
    nil,
    [
      %{"name" => "creator_instagram_account", "required" => false, "type" => "string"},
      %{"name" => "creator_instagram_username", "required" => false, "type" => "string"},
      %{"name" => "revoke", "required" => false, "type" => "bool"}
    ]
  )

  operation(
    :get_branded_content_advertisable_medias,
    "GET",
    "branded_content_advertisable_medias",
    nil,
    [
      %{"name" => "ad_code", "required" => false, "type" => "string"},
      %{"name" => "creator_username", "required" => false, "type" => "string"},
      %{
        "name" => "media_relationship",
        "required" => false,
        "type" =>
          "list<shadowiguserbranded_content_advertisable_medias_media_relationship_enum_param>",
        "values" => ["IS_TAGGED", "OWNED"]
      },
      %{"name" => "only_fetch_allowlisted", "required" => false, "type" => "bool"},
      %{"name" => "only_fetch_recommended_content", "required" => false, "type" => "bool"},
      %{"name" => "permalinks", "required" => false, "type" => "list<string>"}
    ]
  )

  operation(:delete_branded_content_tag_approval, "DELETE", "branded_content_tag_approval", nil, [
    %{"name" => "user_ids", "required" => true, "type" => "list<unsigned int>"}
  ])

  operation(:get_branded_content_tag_approval, "GET", "branded_content_tag_approval", nil, [
    %{"name" => "user_ids", "required" => true, "type" => "list<unsigned int>"}
  ])

  operation(:create_branded_content_tag_approval, "POST", "branded_content_tag_approval", nil, [
    %{"name" => "user_ids", "required" => true, "type" => "list<unsigned int>"}
  ])

  operation(
    :create_business_messaging_feature_status,
    "POST",
    "business_messaging_feature_status",
    nil,
    [%{"name" => "features", "required" => true, "type" => "list<map>"}]
  )

  operation(:get_catalog_product_search, "GET", "catalog_product_search", nil, [
    %{"name" => "catalog_id", "required" => true, "type" => "string"},
    %{"name" => "q", "required" => false, "type" => "string"}
  ])

  operation(:get_collaboration_invites, "GET", "collaboration_invites", nil, [])

  operation(:create_collaboration_invites, "POST", "collaboration_invites", nil, [
    %{"name" => "accept", "required" => true, "type" => "bool"},
    %{"name" => "media_id", "required" => true, "type" => "string"}
  ])

  operation(:get_collaborative_media, "GET", "collaborative_media", nil, [])
  operation(:get_connected_threads_user, "GET", "connected_threads_user", nil, [])

  operation(:get_content_publishing_limit, "GET", "content_publishing_limit", nil, [
    %{"name" => "since", "required" => false, "type" => "datetime"}
  ])

  operation(:get_creator_marketplace_creators, "GET", "creator_marketplace_creators", nil, [
    %{"name" => "creator_age_bucket", "required" => false, "type" => "list<Object>"},
    %{
      "name" => "creator_countries",
      "required" => false,
      "type" => "list<shadowigusercreator_marketplace_creators_creator_countries_enum_param>",
      "values" => [
        "AC",
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AN",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ]
    },
    %{"name" => "creator_follower_growth", "required" => false, "type" => "Object"},
    %{
      "name" => "creator_gender",
      "required" => false,
      "type" => "list<shadowigusercreator_marketplace_creators_creator_gender_enum_param>",
      "values" => ["custom", "female", "male", "unknown"]
    },
    %{"name" => "creator_interests", "required" => false, "type" => "list<Object>"},
    %{"name" => "creator_latest_post_activity", "required" => false, "type" => "Object"},
    %{"name" => "creator_max_engaged_accounts", "required" => false, "type" => "unsigned int"},
    %{"name" => "creator_max_followers", "required" => false, "type" => "unsigned int"},
    %{"name" => "creator_min_engaged_accounts", "required" => false, "type" => "unsigned int"},
    %{"name" => "creator_min_followers", "required" => false, "type" => "unsigned int"},
    %{"name" => "creator_states", "required" => false, "type" => "list<string>"},
    %{"name" => "custom_audience_id", "required" => false, "type" => "string"},
    %{"name" => "has_public_contact_email", "required" => false, "type" => "bool"},
    %{"name" => "is_paid_partnership_messages_enabled", "required" => false, "type" => "bool"},
    %{"name" => "major_audience_age_bucket", "required" => false, "type" => "list<Object>"},
    %{
      "name" => "major_audience_countries",
      "required" => false,
      "type" =>
        "list<shadowigusercreator_marketplace_creators_major_audience_countries_enum_param>",
      "values" => [
        "AC",
        "AD",
        "AE",
        "AF",
        "AG",
        "AI",
        "AL",
        "AM",
        "AN",
        "AO",
        "AQ",
        "AR",
        "AS",
        "AT",
        "AU",
        "AW",
        "AX",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BL",
        "BM",
        "BN",
        "BO",
        "BQ",
        "BR",
        "BS",
        "BT",
        "BV",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CC",
        "CD",
        "CF",
        "CG",
        "CH",
        "CI",
        "CK",
        "CL",
        "CM",
        "CN",
        "CO",
        "CR",
        "CU",
        "CV",
        "CW",
        "CX",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "EH",
        "ER",
        "ES",
        "ET",
        "FI",
        "FJ",
        "FK",
        "FM",
        "FO",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GF",
        "GG",
        "GH",
        "GI",
        "GL",
        "GM",
        "GN",
        "GP",
        "GQ",
        "GR",
        "GS",
        "GT",
        "GU",
        "GW",
        "GY",
        "HK",
        "HM",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IM",
        "IN",
        "IO",
        "IQ",
        "IR",
        "IS",
        "IT",
        "JE",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KP",
        "KR",
        "KW",
        "KY",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MF",
        "MG",
        "MH",
        "MK",
        "ML",
        "MM",
        "MN",
        "MO",
        "MP",
        "MQ",
        "MR",
        "MS",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NC",
        "NE",
        "NF",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NU",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PF",
        "PG",
        "PH",
        "PK",
        "PL",
        "PM",
        "PN",
        "PR",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RE",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SD",
        "SE",
        "SG",
        "SH",
        "SI",
        "SJ",
        "SK",
        "SL",
        "SM",
        "SN",
        "SO",
        "SR",
        "SS",
        "ST",
        "SV",
        "SX",
        "SY",
        "SZ",
        "TC",
        "TD",
        "TF",
        "TG",
        "TH",
        "TJ",
        "TK",
        "TL",
        "TM",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "UM",
        "US",
        "UY",
        "UZ",
        "VA",
        "VC",
        "VE",
        "VG",
        "VI",
        "VN",
        "VU",
        "WF",
        "WS",
        "XK",
        "YE",
        "YT",
        "ZA",
        "ZM",
        "ZW"
      ]
    },
    %{"name" => "major_audience_device_type", "required" => false, "type" => "list<Object>"},
    %{
      "name" => "major_audience_gender",
      "required" => false,
      "type" => "list<shadowigusercreator_marketplace_creators_major_audience_gender_enum_param>",
      "values" => ["custom", "female", "male", "unknown"]
    },
    %{"name" => "major_audience_states", "required" => false, "type" => "list<string>"},
    %{"name" => "page_name", "required" => false, "type" => "string"},
    %{
      "name" => "platform",
      "required" => false,
      "type" => "shadowigusercreator_marketplace_creators_platform_enum_param",
      "values" => ["any", "both", "facebook", "instagram"]
    },
    %{"name" => "query", "required" => false, "type" => "string"},
    %{
      "name" => "recommendation_type",
      "required" => false,
      "type" => "shadowigusercreator_marketplace_creators_recommendation_type_enum_param",
      "values" => [
        "high_ad_performance",
        "interested_in_collaboration",
        "most_ads_experience",
        "most_relevant_for_me",
        "similar_audience",
        "similar_brands"
      ]
    },
    %{"name" => "reels_interaction_rate", "required" => false, "type" => "Object"},
    %{"name" => "show_onboarded_creators_only", "required" => false, "type" => "bool"},
    %{"name" => "similar_to_creators", "required" => false, "type" => "list<string>"},
    %{"name" => "username", "required" => false, "type" => "string"},
    %{"name" => "usernames", "required" => false, "type" => "list<string>"}
  ])

  operation(:get_dataset, "GET", "dataset", nil, [])

  operation(:create_dataset, "POST", "dataset", nil, [
    %{"name" => "dataset_name", "required" => false, "type" => "string"}
  ])

  operation(:get_insights, "GET", "insights", nil, [
    %{
      "name" => "breakdown",
      "required" => false,
      "type" => "list<shadowiguserinsights_breakdown_enum_param>",
      "values" => [
        "age",
        "city",
        "contact_button_type",
        "country",
        "follow_type",
        "gender",
        "media_product_type"
      ]
    },
    %{
      "name" => "metric",
      "required" => true,
      "type" => "list<shadowiguserinsights_metric_enum_param>",
      "values" => [
        "accounts_engaged",
        "comments",
        "content_views",
        "engaged_audience_demographics",
        "follower_count",
        "follower_demographics",
        "follows_and_unfollows",
        "likes",
        "online_followers",
        "profile_links_taps",
        "profile_views",
        "quotes",
        "reach",
        "reached_audience_demographics",
        "replies",
        "reposts",
        "saves",
        "shares",
        "threads_clicks",
        "threads_follower_demographics",
        "threads_followers",
        "threads_likes",
        "threads_replies",
        "threads_reposts",
        "threads_views",
        "total_interactions",
        "views",
        "website_clicks"
      ]
    },
    %{
      "name" => "metric_type",
      "required" => false,
      "type" => "shadowiguserinsights_metric_type_enum_param",
      "values" => ["default", "time_series", "total_value"]
    },
    %{
      "name" => "period",
      "required" => true,
      "type" => "list<shadowiguserinsights_period_enum_param>",
      "values" => ["day", "days_28", "lifetime", "month", "total_over_range", "week"]
    },
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{
      "name" => "timeframe",
      "required" => false,
      "type" => "shadowiguserinsights_timeframe_enum_param",
      "values" => [
        "last_14_days",
        "last_30_days",
        "last_90_days",
        "prev_month",
        "this_month",
        "this_week"
      ]
    },
    %{"name" => "until", "required" => false, "type" => "datetime"}
  ])

  operation(:get_instagram_backed_threads_user, "GET", "instagram_backed_threads_user", nil, [])

  operation(
    :create_instagram_backed_threads_user,
    "POST",
    "instagram_backed_threads_user",
    nil,
    []
  )

  operation(:get_live_media, "GET", "live_media", nil, [
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{"name" => "until", "required" => false, "type" => "datetime"}
  ])

  operation(:get_media, "GET", "media", nil, [
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{"name" => "until", "required" => false, "type" => "datetime"}
  ])

  operation(:create_media, "POST", "media", nil, [
    %{"name" => "alt_text", "required" => false, "type" => "string"},
    %{"name" => "audio_configuration", "required" => false, "type" => "string"},
    %{"name" => "audio_name", "required" => false, "type" => "string"},
    %{
      "name" => "branded_content_sponsor_ids",
      "required" => false,
      "type" => "list<unsigned int>"
    },
    %{"name" => "caption", "required" => false, "type" => "string"},
    %{"name" => "children", "required" => false, "type" => "list<string>"},
    %{"name" => "collaborators", "required" => false, "type" => "list<string>"},
    %{"name" => "cover_url", "required" => false, "type" => "string"},
    %{"name" => "image_url", "required" => false, "type" => "string"},
    %{"name" => "is_ai_generated", "required" => false, "type" => "bool"},
    %{"name" => "is_carousel_item", "required" => false, "type" => "bool"},
    %{"name" => "is_comment_prompt_used", "required" => false, "type" => "bool"},
    %{"name" => "is_paid_partnership", "required" => false, "type" => "bool"},
    %{"name" => "is_poll_duration_extended", "required" => false, "type" => "bool"},
    %{"name" => "location_id", "required" => false, "type" => "string"},
    %{"name" => "media_type", "required" => false, "type" => "string"},
    %{"name" => "poll_attachment", "required" => false, "type" => "string"},
    %{"name" => "product_tags", "required" => false, "type" => "list<map>"},
    %{"name" => "share_to_feed", "required" => false, "type" => "bool"},
    %{"name" => "thumb_offset", "required" => false, "type" => "string"},
    %{"name" => "trial_params", "required" => false, "type" => "map"},
    %{"name" => "upload_type", "required" => false, "type" => "string"},
    %{"name" => "user_tags", "required" => false, "type" => "list<map>"},
    %{"name" => "video_url", "required" => false, "type" => "string"}
  ])

  operation(:create_media_publish, "POST", "media_publish", nil, [
    %{"name" => "creation_id", "required" => true, "type" => "unsigned int"}
  ])

  operation(:create_mentions, "POST", "mentions", nil, [
    %{"name" => "comment_id", "required" => false, "type" => "string"},
    %{"name" => "media_id", "required" => true, "type" => "string"},
    %{"name" => "message", "required" => true, "type" => "string"}
  ])

  operation(:create_moderate_conversations, "POST", "moderate_conversations", nil, [
    %{
      "name" => "actions",
      "required" => true,
      "type" => "list<shadowigusermoderate_conversations_actions_enum_param>",
      "values" => ["BLOCK_USER", "MOVE_TO_SPAM", "UNBLOCK_USER"]
    },
    %{"name" => "user_ids", "required" => true, "type" => "list<map>"}
  ])

  operation(:get_notification_message_tokens, "GET", "notification_message_tokens", nil, [])

  operation(:get_product_appeal, "GET", "product_appeal", nil, [
    %{"name" => "product_id", "required" => true, "type" => "string"}
  ])

  operation(:create_product_appeal, "POST", "product_appeal", nil, [
    %{"name" => "appeal_reason", "required" => true, "type" => "string"},
    %{"name" => "product_id", "required" => true, "type" => "string"}
  ])

  operation(:get_recently_searched_hashtags, "GET", "recently_searched_hashtags", nil, [])
  operation(:get_scheduled_media, "GET", "scheduled_media", nil, [])
  operation(:get_stories, "GET", "stories", nil, [])

  operation(:get_tags, "GET", "tags", nil, [
    %{"name" => "media_type", "required" => false, "type" => "string"},
    %{"name" => "posted_after", "required" => false, "type" => "string"},
    %{"name" => "posted_before", "required" => false, "type" => "string"}
  ])

  operation(:get_upcoming_events, "GET", "upcoming_events", nil, [])

  operation(:create_upcoming_events, "POST", "upcoming_events", nil, [
    %{"name" => "end_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "notification_subtypes",
      "required" => false,
      "type" => "list<shadowiguserupcoming_events_notification_subtypes_enum_param>",
      "values" => [
        "AFTER_EVENT_1DAY",
        "AFTER_EVENT_2DAY",
        "AFTER_EVENT_3DAY",
        "AFTER_EVENT_4DAY",
        "AFTER_EVENT_5DAY",
        "AFTER_EVENT_6DAY",
        "AFTER_EVENT_7DAY",
        "BEFORE_EVENT_15MIN",
        "BEFORE_EVENT_1DAY",
        "BEFORE_EVENT_1HOUR",
        "BEFORE_EVENT_2DAY",
        "EVENT_START",
        "RESCHEDULED"
      ]
    },
    %{"name" => "start_time", "required" => true, "type" => "datetime"},
    %{"name" => "title", "required" => true, "type" => "string"}
  ])

  operation(:get_welcome_message_flows, "GET", "welcome_message_flows", nil, [
    %{"name" => "app_id", "required" => false, "type" => "string"},
    %{"name" => "flow_id", "required" => false, "type" => "string"}
  ])

  operation(:get, "GET", "", nil, [
    %{"name" => "adgroup_id", "required" => false, "type" => "string"}
  ])

  finish()
end
