# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IGVideoCopyrightCheckMatchesInformation do
  use MetaAds.Model

  field("copyright_matches", "list<Object>", [])
  field("status", "IGVideoCopyrightCheckStatus", [])

  finish()
end
