# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.InstagramRelatedProductTags do
  use MetaAds.Model

  field("checkout_setting", "string", [])
  field("id", "int", [])
  field("image_uri", "string", [])
  field("name", "string", [])
  field("price_label", "string", [])
  field("sale_price_label", "string", [])

  finish()
end
