# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IntegrityAppealGetAdAppealEligibility do
  use MetaAds.Model

  field("ad_id", "int", [])
  field("ineligibility_reason", "string", [])
  field("is_eligible", "bool", [])

  finish()
end
