# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IntegrityAppeal do
  use MetaAds.Model

  operation(:get_get_ad_appeal_bulk_eligibility, "GET", "", "integrity/appeals/ads/eligibility", [
    %{"name" => "ad_ids", "required" => true, "type" => "list<int>"}
  ])

  operation(:get_get_ad_appeal_bulk_status, "GET", "", "integrity/appeals/ads/status", [
    %{"name" => "ad_ids", "required" => true, "type" => "list<int>"}
  ])

  operation(:get_eligibility, "GET", "eligibility", "integrity/appeals/ads", [])
  operation(:get_status, "GET", "status", "integrity/appeals/ads", [])
  operation(:create_post_ad_appeal_bulk, "POST", "", "integrity/appeals/ads", [])
  finish()
end
