# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.IPObject do
  use MetaAds.Model

  field("ip_permission", "string", [])
  field("user", "Object", [])

  finish()
end
