# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.KeyValue do
  use MetaAds.Model

  field("key", "string", [])
  field("value", "string", [])

  finish()
end
