# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenLegalContent do
  use MetaAds.Model

  field("custom_disclaimer", "LeadGenCustomDisclaimer", [])
  field("id", "string", [])
  field("privacy_policy", "LeadGenPrivacyPolicy", [])

  finish()
end
