# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenClientValidationRules do
  use MetaAds.Model

  field("exclude_emoji_and_special_chars_enabled", "bool", [])
  field("max_length_value", "int", [])
  field("min_length_value", "int", [])

  finish()
end
