# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenDraftQuestion do
  use MetaAds.Model

  field("conditional_questions_choices", "list<LeadGenConditionalQuestionsGroupChoices>", [])
  field("conditional_questions_group_id", "string", [])
  field("dependent_conditional_questions", "list<LeadGenConditionalQuestionsGroupQuestions>", [])
  field("inline_context", "string", [])
  field("key", "string", [])
  field("label", "string", [])
  field("options", "list<LeadGenQuestionOption>", [])
  field("type", "string", [])

  finish()
end
