# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenContextCard do
  use MetaAds.Model

  field("button_text", "string", [])
  field("content", "list<string>", [])
  field("cover_photo", "Photo", [])
  field("id", "string", [])
  field("style", "string", [])
  field("title", "string", [])

  finish()
end
