# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenLegalContentCheckbox do
  use MetaAds.Model

  field("id", "string", [])
  field("is_checked_by_default", "bool", [])
  field("is_required", "bool", [])
  field("key", "string", [])
  field("text", "string", [])

  finish()
end
