# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenConditionalQuestionsGroupChoices do
  use MetaAds.Model

  field("customized_token", "string", [])
  field("next_question_choices", "list<LeadGenConditionalQuestionsGroupChoices>", [])
  field("value", "string", [])

  finish()
end
