# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenThankYouPage do
  use MetaAds.Model

  field("body", "string", [])
  field("business_phone_number", "string", [])
  field("button_text", "string", [])
  field("button_type", "string", [])
  field("country_code", "string", [])
  field("enable_messenger", "bool", [])
  field("gated_file", "LeadGenThankYouPageGatedFile", [])
  field("id", "string", [])
  field("lead_gen_use_case", "string", [])
  field("status", "string", [])
  field("title", "string", [])
  field("website_url", "string", [])

  finish()
end
