# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenCustomDisclaimer do
  use MetaAds.Model

  field("body", "LeadGenCustomDisclaimerBody", [])
  field("checkboxes", "list<LeadGenLegalContentCheckbox>", [])
  field("title", "string", [])

  finish()
end
