# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Lead do
  use MetaAds.Model

  field("ad_id", "string", [])
  field("ad_name", "string", [])
  field("adset_id", "string", [])
  field("adset_name", "string", [])
  field("campaign_id", "string", [])
  field("campaign_name", "string", [])
  field("created_time", "datetime", [])
  field("custom_disclaimer_responses", "list<UserLeadGenDisclaimerResponse>", [])
  field("field_data", "list<UserLeadGenFieldData>", [])
  field("form_id", "string", [])
  field("home_listing", "HomeListing", [])
  field("id", "string", [])
  field("is_organic", "bool", [])
  field("partner_name", "string", [])
  field("platform", "string", [])
  field("post", "Link", [])
  field("post_submission_check_result", "LeadGenPostSubmissionCheckResult", [])
  field("retailer_item_id", "string", [])
  field("vehicle", "Vehicle", [])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
