# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenURLEntityAtRanges do
  use MetaAds.Model

  field("length", "unsigned int", [])
  field("offset", "unsigned int", [])
  field("url", "string", [])

  finish()
end
