# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LeadGenConditionalQuestionsGroupQuestions do
  use MetaAds.Model

  field("field_key", "string", [])
  field("input_type", "string", [])
  field("name", "string", [])

  finish()
end
