# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Link do
  use MetaAds.Model

  field("caption", "string", [])
  field("created_time", "datetime", [])
  field("description", "string", [])
  field("from", "Object", [])
  field("icon", "string", [])
  field("id", "string", [])
  field("link", "string", [])
  field("message", "string", [])
  field("multi_share_optimized", "bool", [])
  field("name", "string", [])
  field("privacy", "Privacy", [])
  field("via", "Object", [])

  operation(:create_comments, "POST", "comments", nil, [
    %{"name" => "attachment_id", "required" => false, "type" => "string"},
    %{"name" => "attachment_share_url", "required" => false, "type" => "string"},
    %{"name" => "attachment_url", "required" => false, "type" => "string"},
    %{
      "name" => "comment_privacy_value",
      "required" => false,
      "type" => "linkcomments_comment_privacy_value_enum_param",
      "values" => [
        "DECLINED_BY_ADMIN_ASSISTANT",
        "DEFAULT_PRIVACY",
        "FRIENDS_AND_POST_OWNER",
        "FRIENDS_ONLY",
        "GRAPHQL_MULTIPLE_VALUE_HACK_DO_NOT_USE",
        "OWNER_OR_COMMENTER",
        "PENDING_APPROVAL",
        "PRIVATE_CONVERSATION_PARTICIPANTS_ONLY",
        "REMOVED_BY_ADMIN_ASSISTANT",
        "SIDE_CONVERSATION",
        "SIDE_CONVERSATION_AND_POST_OWNER",
        "SPOTLIGHT_TAB"
      ]
    },
    %{"name" => "facepile_mentioned_ids", "required" => false, "type" => "list<string>"},
    %{"name" => "feedback_source", "required" => false, "type" => "string"},
    %{"name" => "is_offline", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "object_id", "required" => false, "type" => "string"},
    %{"name" => "parent_comment_id", "required" => false, "type" => "Object"},
    %{"name" => "text", "required" => false, "type" => "string"},
    %{"name" => "tracking", "required" => false, "type" => "string"}
  ])

  operation(:get_likes, "GET", "likes", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
