# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LinkedInstagramAccountData do
  use MetaAds.Model

  field("access_token", "string", [])
  field("analytics_claim", "string", [])
  field("full_name", "string", [])
  field("profile_picture_url", "string", [])
  field("user_id", "string", [])
  field("user_name", "string", [])

  finish()
end
