# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LiveVideoError do
  use MetaAds.Model

  field("creation_time", "datetime", [])
  field("error_code", "int", [])
  field("error_message", "string", [])
  field("error_type", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
