# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LiveVideo do
  use MetaAds.Model

  field("ad_break_config", "LiveVideoAdBreakConfig", [])
  field("ad_break_failure_reason", "string", [])
  field("broadcast_start_time", "datetime", [])
  field("copyright", "VideoCopyright", [])
  field("creation_time", "datetime", [])
  field("dash_ingest_url", "string", [])
  field("dash_preview_url", "string", [])
  field("description", "string", [])
  field("embed_html", "Object", [])
  field("from", "Object", [])
  field("id", "string", [])
  field("ingest_streams", "list<LiveVideoInputStream>", [])
  field("is_manual_mode", "bool", [])
  field("is_reference_only", "bool", [])
  field("live_views", "unsigned int", [])
  field("permalink_url", "string", [])
  field("planned_start_time", "datetime", [])
  field("recommended_encoder_settings", "LiveVideoRecommendedEncoderSettings", [])
  field("seconds_left", "int", [])
  field("secure_stream_url", "string", [])
  field("status", "string", [])
  field("stream_url", "string", [])
  field("targeting", "LiveVideoTargeting", [])
  field("title", "string", [])
  field("total_views", "string", [])
  field("video", "AdVideo", [])

  operation(:get_blocked_users, "GET", "blocked_users", nil, [
    %{"name" => "uid", "required" => false, "type" => "string"}
  ])

  operation(:get_comments, "GET", "comments", nil, [
    %{
      "name" => "filter",
      "required" => false,
      "type" => "livevideocomments_filter_enum_param",
      "values" => ["stream", "toplevel"]
    },
    %{
      "name" => "live_filter",
      "required" => false,
      "type" => "livevideocomments_live_filter_enum_param",
      "values" => ["filter_low_quality", "no_filter"]
    },
    %{
      "name" => "order",
      "required" => false,
      "type" => "livevideocomments_order_enum_param",
      "values" => ["chronological", "reverse_chronological"]
    },
    %{"name" => "since", "required" => false, "type" => "datetime"}
  ])

  operation(:get_crosspost_shared_pages, "GET", "crosspost_shared_pages", nil, [])
  operation(:get_crossposted_broadcasts, "GET", "crossposted_broadcasts", nil, [])
  operation(:get_errors, "GET", "errors", nil, [])
  operation(:create_input_streams, "POST", "input_streams", nil, [])
  operation(:get_polls, "GET", "polls", nil, [])

  operation(:create_polls, "POST", "polls", nil, [
    %{"name" => "close_after_voting", "required" => false, "type" => "bool"},
    %{"name" => "correct_option", "required" => false, "type" => "unsigned int"},
    %{"name" => "default_open", "required" => false, "type" => "bool"},
    %{"name" => "options", "required" => true, "type" => "list<string>"},
    %{"name" => "question", "required" => true, "type" => "string"},
    %{"name" => "show_gradient", "required" => false, "type" => "bool"},
    %{"name" => "show_results", "required" => false, "type" => "bool"}
  ])

  operation(:get_reactions, "GET", "reactions", nil, [
    %{
      "name" => "type",
      "required" => false,
      "type" => "livevideoreactions_type_enum_param",
      "values" => [
        "ANGRY",
        "CARE",
        "FIRE",
        "HAHA",
        "HUNDRED",
        "LIKE",
        "LOVE",
        "NONE",
        "PRIDE",
        "SAD",
        "THANKFUL",
        "WOW"
      ]
    }
  ])

  operation(:delete, "DELETE", "", nil, [])

  operation(:get, "GET", "", nil, [
    %{"name" => "target_token", "required" => false, "type" => "string"}
  ])

  operation(:create, "POST", "", nil, [
    %{"name" => "allow_bm_crossposting", "required" => false, "type" => "bool"},
    %{"name" => "content_tags", "required" => false, "type" => "list<string>"},
    %{"name" => "cross_share_to_group_ids", "required" => false, "type" => "list<string>"},
    %{"name" => "crossposting_actions", "required" => false, "type" => "list<map>"},
    %{"name" => "custom_labels", "required" => false, "type" => "list<string>"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "direct_share_status", "required" => false, "type" => "unsigned int"},
    %{"name" => "embeddable", "required" => false, "type" => "bool"},
    %{"name" => "end_live_video", "required" => false, "type" => "bool"},
    %{"name" => "event_params", "required" => false, "type" => "Object"},
    %{"name" => "is_audio_only", "required" => false, "type" => "bool"},
    %{"name" => "is_manual_mode", "required" => false, "type" => "bool"},
    %{
      "name" => "live_comment_moderation_setting",
      "required" => false,
      "type" => "list<livevideo_live_comment_moderation_setting>",
      "values" => [
        "DEFAULT",
        "DISCUSSION",
        "FOLLOWED",
        "FOLLOWER",
        "NO_HYPERLINK",
        "PROTECTED_MODE",
        "RESTRICTED",
        "SLOW",
        "SUPPORTER",
        "TAGGED"
      ]
    },
    %{"name" => "master_ingest_stream_id", "required" => false, "type" => "string"},
    %{"name" => "og_icon_id", "required" => false, "type" => "string"},
    %{"name" => "og_phrase", "required" => false, "type" => "string"},
    %{
      "name" => "persistent_stream_key_status",
      "required" => false,
      "type" => "livevideo_persistent_stream_key_status",
      "values" => ["DISABLE", "ENABLE", "REGENERATE"]
    },
    %{"name" => "place", "required" => false, "type" => "Object"},
    %{"name" => "planned_start_time", "required" => false, "type" => "datetime"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "schedule_custom_profile_image", "required" => false, "type" => "file"},
    %{"name" => "schedule_feed_background_image", "required" => false, "type" => "file"},
    %{"name" => "sponsor_id", "required" => false, "type" => "string"},
    %{"name" => "sponsor_relationship", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "status",
      "required" => false,
      "type" => "livevideo_status",
      "values" => [
        "LIVE_NOW",
        "SCHEDULED_CANCELED",
        "SCHEDULED_LIVE",
        "SCHEDULED_UNPUBLISHED",
        "UNPUBLISHED"
      ]
    },
    %{
      "name" => "stream_type",
      "required" => false,
      "type" => "livevideo_stream_type",
      "values" => ["AMBIENT", "REGULAR"]
    },
    %{"name" => "tags", "required" => false, "type" => "list<int>"},
    %{"name" => "targeting", "required" => false, "type" => "Object"},
    %{"name" => "title", "required" => false, "type" => "string"}
  ])

  finish()
end
