# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LiveVideoAdCampaignConfig do
  use MetaAds.Model

  field("id", "string", [])
  field("live_video_ad_type", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
