# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LiveVideoTargeting do
  use MetaAds.Model

  field("age_max", "unsigned int", [])
  field("age_min", "unsigned int", [])
  field("excluded_countries", "list<string>", [])
  field("geo_locations", "TargetingGeoLocation", [])

  finish()
end
