# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LiveVideoAdBreakConfig do
  use MetaAds.Model

  field("default_ad_break_duration", "unsigned int", [])
  field("failure_reason_polling_interval", "unsigned int", [])
  field("first_break_eligible_secs", "unsigned int", [])
  field("guide_url", "string", [])
  field("is_eligible_to_onboard", "bool", [])
  field("is_enabled", "bool", [])
  field("onboarding_url", "string", [])
  field("preparing_duration", "unsigned int", [])
  field("time_between_ad_breaks_secs", "unsigned int", [])
  field("viewer_count_threshold", "unsigned int", [])

  finish()
end
