# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LocalServiceBusiness do
  use MetaAds.Model

  field("address", "Object", [])
  field("applinks", "CatalogItemAppLinks", [])

  field("availability", "LocalServiceBusiness_availability", [
    "AVAILABLE_FOR_ORDER",
    "DISCONTINUED",
    "IN_STOCK",
    "MARK_AS_EXPIRED",
    "MARK_AS_SOLD",
    "OUT_OF_STOCK",
    "PENDING",
    "PREORDER"
  ])

  field("brand", "string", [])
  field("category", "string", [])

  field("condition", "LocalServiceBusiness_condition", [
    "PC_CPO",
    "PC_NEW",
    "PC_OPEN_BOX_NEW",
    "PC_REFURBISHED",
    "PC_USED",
    "PC_USED_FAIR",
    "PC_USED_GOOD",
    "PC_USED_LIKE_NEW"
  ])

  field("cuisine_type", "string", [])
  field("currency", "string", [])
  field("custom_label_0", "string", [])
  field("custom_label_1", "string", [])
  field("custom_label_2", "string", [])
  field("custom_label_3", "string", [])
  field("custom_label_4", "string", [])
  field("custom_number_0", "unsigned int", [])
  field("custom_number_1", "unsigned int", [])
  field("custom_number_2", "unsigned int", [])
  field("custom_number_3", "unsigned int", [])
  field("custom_number_4", "unsigned int", [])
  field("description", "string", [])
  field("expiration_date", "string", [])
  field("gtin", "string", [])
  field("id", "string", [])

  field("image_fetch_status", "LocalServiceBusiness_image_fetch_status", [
    "DIRECT_UPLOAD",
    "FETCHED",
    "FETCH_FAILED",
    "NO_STATUS",
    "OUTDATED",
    "PARTIAL_FETCH"
  ])

  field("images", "list<string>", [])
  field("local_info", "ProductItemLocalInfo", [])
  field("local_service_business_id", "string", [])
  field("main_local_info", "ProductItemLocalInfo", [])
  field("phone", "string", [])
  field("price", "string", [])
  field("price_range", "string", [])
  field("retailer_category", "string", [])
  field("sanitized_images", "list<string>", [])
  field("size", "string", [])
  field("tags", "list<string>", [])
  field("title", "string", [])
  field("unit_price", "Object", [])
  field("url", "string", [])
  field("vendor_id", "string", [])
  field("visibility", "LocalServiceBusiness_visibility", ["PUBLISHED", "STAGING"])

  operation(:get_channels_to_integrity_status, "GET", "channels_to_integrity_status", nil, [])

  operation(:get_override_details, "GET", "override_details", nil, [
    %{"name" => "keys", "required" => false, "type" => "list<string>"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "localservicebusinessoverride_details_type_enum_param",
      "values" => ["COUNTRY", "LANGUAGE", "LANGUAGE_AND_COUNTRY"]
    }
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
