# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.LookalikeSpec do
  use MetaAds.Model

  field("country", "string", [])
  field("is_created_by_recommended_dfca", "bool", [])
  field("is_financial_service", "bool", [])
  field("is_parent_lal", "bool", [])
  field("origin", "list<Object>", [])
  field("origin_event_name", "string", [])
  field("origin_event_source_name", "string", [])
  field("origin_event_source_type", "string", [])
  field("product_set_name", "string", [])
  field("ratio", "float", [])
  field("starting_ratio", "float", [])
  field("target_countries", "list<string>", [])
  field("target_country_names", "list", [])
  field("type", "string", [])

  finish()
end
