# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ManagementSiteLink do
  use MetaAds.Model

  field("ad_account_id", "string", [])
  field("id", "string", [])
  field("link_domain", "string", [])
  field("link_hash", "string", [])
  field("link_image_hash", "string", [])
  field("link_image_url", "string", [])
  field("link_title", "string", [])
  field("link_type", "string", [])
  field("link_url", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
