# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MarketingMessagesOnboardingStatus do
  use MetaAds.Model

  field("status", "string", [])
  field("time", "datetime", [])

  finish()
end
