# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MCExperienceConfigForApi do
  use MetaAds.Model

  field("is_campaign_enabled", "bool", [])
  field("is_terms_signed", "bool", [])
  field("is_user_manually_toggle_mc_off", "bool", [])
  field("merchant_type", "string", [])

  finish()
end
