# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.McomInvoiceStatus do
  use MetaAds.Model

  field("bank_account_number", "string", [])
  field("bank_code", "string", [])
  field("invoice_id", "string", [])
  field("invoice_status", "string", [])
  field("page_id", "string", [])
  field("payment_method", "string", [])
  field("payment_type", "string", [])
  field("payout_amount", "Object", [])
  field("slip_verification_error", "string", [])
  field("slip_verification_status", "string", [])
  field("sof_transfer_id", "string", [])
  field("sof_transfer_timestamp", "int", [])
  field("transaction_fee", "Object", [])
  field("transfer_slip", "string", [])
  field("transfer_slip_qr_code", "string", [])

  finish()
end
