# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.McomInvoiceLists do
  use MetaAds.Model

  field("invoice_details", "list<McomInvoiceDetails>", [])
  field("invoice_ids", "list<string>", [])
  field("page_id", "string", [])

  finish()
end
