# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.McomInvoiceDetails do
  use MetaAds.Model

  field("additional_amounts", "list<Object>", [])
  field("buyer_notes", "string", [])
  field("currency_amount", "Object", [])
  field("external_invoice_id", "string", [])
  field("features", "Object", [])
  field("invoice_created", "int", [])
  field("invoice_id", "string", [])
  field("invoice_instructions", "string", [])
  field("invoice_instructions_image_url", "string", [])
  field("invoice_updated", "int", [])
  field("outstanding_amount", "Object", [])
  field("paid_amount", "Object", [])
  field("payments", "list<Object>", [])
  field("platform_logo_url", "string", [])
  field("platform_name", "string", [])
  field("product_items", "list<Object>", [])
  field("shipping_address", "Object", [])
  field("status", "string", [])
  field("tracking_info", "Object", [])

  finish()
end
