# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.McomOnboardingStatus do
  use MetaAds.Model

  field("onboarding_status", "string", [])
  field("page_id", "string", [])

  finish()
end
