# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MeasurementReport do
  use MetaAds.Model

  field("download_urls", "list<string>", [])
  field("id", "string", [])
  field("metadata", "map", [])
  field("report_type", "string", [])
  field("status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
