# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MediaFingerprint do
  use MetaAds.Model

  field("duration_in_sec", "float", [])
  field("fingerprint_content_type", "string", [])
  field("fingerprint_type", "string", [])
  field("id", "string", [])
  field("metadata", "Object", [])
  field("title", "string", [])
  field("universal_content_id", "string", [])

  operation(:get, "GET", "", nil, [])

  finish()
end
