# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MessageDeliveryEstimate do
  use MetaAds.Model

  field("estimate_cost", "float", [])
  field("estimate_cost_lower_bound", "float", [])
  field("estimate_cost_upper_bound", "float", [])
  field("estimate_coverage_lower_bound", "int", [])
  field("estimate_coverage_upper_bound", "int", [])
  field("estimate_delivery", "int", [])
  field("estimate_delivery_lower_bound", "int", [])
  field("estimate_delivery_upper_bound", "int", [])
  field("estimate_status", "string", [])

  finish()
end
