# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MessengerProfile do
  use MetaAds.Model

  field("account_linking_url", "string", [])
  field("commands", "list<Object>", [])
  field("get_started", "Object", [])
  field("ice_breakers", "list<Object>", [])
  field("persistent_menu", "list<Object>", [])
  field("subject_to_new_eu_privacy_rules", "bool", [])
  field("whitelisted_domains", "list<string>", [])

  finish()
end
