# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MessengerBusinessTemplate do
  use MetaAds.Model

  field("category", "string", [])
  field("components", "list<Object>", [])
  field("creation_time", "int", [])
  field("id", "string", [])
  field("language", "string", [])
  field("language_count", "int", [])
  field("last_updated_time", "datetime", [])
  field("library_template_name", "string", [])
  field("name", "string", [])
  field("parameter_format", "string", [])
  field("rejected_reason", "string", [])
  field("rejection_reasons", "Object", [])
  field("specific_rejection_reasons", "Object", [])
  field("status", "string", [])

  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "components", "required" => false, "type" => "list<map>"},
    %{
      "name" => "parameter_format",
      "required" => false,
      "type" => "messengerbusinesstemplate_parameter_format",
      "values" => ["NAMED", "POSITIONAL"]
    }
  ])

  finish()
end
