# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MessagingAppsInfo do
  use MetaAds.Model

  field("ctd_support_only_for_ig_app", "bool", [])
  field("has_instagram_messaging_permission", "bool", [])
  field("has_messenger_messaging_permission", "bool", [])
  field("id", "string", [])
  field("name", "string", [])

  finish()
end
