# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.MetaMomentMakerConfig do
  use MetaAds.Model

  field("saturation_mode", "string", [])

  finish()
end
