# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OfflineConversionDataSetOptimizationStatus do
  use MetaAds.Model

  field("event", "string", [])
  field("last_changed_time", "int", [])
  field("last_detected_time", "int", [])
  field("status", "string", [])

  finish()
end
