# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OfflineConversionDataSetUpload do
  use MetaAds.Model

  field("api_calls", "int", [])
  field("creation_time", "int", [])
  field("duplicate_entries", "int", [])
  field("event_stats", "string", [])
  field("event_time_max", "int", [])
  field("event_time_min", "int", [])
  field("first_upload_time", "int", [])
  field("id", "string", [])
  field("is_excluded_for_lift", "bool", [])
  field("last_upload_time", "int", [])
  field("match_rate_approx", "int", [])
  field("matched_entries", "int", [])
  field("upload_tag", "string", [])
  field("valid_entries", "int", [])

  operation(:get_progress, "GET", "progress", nil, [])
  operation(:get_pull_sessions, "GET", "pull_sessions", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
