# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OfflineConversionDataSetPermissions do
  use MetaAds.Model

  field("can_edit", "bool", [])
  field("can_edit_or_upload", "bool", [])
  field("can_upload", "bool", [])
  field("should_block_vanilla_business_employee_access", "bool", [])

  finish()
end
