# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OfflineConversionDataSetUsage do
  use MetaAds.Model

  field("num_lift_studies", "int", [])

  finish()
end
