# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OffsiteSignalContainerBusinessObject do
  use MetaAds.Model

  field("business", "Business", [])
  field("id", "string", [])
  field("is_eligible_for_sharing_to_ad_account", "bool", [])
  field("is_eligible_for_sharing_to_business", "bool", [])
  field("is_unavailable", "bool", [])
  field("name", "string", [])
  field("primary_container_id", "string", [])

  operation(:get_linked_application, "GET", "linked_application", nil, [])
  operation(:get_linked_page, "GET", "linked_page", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
