# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OmegaCustomerTrx do
  use MetaAds.Model

  field("ad_account_ids", "list<string>", [])
  field("advertiser_name", "string", [])
  field("amount", "string", [])
  field("amount_due", "CurrencyAmount", [])
  field("billed_amount_details", "Object", [])
  field("billing_period", "string", [])
  field("cdn_download_uri", "string", [])
  field("currency", "string", [])
  field("download_uri", "string", [])
  field("due_date", "datetime", [])
  field("entity", "string", [])
  field("id", "string", [])
  field("invoice_date", "datetime", [])
  field("invoice_id", "string", [])
  field("invoice_type", "string", [])
  field("liability_type", "string", [])
  field("payment_status", "string", [])
  field("payment_term", "string", [])
  field("type", "string", [])

  operation(:get_campaigns, "GET", "campaigns", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
