# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OpenBridgeConfiguration do
  use MetaAds.Model

  field("active", "bool", [])
  field("associated_sgw_data_source_id", "string", [])
  field("blocked_event_types", "list<string>", [])
  field("blocked_websites", "list<string>", [])
  field("browser_agent", "list<string>", [])
  field("capi_publishing_state", "string", [])
  field("cloud_provider", "string", [])
  field("cloud_region", "string", [])
  field("destination_id", "string", [])
  field("endpoint", "string", [])
  field("event_enrichment_advertiser_state", "string", [])
  field("event_enrichment_meta_state", "string", [])
  field("event_enrichment_state", "string", [])
  field("fallback_domain", "string", [])
  field("host_business_id", "string", [])
  field("id", "string", [])
  field("instance_id", "string", [])
  field("instance_version", "string", [])
  field("is_sgw_instance", "bool", [])
  field("is_sgw_pixel_from_meta_pixel", "bool", [])
  field("mpc_fallback_domain", "string", [])
  field("partner_name", "string", [])
  field("pixel_id", "string", [])
  field("sgw_account_id", "string", [])
  field("sgw_instance_url", "string", [])
  field("sgw_pixel_id", "string", [])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "active", "required" => false, "type" => "bool"},
    %{"name" => "associated_sgw_data_source_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "blocked_event_types", "required" => false, "type" => "list<string>"},
    %{"name" => "blocked_websites", "required" => false, "type" => "list<string>"},
    %{
      "name" => "capi_publishing_state",
      "required" => false,
      "type" => "openbridgeconfiguration_capi_publishing_state",
      "values" => ["DISABLED", "ENABLED", "NOT_INITIALIZED"]
    },
    %{"name" => "cloud_provider", "required" => false, "type" => "string"},
    %{"name" => "cloud_region", "required" => false, "type" => "string"},
    %{"name" => "destination_id", "required" => false, "type" => "string"},
    %{"name" => "endpoint", "required" => false, "type" => "string"},
    %{
      "name" => "event_enrichment_advertiser_state",
      "required" => false,
      "type" => "openbridgeconfiguration_event_enrichment_advertiser_state",
      "values" => ["DISABLED", "ENABLED", "NOT_INITIALIZED"]
    },
    %{
      "name" => "event_enrichment_meta_state",
      "required" => false,
      "type" => "openbridgeconfiguration_event_enrichment_meta_state",
      "values" => ["ALLOWED", "BLOCKED", "NOT_INITIALIZED"]
    },
    %{
      "name" => "event_enrichment_state",
      "required" => false,
      "type" => "openbridgeconfiguration_event_enrichment_state",
      "values" => ["NO", "NOT_INITIALIZED", "YES"]
    },
    %{"name" => "fallback_domain", "required" => false, "type" => "string"},
    %{"name" => "host_business_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "instance_id", "required" => false, "type" => "string"},
    %{"name" => "instance_version", "required" => false, "type" => "string"},
    %{"name" => "is_sgw_instance", "required" => false, "type" => "bool"},
    %{"name" => "is_sgw_pixel_from_meta_pixel", "required" => false, "type" => "bool"},
    %{"name" => "partner_name", "required" => false, "type" => "string"},
    %{"name" => "sgw_account_id", "required" => false, "type" => "string"},
    %{"name" => "sgw_instance_url", "required" => false, "type" => "string"},
    %{"name" => "sgw_pixel_id", "required" => false, "type" => "unsigned int"}
  ])

  finish()
end
