# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OpportunityScoreChangelog do
  use MetaAds.Model

  operation(:get_opportunity_score_history, "GET", "opportunity_score_history", nil, [
    %{"name" => "from_date", "required" => false, "type" => "string"},
    %{"name" => "get_reason", "required" => false, "type" => "bool"},
    %{"name" => "to_date", "required" => false, "type" => "string"}
  ])

  finish()
end
