# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.OwnedDomain do
  use MetaAds.Model

  field("domain_name", "string", [])
  field("id", "string", [])
  field("owner_business", "Business", [])
  field("status", "string", [])
  field("verification_code", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
