# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageRestaurantSpecialties do
  use MetaAds.Model

  field("breakfast", "unsigned int", [])
  field("coffee", "unsigned int", [])
  field("dinner", "unsigned int", [])
  field("drinks", "unsigned int", [])
  field("lunch", "unsigned int", [])

  finish()
end
