# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageUserMessageThreadLabel do
  use MetaAds.Model

  field("id", "string", [])
  field("page_label_name", "string", [])

  operation(:delete_label, "DELETE", "label", nil, [
    %{"name" => "user", "required" => true, "type" => "int"}
  ])

  operation(:create_label, "POST", "label", nil, [
    %{"name" => "user", "required" => true, "type" => "int"}
  ])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
