# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageGetStartedNullstate do
  use MetaAds.Model

  field("cta_title", "string", [])
  field("processed_greeting", "string", [])
  field("responsiveness", "string", [])

  finish()
end
