# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageSettings do
  use MetaAds.Model

  field("setting", "string", [])
  field("value", "Object", [])

  finish()
end
