# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PagePublisher do
  use MetaAds.Model

  field("global_parent_id", "string", [])
  field("icon", "string", [])
  field("id", "string", [])
  field("name", "string", [])
  field("url", "string", [])

  finish()
end
