# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageLocationsBreakdown do
  use MetaAds.Model

  field("location_id", "string", [])
  field("location_name", "string", [])
  field("location_type", "string", [])
  field("num_pages", "int", [])
  field("num_pages_eligible_for_store_visit_reporting", "int", [])
  field("num_unpublished_or_closed_pages", "int", [])
  field("parent_country_code", "string", [])
  field("parent_region_id", "int", [])
  field("parent_region_name", "string", [])

  finish()
end
