# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageRecommendedPostsInfo do
  use MetaAds.Model

  field("recommendation_source", "string", [])
  field("recommended_posts", "list<RecommendedPagePost>", [])

  finish()
end
