# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PagePartnerWithLeadsAccess do
  use MetaAds.Model

  field("can_access_leads", "bool", [])
  field("partner_business", "Business", [])
  field("permitted_tasks", "list<string>", [])

  finish()
end
