# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageLeadsAccessConfig do
  use MetaAds.Model

  field("id", "string", [])
  field("page", "Page", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
