# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageCTSTopic do
  use MetaAds.Model

  field("app_id", "string", [])
  field("frequency", "string", [])
  field("image_hash", "string", [])
  field("image_url", "string", [])
  field("subscriber", "int", [])
  field("title", "string", [])

  finish()
end
