# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageInsightsAsyncExportRun do
  use MetaAds.Model

  field("data_level", "string", [])
  field("filters", "list<Object>", [])
  field("format", "string", [])
  field("gen_report_date", "int", [])
  field("id", "string", [])
  field("report_end_date", "int", [])
  field("report_start_date", "int", [])
  field("sorters", "list<Object>", [])
  field("status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
