# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageOwnedProductCatalog do
  use MetaAds.Model

  operation(:create_owned_product_catalogs, "POST", "owned_product_catalogs", nil, [])
  finish()
end
