# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageUserWithLeadsAccess do
  use MetaAds.Model

  field("active_on_business", "bool", [])
  field("business_role", "string", [])
  field("can_access_leads", "bool", [])
  field("page_role", "string", [])

  finish()
end
