# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageUpcomingChange do
  use MetaAds.Model

  field("change_type", "string", [])
  field("effective_time", "datetime", [])
  field("id", "string", [])
  field("page", "Page", [])
  field("proposal", "PageChangeProposal", [])
  field("timer_status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
