# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PageCategory do
  use MetaAds.Model

  field("api_enum", "string", [])
  field("fb_page_categories", "list<PageCategory>", [])
  field("id", "string", [])
  field("name", "string", [])

  finish()
end
