# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PartnerIntegrationLinked do
  use MetaAds.Model

  field("ads_pixel", "AdsPixel", [])
  field("application", "Application", [])
  field("completed_integration_types", "list<string>", [])
  field("external_business_connection_id", "string", [])
  field("external_id", "string", [])
  field("has_oauth_token", "bool", [])
  field("id", "string", [])
  field("mbe_app_id", "string", [])
  field("mbe_asset_id", "string", [])
  field("mbe_external_business_id", "string", [])
  field("name", "string", [])
  field("offline_conversion_data_set", "OfflineConversionDataSet", [])
  field("page", "Page", [])
  field("partner", "string", [])
  field("product_catalog", "ProductCatalog", [])
  field("setup_status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
