# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PartnerAppAndWelcomeMessageFlowData do
  use MetaAds.Model

  field("flow_data", "list<Object>", [])

  finish()
end
