# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PartnerStudy do
  use MetaAds.Model

  field("additional_info", "string", [])
  field("brand", "string", [])
  field("client_name", "string", [])
  field("emails", "string", [])
  field("id", "string", [])
  field("input_ids", "list<string>", [])
  field("is_export", "bool", [])
  field("lift_study", "AdStudy", [])
  field("location", "string", [])
  field("match_file_ds", "string", [])
  field("name", "string", [])
  field("partner_defined_id", "string", [])
  field("partner_household_graph_dataset_id", "string", [])
  field("status", "string", [])
  field("study_end_date", "datetime", [])
  field("study_start_date", "datetime", [])
  field("study_type", "string", [])
  field("submit_date", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
