# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PartnerAccountLinking do
  use MetaAds.Model

  field("adaccount", "AdAccount", [])
  field("app", "Application", [])
  field("business", "Business", [])
  field("externalidentifier", "string", [])
  field("externalidentifieruri", "string", [])
  field("id", "string", [])
  field("partnername", "string", [])
  field("pixel", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
