# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PartnerCenterExportFile do
  use MetaAds.Model

  field("id", "string", [])
  field("report_ds", "string", [])
  field("url", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
