# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PaymentEnginePayment do
  use MetaAds.Model

  field("actions", "list<Object>", [])
  field("application", "Application", [])
  field("country", "string", [])
  field("created_time", "datetime", [])
  field("disputes", "list<Object>", [])
  field("fraud_status", "string", [])
  field("fulfillment_status", "string", [])
  field("id", "string", [])
  field("is_from_ad", "bool", [])
  field("is_from_page_post", "bool", [])
  field("items", "list<Object>", [])
  field("payout_foreign_exchange_rate", "float", [])
  field("phone_support_eligible", "bool", [])
  field("platform", "string", [])
  field("refundable_amount", "CurrencyAmount", [])
  field("request_id", "string", [])
  field("tax", "string", [])
  field("tax_country", "string", [])
  field("test", "unsigned int", [])
  field("user", "User", [])

  operation(:create_dispute, "POST", "dispute", nil, [
    %{
      "name" => "reason",
      "required" => true,
      "type" => "paymentenginepaymentdispute_reason_enum_param",
      "values" => ["BANNED_USER", "DENIED_REFUND", "GRANTED_REPLACEMENT_ITEM"]
    }
  ])

  operation(:create_refunds, "POST", "refunds", nil, [
    %{"name" => "amount", "required" => true, "type" => "float"},
    %{"name" => "currency", "required" => true, "type" => "string"},
    %{
      "name" => "reason",
      "required" => false,
      "type" => "paymentenginepaymentrefunds_reason_enum_param",
      "values" => ["CUSTOMER_SERVICE", "FRIENDLY_FRAUD", "MALICIOUS_FRAUD"]
    }
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
