# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Persona do
  use MetaAds.Model

  field("id", "string", [])
  field("name", "string", [])
  field("profile_picture_url", "string", [])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
