# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PhotoMetadata do
  use MetaAds.Model

  field("camera_make", "string", [])
  field("camera_model", "string", [])
  field("datetime_modified", "datetime", [])
  field("datetime_taken", "datetime", [])
  field("exposure", "string", [])
  field("focal_length", "string", [])
  field("fstop", "string", [])
  field("iso_speed", "int", [])
  field("offline_id", "string", [])
  field("orientation", "string", [])
  field("original_height", "string", [])
  field("original_width", "string", [])

  finish()
end
