# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Photo do
  use MetaAds.Model

  field("album", "Album", [])
  field("alt_text", "string", [])
  field("alt_text_custom", "string", [])
  field("backdated_time", "datetime", [])
  field("backdated_time_granularity", "string", [])
  field("can_backdate", "bool", [])
  field("can_delete", "bool", [])
  field("can_tag", "bool", [])
  field("created_time", "datetime", [])
  field("event", "Event", [])
  field("from", "Object", [])
  field("height", "unsigned int", [])
  field("icon", "string", [])
  field("id", "string", [])
  field("images", "list<PlatformImageSource>", [])
  field("link", "string", [])
  field("name", "string", [])
  field("name_tags", "list<EntityAtTextRange>", [])
  field("page_story_id", "string", [])
  field("picture", "string", [])
  field("place", "Place", [])
  field("position", "unsigned int", [])
  field("source", "string", [])
  field("target", "Profile", [])
  field("updated_time", "datetime", [])
  field("webp_images", "list<PlatformImageSource>", [])
  field("width", "unsigned int", [])

  operation(:get_comments, "GET", "comments", nil, [
    %{
      "name" => "filter",
      "required" => false,
      "type" => "photocomments_filter_enum_param",
      "values" => ["stream", "toplevel"]
    },
    %{
      "name" => "live_filter",
      "required" => false,
      "type" => "photocomments_live_filter_enum_param",
      "values" => ["filter_low_quality", "no_filter"]
    },
    %{
      "name" => "order",
      "required" => false,
      "type" => "photocomments_order_enum_param",
      "values" => ["chronological", "reverse_chronological"]
    },
    %{"name" => "since", "required" => false, "type" => "datetime"}
  ])

  operation(:create_comments, "POST", "comments", nil, [
    %{"name" => "attachment_id", "required" => false, "type" => "string"},
    %{"name" => "attachment_share_url", "required" => false, "type" => "string"},
    %{"name" => "attachment_url", "required" => false, "type" => "string"},
    %{
      "name" => "comment_privacy_value",
      "required" => false,
      "type" => "photocomments_comment_privacy_value_enum_param",
      "values" => [
        "DECLINED_BY_ADMIN_ASSISTANT",
        "DEFAULT_PRIVACY",
        "FRIENDS_AND_POST_OWNER",
        "FRIENDS_ONLY",
        "GRAPHQL_MULTIPLE_VALUE_HACK_DO_NOT_USE",
        "OWNER_OR_COMMENTER",
        "PENDING_APPROVAL",
        "PRIVATE_CONVERSATION_PARTICIPANTS_ONLY",
        "REMOVED_BY_ADMIN_ASSISTANT",
        "SIDE_CONVERSATION",
        "SIDE_CONVERSATION_AND_POST_OWNER",
        "SPOTLIGHT_TAB"
      ]
    },
    %{"name" => "facepile_mentioned_ids", "required" => false, "type" => "list<string>"},
    %{"name" => "feedback_source", "required" => false, "type" => "string"},
    %{"name" => "is_offline", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "object_id", "required" => false, "type" => "string"},
    %{"name" => "parent_comment_id", "required" => false, "type" => "Object"},
    %{"name" => "text", "required" => false, "type" => "string"},
    %{"name" => "tracking", "required" => false, "type" => "string"}
  ])

  operation(:get_insights, "GET", "insights", nil, [
    %{
      "name" => "date_preset",
      "required" => false,
      "type" => "photoinsights_date_preset_enum_param",
      "values" => [
        "data_maximum",
        "last_14d",
        "last_28d",
        "last_30d",
        "last_3d",
        "last_7d",
        "last_90d",
        "last_month",
        "last_quarter",
        "last_week_mon_sun",
        "last_week_sun_sat",
        "last_year",
        "maximum",
        "this_month",
        "this_quarter",
        "this_week_mon_today",
        "this_week_sun_today",
        "this_year",
        "today",
        "yesterday"
      ]
    },
    %{"name" => "metric", "required" => false, "type" => "list<Object>"},
    %{
      "name" => "period",
      "required" => false,
      "type" => "photoinsights_period_enum_param",
      "values" => ["day", "days_28", "lifetime", "month", "total_over_range", "week"]
    },
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{"name" => "until", "required" => false, "type" => "datetime"}
  ])

  operation(:get_likes, "GET", "likes", nil, [])

  operation(:create_likes, "POST", "likes", nil, [
    %{"name" => "attribution_id_v2", "required" => false, "type" => "string"},
    %{"name" => "feedback_source", "required" => false, "type" => "string"},
    %{"name" => "nectar_module", "required" => false, "type" => "string"},
    %{"name" => "notify", "required" => false, "type" => "bool"},
    %{"name" => "tracking", "required" => false, "type" => "string"}
  ])

  operation(:get_sponsor_tags, "GET", "sponsor_tags", nil, [])
  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
