# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PlaceTag do
  use MetaAds.Model

  field("created_time", "datetime", [])
  field("id", "string", [])
  field("place", "Page", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
