# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PlaceTopic do
  use MetaAds.Model

  field("count", "unsigned int", [])
  field("has_children", "bool", [])
  field("icon_url", "string", [])
  field("id", "string", [])
  field("name", "string", [])
  field("plural_name", "string", [])
  field("top_subtopic_names", "list<string>", [])

  operation(:get, "GET", "", nil, [
    %{
      "name" => "icon_size",
      "required" => false,
      "type" => "placetopic_icon_size",
      "values" => ["24", "36", "48", "72"]
    }
  ])

  finish()
end
