# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Placement do
  use MetaAds.Model

  field("audience_network_positions", "list<string>", [])
  field("device_platforms", "list<Placement_device_platforms>", [])
  field("effective_audience_network_positions", "list<string>", [])
  field("effective_device_platforms", "list<Placement_effective_device_platforms>", [])
  field("effective_facebook_positions", "list<string>", [])
  field("effective_instagram_positions", "list<string>", [])
  field("effective_messenger_positions", "list<string>", [])
  field("effective_oculus_positions", "list<string>", [])
  field("effective_publisher_platforms", "list<string>", [])
  field("effective_threads_positions", "list<string>", [])
  field("effective_whatsapp_positions", "list<string>", [])
  field("facebook_positions", "list<string>", [])
  field("instagram_positions", "list<string>", [])
  field("messenger_positions", "list<string>", [])
  field("oculus_positions", "list<string>", [])
  field("publisher_platforms", "list<string>", [])
  field("threads_positions", "list<string>", [])
  field("whatsapp_positions", "list<string>", [])

  finish()
end
