# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Place do
  use MetaAds.Model

  field("id", "string", [])
  field("location", "Location", [])
  field("name", "string", [])
  field("overall_rating", "float", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
