# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PreapprovalReview do
  use MetaAds.Model

  field("comp_type", "string", [])
  field("crow_component_id", "int", [])
  field("is_human_reviewed", "bool", [])
  field("is_reviewed", "bool", [])
  field("policy_info", "list<map<string, Object>>", [])

  finish()
end
