# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PrivateLiftStudyInstance do
  use MetaAds.Model

  field("breakdown_key", "string", [])
  field("created_time", "datetime", [])
  field("feature_list", "list<string>", [])
  field("id", "string", [])
  field("issuer_certificate", "string", [])
  field("latest_status_update_time", "datetime", [])
  field("run_id", "string", [])
  field("server_hostnames", "list<string>", [])
  field("server_ips", "list<string>", [])
  field("status", "string", [])
  field("tier", "string", [])

  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{
      "name" => "operation",
      "required" => false,
      "type" => "privateliftstudyinstance_operation",
      "values" => ["AGGREGATE", "CANCEL", "COMPUTE", "ID_MATCH", "NEXT", "NONE"]
    },
    %{"name" => "run_id", "required" => false, "type" => "string"}
  ])

  finish()
end
