# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Privacy do
  use MetaAds.Model

  field("allow", "string", [])
  field("deny", "string", [])
  field("description", "string", [])
  field("friends", "string", [])
  field("networks", "string", [])
  field("value", "string", [])

  finish()
end
