# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PrivacyOption do
  use MetaAds.Model

  field("description", "string", [])
  field("icon_src", "string", [])
  field("id", "string", [])
  field("is_currently_selected", "bool", [])
  field("type", "string", [])
  field("user_id", "string", [])

  finish()
end
