# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductGroupGet do
  use MetaAds.Model

  field("id", "int", [])
  field("mini_shops_product_sets_count", "int", [])
  field("product_catalog", "object", [])
  field("products", "object", [])
  field("representative_item_id", "string", [])
  field("retailer_id", "string", [])
  field("variants", "list<object>", [])

  finish()
end
