# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogPost do
  use MetaAds.Model

  field("__firstOneOf", "object", [])
  field("__secondOneOf", "object", [])

  finish()
end
