# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductItemLocalInfoLatLongShape do
  use MetaAds.Model

  field("latitude", "float", [])
  field("longitude", "float", [])

  finish()
end
