# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductSetTaxonCategory do
  use MetaAds.Model

  field("category_id", "int", [])
  field("category_name", "string", [])
  field("image_url", "string", [])

  finish()
end
