# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductItemLandingPageData do
  use MetaAds.Model

  field("availability", "ProductItemLandingPageData_availability", [
    "available for order",
    "discontinued",
    "in stock",
    "mark_as_expired",
    "mark_as_sold",
    "out of stock",
    "pending",
    "preorder"
  ])

  finish()
end
