# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductFeedUploadProgress do
  use MetaAds.Model

  field("pos", "int", [])
  field("size", "int", [])
  field("step", "string", [])
  field("unit", "string", [])
  field("updated_time", "datetime", [])

  finish()
end
