# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductSetHotels do
  use MetaAds.Model

  operation(:get_hotels, "GET", "hotels", nil, [
    %{"name" => "after", "required" => false, "type" => "string"},
    %{"name" => "before", "required" => false, "type" => "string"},
    %{
      "name" => "display_format",
      "required" => false,
      "type" => "ProductSetHotelsGet_display_format_enum_param",
      "values" => ["CAROUSEL_AD", "SHOPS_PDP", "SINGLE_AD"]
    },
    %{"name" => "limit", "required" => false, "type" => "int"},
    %{"name" => "summary", "required" => false, "type" => "bool"}
  ])

  finish()
end
