# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductItemVideoData do
  use MetaAds.Model

  field("tags", "list<string>", [])
  field("url", "string", [])

  finish()
end
