# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductFeedSchedule do
  use MetaAds.Model

  field("day_of_month", "unsigned int", [])
  field("day_of_week", "string", [])
  field("hour", "unsigned int", [])
  field("id", "string", [])
  field("interval", "ProductFeedSchedule_interval", ["DAILY", "HOURLY", "MONTHLY", "WEEKLY"])
  field("interval_count", "unsigned int", [])
  field("minute", "unsigned int", [])
  field("timezone", "string", [])
  field("url", "string", [])
  field("username", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
