# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductItemInsights do
  use MetaAds.Model

  field("ad_click_count", "int", [])
  field("ad_impression_count", "int", [])
  field("add_to_cart_count", "int", [])
  field("purchase_count", "int", [])
  field("view_content_count", "int", [])

  finish()
end
