# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductItemShipping do
  use MetaAds.Model

  field("shipping_country", "string", [])
  field("shipping_price_currency", "string", [])
  field("shipping_price_value", "float", [])
  field("shipping_region", "string", [])
  field("shipping_service", "string", [])

  finish()
end
