# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogMediaTitle do
  use MetaAds.Model

  operation(:delete_delete, "DELETE", "", nil, [])
  finish()
end
