# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogCheckMarketplacePartnerSellersStatus do
  use MetaAds.Model

  field("sample_errors", "list<Object>", [])
  field("session_id", "string", [])
  field("status", "string", [])

  finish()
end
