# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductFeedUploadGet do
  use MetaAds.Model

  field("end_time", "mixed", [])
  field("error_count", "int", [])
  field("error_report", "object", [])
  field("errors", "object", [])
  field("filename", "string", [])
  field("id", "int", [])

  field("input_method", "ProductFeedUploadGet_input_method", [
    "GOOGLE_SHEETS_FETCH",
    "MANUAL_UPLOAD",
    "REUPLOAD_EXISTING",
    "REUPLOAD_LAST_FILE",
    "SERVER_FETCH",
    "USER_INITIATED_SERVER_FETCH"
  ])

  field("num_deleted_items", "int", [])
  field("num_detected_items", "int", [])
  field("num_invalid_items", "int", [])
  field("num_persisted_items", "int", [])
  field("progresses", "object", [])
  field("start_time", "mixed", [])
  field("upload_complete", "bool", [])
  field("url", "string", [])
  field("warning_count", "int", [])

  finish()
end
