# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogHotelsItem do
  use MetaAds.Model

  operation(:get, "GET", "", nil, [
    %{
      "name" => "display_format",
      "required" => false,
      "type" => "ProductCatalogHotelsItemGet_display_format_enum_param",
      "values" => ["CAROUSEL_AD", "SHOPS_PDP", "SINGLE_AD"]
    }
  ])

  finish()
end
