# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductDeliveryPreference do
  use MetaAds.Model

  field("ad_object_id", "string", [])
  field("id", "string", [])
  field("product_priority", "string", [])
  field("product_priority_category", "list<string>", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
