# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogAppsAndSoftwareItem do
  use MetaAds.Model

  operation(:delete, "DELETE", "", nil, [])
  finish()
end
