# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductFeedRuleSuggestion do
  use MetaAds.Model

  field("attribute", "string", [])
  field("params", "list<map<string, string>>", [])
  field("type", "string", [])

  finish()
end
