# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogCheckBatchRequestStatusGet do
  use MetaAds.Model

  field("data", "list<object>", [])
  field("paging", "object", [])

  finish()
end
