# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductFeedUploadError do
  use MetaAds.Model

  field("affected_surfaces", "list<ProductFeedUploadError_affected_surfaces>", [])
  field("description", "string", [])
  field("error_type", "string", [])
  field("id", "string", [])
  field("severity", "ProductFeedUploadError_severity", ["fatal", "warning"])
  field("summary", "string", [])
  field("total_count", "unsigned int", [])

  operation(:get_samples, "GET", "samples", nil, [])
  operation(:get_suggested_rules, "GET", "suggested_rules", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
