# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductVariant do
  use MetaAds.Model

  field("label", "string", [])
  field("options", "list<string>", [])
  field("product_field", "string", [])

  finish()
end
