# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductItemOffer do
  use MetaAds.Model

  field("availability_area", "list<Object>", [])
  field("availability_radius", "float", [])
  field("id", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
