# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductItemImporterAddress do
  use MetaAds.Model

  field("city", "string", [])
  field("country", "string", [])
  field("postal_code", "string", [])
  field("region", "string", [])
  field("street1", "string", [])
  field("street2", "string", [])

  finish()
end
