# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogLocalizationSettings do
  use MetaAds.Model

  field("default_country", "string", [])
  field("default_language", "string", [])
  field("id", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
