# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogArticlesAndPublicationsPost do
  use MetaAds.Model

  field("id", "int", [])

  finish()
end
