# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductFeedUploadErrorSample do
  use MetaAds.Model

  field("id", "string", [])
  field("retailer_id", "string", [])
  field("row_number", "int", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
