# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductItemSubscriptionInfo do
  use MetaAds.Model

  field("is_subscribable", "bool", [])
  field("subscription_billing_period", "unsigned int", [])
  field("subscription_billing_type", "string", [])

  finish()
end
