# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogItemsBatch do
  use MetaAds.Model

  operation(:create_items_batch, "POST", "items_batch", nil, [])
  finish()
end
