# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogDataSource do
  use MetaAds.Model

  field("app_id", "string", [])
  field("id", "string", [])
  field("ingestion_source_type", "string", [])
  field("name", "string", [])
  field("upload_type", "string", [])

  finish()
end
