# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductImage do
  use MetaAds.Model

  field("height", "int", [])
  field("id", "string", [])
  field("image_url", "string", [])
  field("width", "int", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
