# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogProfessionalServicesItem do
  use MetaAds.Model

  operation(:update, "PUT", "", nil, [])
  finish()
end
