# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogDiagnosticGroup do
  use MetaAds.Model

  field("affected_channels", "list<string>", [])

  field("affected_entity", "ProductCatalogDiagnosticGroup_affected_entity", [
    "product_catalog",
    "product_event",
    "product_item",
    "product_set"
  ])

  field("affected_features", "list<ProductCatalogDiagnosticGroup_affected_features>", [])
  field("diagnostics", "list<Object>", [])
  field("error_code", "int", [])
  field("number_of_affected_entities", "int", [])
  field("number_of_affected_items", "int", [])
  field("severity", "ProductCatalogDiagnosticGroup_severity", ["MUST_FIX", "OPPORTUNITY"])
  field("subtitle", "string", [])
  field("title", "string", [])

  field("type", "ProductCatalogDiagnosticGroup_type", [
    "AR_VISIBILITY_ISSUES",
    "ATTRIBUTES_INVALID",
    "ATTRIBUTES_MISSING",
    "CATEGORY",
    "CHECKOUT",
    "DA_VISIBILITY_ISSUES",
    "EVENT_SOURCE_ISSUES",
    "IMAGE_QUALITY",
    "LOW_QUALITY_TITLE_AND_DESCRIPTION",
    "POLICY_VIOLATION",
    "SHOPS_VISIBILITY_ISSUES"
  ])

  finish()
end
