# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductFeedUploadErrorReport do
  use MetaAds.Model

  field("file_handle", "string", [])
  field("report_status", "string", [])

  finish()
end
