# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductVisualVariant do
  use MetaAds.Model

  field("items", "list<ProductItem>", [])
  field("unique_key", "string", [])

  finish()
end
