# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductFeedRules do
  use MetaAds.Model

  operation(:get_rules, "GET", "rules", nil, [])
  finish()
end
