# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductEventStat do
  use MetaAds.Model

  field("date_start", "string", [])
  field("date_stop", "string", [])

  field("device_type", "ProductEventStat_device_type", [
    "desktop",
    "mobile_android_phone",
    "mobile_android_tablet",
    "mobile_ipad",
    "mobile_iphone",
    "mobile_ipod",
    "mobile_phone",
    "mobile_tablet",
    "mobile_windows_phone",
    "unknown"
  ])

  field("event", "ProductEventStat_event", [
    "AddToCart",
    "AddToWishlist",
    "InitiateCheckout",
    "Lead",
    "Purchase",
    "Search",
    "Subscribe",
    "ViewContent"
  ])

  field("event_source", "ExternalEventSource", [])
  field("total_content_ids_matched_other_catalogs", "int", [])
  field("total_matched_content_ids", "int", [])
  field("total_unmatched_content_ids", "int", [])
  field("unique_content_ids_matched_other_catalogs", "int", [])
  field("unique_matched_content_ids", "int", [])
  field("unique_unmatched_content_ids", "int", [])

  finish()
end
