# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogItemsBatchPost do
  use MetaAds.Model

  field("handles", "list<string>", [])
  field("validation_status", "list<object>", [])

  finish()
end
