# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogPricingVariablesBatch do
  use MetaAds.Model

  field("errors", "list<Object>", [])
  field("errors_total_count", "int", [])
  field("handle", "string", [])
  field("status", "string", [])

  finish()
end
