# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogActivities do
  use MetaAds.Model

  operation(:create_activities, "POST", "activities", nil, [])
  finish()
end
