# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ProductCatalogCheckBatchRequestStatus do
  use MetaAds.Model

  operation(:get_check_batch_request_status, "GET", "check_batch_request_status", nil, [
    %{"name" => "after", "required" => false, "type" => "string"},
    %{"name" => "before", "required" => false, "type" => "string"},
    %{
      "name" => "error_priority",
      "required" => false,
      "type" => "ProductCatalogCheckBatchRequestStatusGet_error_priority_enum_param",
      "values" => ["HIGH", "LOW", "MEDIUM"]
    },
    %{"name" => "fields", "required" => false, "type" => "string"},
    %{"name" => "handle", "required" => true, "type" => "string"},
    %{"name" => "limit", "required" => false, "type" => "int"},
    %{"name" => "load_ids_of_invalid_requests", "required" => false, "type" => "bool"}
  ])

  finish()
end
