# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PublisherBlockList do
  use MetaAds.Model

  field("app_publishers", "list<AppPublisher>", [])
  field("business_owner_id", "string", [])
  field("id", "string", [])
  field("is_auto_blocking_on", "bool", [])
  field("is_eligible_at_campaign_level", "bool", [])
  field("last_update_time", "datetime", [])
  field("last_update_user", "string", [])
  field("name", "string", [])
  field("owner_ad_account_id", "string", [])
  field("web_publishers", "list<WebPublisher>", [])

  operation(:create_append_publisher_urls, "POST", "append_publisher_urls", nil, [
    %{"name" => "publisher_urls", "required" => true, "type" => "list<string>"}
  ])

  operation(:get_paged_web_publishers, "GET", "paged_web_publishers", nil, [
    %{"name" => "draft_id", "required" => false, "type" => "string"}
  ])

  operation(:delete, "DELETE", "", nil, [])

  operation(:get, "GET", "", nil, [
    %{"name" => "account_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "business_id", "required" => false, "type" => "string"},
    %{"name" => "draft_id", "required" => false, "type" => "string"}
  ])

  operation(:create, "POST", "", nil, [
    %{"name" => "spec", "required" => true, "type" => "Object"}
  ])

  finish()
end
