# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.PublisherDeliveryReport do
  use MetaAds.Model

  field("content_types", "list<string>", [])
  field("estimated_impressions", "unsigned int", [])
  field("name", "string", [])
  field("status", "string", [])
  field("url", "string", [])

  finish()
end
