# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ReachFrequencyCurveUpperConfidenceRange do
  use MetaAds.Model

  field("impression_upper", "list<int>", [])
  field("num_points", "unsigned int", [])
  field("reach", "list<int>", [])
  field("reach_upper", "list<int>", [])
  field("uniq_video_views_2s_upper", "list<int>", [])
  field("video_views_2s_upper", "list<int>", [])

  finish()
end
