# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ReachFrequencySpec do
  use MetaAds.Model

  field("countries", "list<string>", [])
  field("default_creation_data", "Object", [])
  field("global_io_max_campaign_duration", "unsigned int", [])
  field("max_campaign_duration", "Object", [])
  field("max_days_to_finish", "Object", [])
  field("max_pause_without_prediction_rerun", "Object", [])
  field("min_campaign_duration", "Object", [])
  field("min_reach_limits", "Object", [])

  finish()
end
