# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ReachFrequencyCurveLowerConfidenceRange do
  use MetaAds.Model

  field("impression_lower", "list<int>", [])
  field("num_points", "unsigned int", [])
  field("reach", "list<int>", [])
  field("reach_lower", "list<int>", [])
  field("uniq_video_views_2s_lower", "list<int>", [])
  field("video_views_2s_lower", "list<int>", [])

  finish()
end
