# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ReachFrequencyActivity do
  use MetaAds.Model

  field("account_id", "string", [])
  field("campaign_active", "bool", [])
  field("campaign_started", "bool", [])
  field("creative_uploaded", "bool", [])
  field("io_approved", "bool", [])
  field("sf_link", "string", [])

  finish()
end
