# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ReachFrequencyAdFormat do
  use MetaAds.Model

  field("details", "Object", [])
  field("type", "string", [])

  finish()
end
