# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.RecommendedPagePost do
  use MetaAds.Model

  field("intent_score", "float", [])
  field("is_ig_media", "bool", [])
  field("post_id", "string", [])

  finish()
end
