# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Recommendation do
  use MetaAds.Model

  field("created_time", "datetime", [])
  field("has_rating", "bool", [])
  field("has_review", "bool", [])
  field("open_graph_story", "Object", [])
  field("rating", "int", [])
  field("recommendation_type", "string", [])
  field("review_text", "string", [])
  field("reviewer", "User", [])

  finish()
end
