# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.RepeatReachState do
  use MetaAds.Model

  field("current_saturation_level", "float", [])
  field("forecasted_saturation_level", "float", [])
  field("high_saturation_threshold", "float", [])
  field("should_display_cpr", "bool", [])

  finish()
end
