# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.RevSharePolicy do
  use MetaAds.Model

  field("policy_id", "string", [])
  field("policy_name", "string", [])

  finish()
end
