# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.RightsManagerDataExport do
  use MetaAds.Model

  field("download_uri", "string", [])
  field("export_scope", "string", [])
  field("id", "string", [])
  field("name", "string", [])
  field("record_type", "string", [])
  field("time_range_end", "datetime", [])
  field("time_range_start", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
