# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Robot do
  use MetaAds.Model

  field("bringup_vars", "list<map<string, string>>", [])
  field("configurations", "list<map<string, string>>", [])
  field("data_center", "string", [])
  field("fw_image", "string", [])
  field("id", "string", [])
  field("init_pos", "list<map<string, float>>", [])
  field("last_pos", "list<map<string, float>>", [])
  field("meetup_link_hash", "string", [])
  field("release_image", "string", [])
  field("robot_notes", "string", [])
  field("suite", "string", [])
  field("target_fw_image", "string", [])
  field("target_fw_image_uri", "string", [])
  field("target_map_image_uri", "string", [])
  field("target_os_image_uri", "string", [])
  field("target_release_image", "string", [])
  field("target_sw_image_uri", "string", [])
  field("user", "User", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
