# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.RTBDynamicPostComments do
  use MetaAds.Model

  operation(:create_comments, "POST", "comments", nil, [])
  finish()
end
