# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.SavedMessageResponse do
  use MetaAds.Model

  field("id", "string", [])
  field("image", "string", [])
  field("is_enabled", "bool", [])
  field("message", "string", [])
  field("title", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
