# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ShadowIGUserCollaborationInvites do
  use MetaAds.Model

  field("caption", "string", [])
  field("media_id", "string", [])
  field("media_owner_username", "string", [])
  field("media_url", "string", [])

  finish()
end
