# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ShadowIGMediaCollaborators do
  use MetaAds.Model

  field("id", "string", [])
  field("invite_status", "string", [])
  field("username", "string", [])

  finish()
end
