# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Shop do
  use MetaAds.Model

  field("commerce_merchant_settings", "CommerceMerchantSettings", [])
  field("fb_sales_channel", "Object", [])
  field("id", "string", [])
  field("ig_sales_channel", "Object", [])
  field("shop_status", "string", [])
  field("workspace", "Object", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
