# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.SignalsIWLExtractor do
  use MetaAds.Model

  field("domain_uri", "string", [])
  field("event_type", "string", [])
  field("extractor_config", "Object", [])
  field("extractor_type", "string", [])
  field("id", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
