# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.StreamFilter do
  use MetaAds.Model

  field("filter_key", "string", [])
  field("name", "string", [])
  field("type", "string", [])

  finish()
end
