# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.SystemUser do
  use MetaAds.Model

  field("created_by", "User", [])
  field("created_time", "datetime", [])
  field("finance_permission", "string", [])
  field("id", "string", [])
  field("ip_permission", "string", [])
  field("name", "string", [])

  operation(:get_assigned_ad_accounts, "GET", "assigned_ad_accounts", nil, [])

  operation(:get_assigned_business_asset_groups, "GET", "assigned_business_asset_groups", nil, [
    %{"name" => "contained_asset_id", "required" => false, "type" => "string"}
  ])

  operation(:get_assigned_pages, "GET", "assigned_pages", nil, [
    %{"name" => "pages", "required" => false, "type" => "list<unsigned int>"}
  ])

  operation(:get_assigned_product_catalogs, "GET", "assigned_product_catalogs", nil, [])

  operation(
    :get_assigned_whatsapp_business_accounts,
    "GET",
    "assigned_whatsapp_business_accounts",
    nil,
    []
  )

  operation(:get, "GET", "", nil, [])
  finish()
end
