# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingGeoLocationPlace do
  use MetaAds.Model

  field("country", "string", [])
  field("distance_unit", "string", [])
  field("key", "string", [])
  field("latitude", "float", [])
  field("longitude", "float", [])
  field("name", "string", [])
  field("primary_city_id", "int", [])
  field("radius", "float", [])
  field("region_id", "int", [])

  finish()
end
