# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingGeoLocationPoliticalDistrict do
  use MetaAds.Model

  field("country", "string", [])
  field("key", "string", [])
  field("name", "string", [])
  field("political_district", "string", [])

  finish()
end
