# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingRelaxation do
  use MetaAds.Model

  field("custom_audience", "unsigned int", [])
  field("lookalike", "unsigned int", [])

  finish()
end
