# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingGeoLocation do
  use MetaAds.Model

  field("cities", "list<TargetingGeoLocationCity>", [])
  field("countries", "list<string>", [])
  field("country_groups", "list<string>", [])
  field("custom_locations", "list<TargetingGeoLocationCustomLocation>", [])
  field("electoral_districts", "list<TargetingGeoLocationElectoralDistrict>", [])
  field("geo_markets", "list<TargetingGeoLocationMarket>", [])
  field("large_geo_areas", "list<TargetingGeoLocationGeoEntities>", [])
  field("location_cluster_ids", "list<TargetingGeoLocationLocationCluster>", [])
  field("location_types", "list<string>", [])
  field("medium_geo_areas", "list<TargetingGeoLocationGeoEntities>", [])
  field("metro_areas", "list<TargetingGeoLocationGeoEntities>", [])
  field("neighborhoods", "list<TargetingGeoLocationGeoEntities>", [])
  field("places", "list<TargetingGeoLocationPlace>", [])
  field("political_districts", "list<TargetingGeoLocationPoliticalDistrict>", [])
  field("regions", "list<TargetingGeoLocationRegion>", [])
  field("small_geo_areas", "list<TargetingGeoLocationGeoEntities>", [])
  field("subcities", "list<TargetingGeoLocationGeoEntities>", [])
  field("subneighborhoods", "list<TargetingGeoLocationGeoEntities>", [])
  field("zips", "list<TargetingGeoLocationZip>", [])

  finish()
end
