# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingProspectingAudience do
  use MetaAds.Model

  field("sources", "list<Object>", [])

  finish()
end
