# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingGeoLocationZip do
  use MetaAds.Model

  field("country", "string", [])
  field("key", "string", [])
  field("name", "string", [])
  field("primary_city_id", "int", [])
  field("region_id", "int", [])

  finish()
end
