# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingAutomation do
  use MetaAds.Model

  field("advantage_audience", "unsigned int", [])
  field("creative_audience_pairing", "unsigned int", [])
  field("individual_setting", "Object", [])
  field("shared_audiences", "unsigned int", [])
  field("value_expression", "unsigned int", [])

  finish()
end
