# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingGeoLocationGeoEntities do
  use MetaAds.Model

  field("country", "string", [])
  field("key", "string", [])
  field("name", "string", [])
  field("region", "string", [])
  field("region_id", "string", [])

  finish()
end
