# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingProductAudienceSpec do
  use MetaAds.Model

  field("exclusions", "list<TargetingProductAudienceSubSpec>", [])
  field("inclusions", "list<TargetingProductAudienceSubSpec>", [])
  field("product_set_id", "string", [])

  finish()
end
