# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingGeoLocationElectoralDistrict do
  use MetaAds.Model

  field("country", "string", [])
  field("deprecation_code", "string", [])
  field("electoral_district", "string", [])
  field("key", "string", [])
  field("name", "string", [])

  finish()
end
