# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingSentenceLine do
  use MetaAds.Model

  field("id", "string", [])
  field("params", "Targeting", [])
  field("targetingsentencelines", "list", [])

  finish()
end
