# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TargetingDynamicRule do
  use MetaAds.Model

  field("action.type", "string", [])
  field("ad_group_id", "string", [])
  field("campaign_group_id", "string", [])
  field("campaign_id", "string", [])
  field("impression_count", "string", [])
  field("page_id", "string", [])
  field("post", "string", [])
  field("retention_seconds", "string", [])

  finish()
end
