# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ThirdPartyPartnerPanelRequest do
  use MetaAds.Model

  field("adentities_ids", "list<string>", [])
  field("country", "string", [])
  field("created_time", "datetime", [])
  field("description", "string", [])
  field("id", "string", [])
  field("modified_time", "datetime", [])
  field("owner_instance_id", "string", [])
  field("owner_panel_id", "string", [])
  field("owner_panel_name", "string", [])

  field("status", "ThirdPartyPartnerPanelRequest_status", [
    "CREATED",
    "FAILURE",
    "IN_PROGRESS",
    "SCHEDULED",
    "SUCCESS"
  ])

  field("study_end_time", "datetime", [])
  field("study_start_time", "datetime", [])

  field("study_type", "ThirdPartyPartnerPanelRequest_study_type", [
    "BRAND_LIFT",
    "PANEL_SALES_ATTRIBUTION",
    "REACH"
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
