# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ThirdPartyPartnerPanelScheduled do
  use MetaAds.Model

  field("adentities_ids", "list<string>", [])
  field("cadence", "string", [])
  field("country", "string", [])
  field("created_time", "datetime", [])
  field("description", "string", [])
  field("end_time", "datetime", [])
  field("id", "string", [])
  field("modified_time", "datetime", [])
  field("owner_instance_id", "string", [])
  field("owner_panel_id", "string", [])
  field("owner_panel_name", "string", [])
  field("start_time", "datetime", [])

  field("status", "ThirdPartyPartnerPanelScheduled_status", [
    "CANCELLED",
    "CREATED",
    "FINISHED",
    "ONGOING"
  ])

  field("study_type", "ThirdPartyPartnerPanelScheduled_study_type", [
    "BRAND_LIFT",
    "PANEL_SALES_ATTRIBUTION",
    "REACH"
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
