# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.ThirdPartyPartnerLiftRequest do
  use MetaAds.Model

  field("ad_entities", "list<string>", [])
  field("country", "string", [])
  field("created_time", "datetime", [])
  field("description", "string", [])
  field("holdout_size", "float", [])
  field("id", "string", [])
  field("legacy_ads_data_partner_id", "string", [])
  field("legacy_ads_data_partner_name", "string", [])
  field("modified_time", "datetime", [])
  field("owner_instance_id", "string", [])
  field("partner_household_graph_dataset_id", "string", [])
  field("region", "string", [])

  field("status", "ThirdPartyPartnerLiftRequest_status", [
    "CREATED",
    "FAILURE",
    "IN_PROGRESS",
    "SCHEDULED",
    "SUCCESS"
  ])

  field("study_cells", "list<string>", [])
  field("study_end_time", "datetime", [])
  field("study_start_time", "datetime", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
