# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TimezoneOffset do
  use MetaAds.Model

  field("abbr", "string", [])
  field("isdst", "bool", [])
  field("offset", "int", [])
  field("time", "string", [])
  field("ts", "unsigned int", [])

  finish()
end
