# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.TransactableItem do
  use MetaAds.Model

  field("action_title", "string", [])
  field("applinks", "CatalogItemAppLinks", [])
  field("currency", "string", [])
  field("description", "string", [])
  field("duration_time", "unsigned int", [])
  field("duration_type", "string", [])
  field("id", "string", [])

  field("image_fetch_status", "TransactableItem_image_fetch_status", [
    "DIRECT_UPLOAD",
    "FETCHED",
    "FETCH_FAILED",
    "NO_STATUS",
    "OUTDATED",
    "PARTIAL_FETCH"
  ])

  field("images", "list<string>", [])
  field("order_index", "unsigned int", [])
  field("price", "string", [])
  field("price_type", "string", [])
  field("sanitized_images", "list<string>", [])
  field("session_type", "string", [])
  field("time_padding_after_end", "unsigned int", [])
  field("title", "string", [])
  field("transactable_item_id", "string", [])
  field("url", "string", [])
  field("visibility", "TransactableItem_visibility", ["PUBLISHED", "STAGING"])

  operation(:get_channels_to_integrity_status, "GET", "channels_to_integrity_status", nil, [])

  operation(:get_override_details, "GET", "override_details", nil, [
    %{"name" => "keys", "required" => false, "type" => "list<string>"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "transactableitemoverride_details_type_enum_param",
      "values" => ["COUNTRY", "LANGUAGE", "LANGUAGE_AND_COUNTRY"]
    }
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
