# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UnifiedThread do
  use MetaAds.Model

  field("can_reply", "bool", [])
  field("folder", "string", [])
  field("former_participants", "Object", [])
  field("id", "string", [])
  field("is_owner", "bool", [])
  field("is_subscribed", "bool", [])
  field("link", "string", [])
  field("linked_group", "Group", [])
  field("message_count", "int", [])
  field("name", "string", [])
  field("participants", "Object", [])
  field("scoped_thread_key", "string", [])
  field("senders", "Object", [])
  field("snippet", "string", [])
  field("unread_count", "int", [])
  field("updated_time", "datetime", [])
  field("wallpaper", "string", [])

  operation(:get_messages, "GET", "messages", nil, [
    %{
      "name" => "source",
      "required" => false,
      "type" => "unifiedthreadmessages_source_enum_param",
      "values" => ["ALL", "PARTICIPANTS"]
    }
  ])

  operation(:get, "GET", "", nil, [])
  finish()
end
