# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UniqueAdCreative do
  use MetaAds.Model

  field("sample_creative", "AdCreative", [])
  field("visual_hash", "unsigned int", [])

  finish()
end
