# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.URL do
  use MetaAds.Model

  field("engagement", "Object", [])
  field("id", "string", [])
  field("og_object", "Object", [])
  field("ownership_permissions", "Object", [])
  field("scopes", "Object", [])

  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "blacklist", "required" => false, "type" => "bool"},
    %{"name" => "denylist", "required" => false, "type" => "bool"},
    %{"name" => "hmac", "required" => false, "type" => "string"},
    %{"name" => "locale", "required" => false, "type" => "list<string>"},
    %{
      "name" => "scopes",
      "required" => false,
      "type" => "list<url_scopes>",
      "values" => ["NEWS_TAB", "NEWS_TAB_DEV_ENV"]
    },
    %{"name" => "ts", "required" => false, "type" => "datetime"}
  ])

  finish()
end
