# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserAvailableCatalogs do
  use MetaAds.Model

  field("catalog_id", "string", [])
  field("catalog_name", "string", [])
  field("product_count", "int", [])
  field("shop_name", "string", [])

  finish()
end
