# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserMobileConfig do
  use MetaAds.Model

  field("section_name", "string", [])
  field("value", "Object", [])

  finish()
end
