# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserLeadGenDisclaimerResponse do
  use MetaAds.Model

  field("checkbox_key", "string", [])
  field("is_checked", "string", [])

  finish()
end
