# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserDevice do
  use MetaAds.Model

  field("hardware", "string", [])
  field("os", "string", [])

  finish()
end
