# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.User do
  use MetaAds.Model

  field("about", "string", [])
  field("age_range", "AgeRange", [])
  field("birthday", "string", [])
  field("client_business_id", "string", [])
  field("community", "Group", [])
  field("cover", "UserCoverPhoto", [])
  field("currency", "Currency", [])
  field("education", "list<EducationExperience>", [])
  field("email", "string", [])
  field("favorite_athletes", "list<Experience>", [])
  field("favorite_teams", "list<Experience>", [])
  field("first_name", "string", [])
  field("gender", "string", [])
  field("hometown", "Page", [])
  field("id", "string", [])
  field("inspirational_people", "list<Experience>", [])
  field("install_type", "string", [])
  field("installed", "bool", [])
  field("is_guest_user", "bool", [])
  field("is_work_account", "bool", [])
  field("languages", "list<Experience>", [])
  field("last_name", "string", [])
  field("link", "string", [])
  field("local_news_megaphone_dismiss_status", "bool", [])
  field("local_news_subscription_status", "bool", [])
  field("locale", "string", [])
  field("location", "Page", [])
  field("meeting_for", "list<string>", [])
  field("middle_name", "string", [])
  field("name", "string", [])
  field("name_format", "string", [])
  field("payment_pricepoints", "PaymentPricepoints", [])
  field("political", "string", [])
  field("profile_pic", "string", [])
  field("quotes", "string", [])
  field("relationship_status", "string", [])
  field("religion", "string", [])
  field("shared_login_upgrade_required_by", "datetime", [])
  field("short_name", "string", [])
  field("significant_other", "User", [])
  field("sports", "list<Experience>", [])
  field("supports_donate_button_in_live_video", "bool", [])
  field("third_party_id", "string", [])
  field("timezone", "float", [])
  field("token_for_business", "string", [])
  field("updated_time", "datetime", [])
  field("verified", "bool", [])
  field("video_upload_limits", "VideoUploadLimits", [])
  field("website", "string", [])

  operation(:delete_access_tokens, "DELETE", "access_tokens", nil, [])

  operation(:create_access_tokens, "POST", "access_tokens", nil, [
    %{"name" => "business_app", "required" => true, "type" => "string"},
    %{"name" => "page_id", "required" => false, "type" => "string"},
    %{"name" => "scope", "required" => false, "type" => "list<string>"},
    %{"name" => "set_token_expires_in_60_days", "required" => false, "type" => "bool"}
  ])

  operation(:get_accounts, "GET", "accounts", nil, [
    %{"name" => "ad_id", "required" => false, "type" => "string"},
    %{"name" => "is_place", "required" => false, "type" => "bool"},
    %{"name" => "is_promotable", "required" => false, "type" => "bool"}
  ])

  operation(:create_accounts, "POST", "accounts", nil, [
    %{"name" => "about", "required" => false, "type" => "string"},
    %{"name" => "address", "required" => false, "type" => "string"},
    %{"name" => "category", "required" => false, "type" => "int"},
    %{"name" => "category_enum", "required" => false, "type" => "string"},
    %{"name" => "category_list", "required" => false, "type" => "list<string>"},
    %{"name" => "city_id", "required" => false, "type" => "string"},
    %{"name" => "coordinates", "required" => false, "type" => "Object"},
    %{"name" => "cover_photo", "required" => false, "type" => "Object"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "ignore_coordinate_warnings", "required" => false, "type" => "bool"},
    %{"name" => "location", "required" => false, "type" => "Object"},
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "phone", "required" => false, "type" => "string"},
    %{"name" => "picture", "required" => false, "type" => "string"},
    %{"name" => "website", "required" => false, "type" => "string"},
    %{"name" => "zip", "required" => false, "type" => "string"}
  ])

  operation(:get_ad_studies, "GET", "ad_studies", nil, [])

  operation(:create_ad_studies, "POST", "ad_studies", nil, [
    %{"name" => "cells", "required" => false, "type" => "list<Object>"},
    %{"name" => "client_business", "required" => false, "type" => "string"},
    %{"name" => "confidence_level", "required" => false, "type" => "float"},
    %{"name" => "cooldown_start_time", "required" => false, "type" => "int"},
    %{"name" => "creative_test_config", "required" => false, "type" => "map"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{"name" => "end_time", "required" => false, "type" => "int"},
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "objectives", "required" => false, "type" => "list<Object>"},
    %{"name" => "observation_end_time", "required" => false, "type" => "int"},
    %{"name" => "start_time", "required" => false, "type" => "int"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "userad_studies_type_enum_param",
      "values" => [
        "BACKEND_AB_TESTING",
        "CONTINUOUS_LIFT_CONFIG",
        "CREATIVE_SPEND_ENFORCEMENT",
        "GEO_LIFT",
        "LIFT",
        "PORTFOLIO_OPTIMIZER",
        "SPLIT_TEST",
        "VERSION_CONTROL"
      ]
    },
    %{"name" => "viewers", "required" => false, "type" => "list<int>"}
  ])

  operation(:get_adaccounts, "GET", "adaccounts", nil, [])
  operation(:get_albums, "GET", "albums", nil, [])

  operation(:create_applications, "POST", "applications", nil, [
    %{"name" => "business_app", "required" => true, "type" => "int"}
  ])

  operation(:get_apprequestformerrecipients, "GET", "apprequestformerrecipients", nil, [])
  operation(:get_apprequests, "GET", "apprequests", nil, [])
  operation(:get_assigned_ad_accounts, "GET", "assigned_ad_accounts", nil, [])
  operation(:get_assigned_applications, "GET", "assigned_applications", nil, [])

  operation(:get_assigned_business_asset_groups, "GET", "assigned_business_asset_groups", nil, [
    %{"name" => "contained_asset_id", "required" => false, "type" => "string"}
  ])

  operation(:get_assigned_pages, "GET", "assigned_pages", nil, [
    %{"name" => "pages", "required" => false, "type" => "list<unsigned int>"}
  ])

  operation(:get_assigned_product_catalogs, "GET", "assigned_product_catalogs", nil, [])

  operation(
    :get_assigned_whatsapp_business_accounts,
    "GET",
    "assigned_whatsapp_business_accounts",
    nil,
    []
  )

  operation(:get_business_users, "GET", "business_users", nil, [])

  operation(:delete_businesses, "DELETE", "businesses", nil, [
    %{"name" => "business", "required" => false, "type" => "string"}
  ])

  operation(:get_businesses, "GET", "businesses", nil, [])

  operation(:create_businesses, "POST", "businesses", nil, [
    %{"name" => "child_business_external_id", "required" => false, "type" => "string"},
    %{"name" => "email", "required" => false, "type" => "string"},
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "primary_page", "required" => false, "type" => "string"},
    %{"name" => "sales_rep_email", "required" => false, "type" => "string"},
    %{
      "name" => "survey_business_type",
      "required" => false,
      "type" => "userbusinesses_survey_business_type_enum_param",
      "values" => ["ADVERTISER", "AGENCY", "APP_DEVELOPER", "PUBLISHER"]
    },
    %{"name" => "survey_num_assets", "required" => false, "type" => "unsigned int"},
    %{"name" => "survey_num_people", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "timezone_id",
      "required" => false,
      "type" => "userbusinesses_timezone_id_enum_param",
      "values" => [
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
        "31",
        "32",
        "33",
        "34",
        "35",
        "36",
        "37",
        "38",
        "39",
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46",
        "47",
        "48",
        "49",
        "50",
        "51",
        "52",
        "53",
        "54",
        "55",
        "56",
        "57",
        "58",
        "59",
        "60",
        "61",
        "62",
        "63",
        "64",
        "65",
        "66",
        "67",
        "68",
        "69",
        "70",
        "71",
        "72",
        "73",
        "74",
        "75",
        "76",
        "77",
        "78",
        "79",
        "80",
        "81",
        "82",
        "83",
        "84",
        "85",
        "86",
        "87",
        "88",
        "89",
        "90",
        "91",
        "92",
        "93",
        "94",
        "95",
        "96",
        "97",
        "98",
        "99",
        "100",
        "101",
        "102",
        "103",
        "104",
        "105",
        "106",
        "107",
        "108",
        "109",
        "110",
        "111",
        "112",
        "113",
        "114",
        "115",
        "116",
        "117",
        "118",
        "119",
        "120",
        "121",
        "122",
        "123",
        "124",
        "125",
        "126",
        "127",
        "128",
        "129",
        "130",
        "131",
        "132",
        "133",
        "134",
        "135",
        "136",
        "137",
        "138",
        "139",
        "140",
        "141",
        "142",
        "143",
        "144",
        "145",
        "146",
        "147",
        "148",
        "149",
        "150",
        "151",
        "152",
        "153",
        "154",
        "155",
        "156",
        "157",
        "158",
        "159",
        "160",
        "161",
        "162",
        "163",
        "164",
        "165",
        "166",
        "167",
        "168",
        "169",
        "170",
        "171",
        "172",
        "173",
        "174",
        "175",
        "176",
        "177",
        "178",
        "179",
        "180",
        "181",
        "182",
        "183",
        "184",
        "185",
        "186",
        "187",
        "188",
        "189",
        "190",
        "191",
        "192",
        "193",
        "194",
        "195",
        "196",
        "197",
        "198",
        "199",
        "200",
        "201",
        "202",
        "203",
        "204",
        "205",
        "206",
        "207",
        "208",
        "209",
        "210",
        "211",
        "212",
        "213",
        "214",
        "215",
        "216",
        "217",
        "218",
        "219",
        "220",
        "221",
        "222",
        "223",
        "224",
        "225",
        "226",
        "227",
        "228",
        "229",
        "230",
        "231",
        "232",
        "233",
        "234",
        "235",
        "236",
        "237",
        "238",
        "239",
        "240",
        "241",
        "242",
        "243",
        "244",
        "245",
        "246",
        "247",
        "248",
        "249",
        "250",
        "251",
        "252",
        "253",
        "254",
        "255",
        "256",
        "257",
        "258",
        "259",
        "260",
        "261",
        "262",
        "263",
        "264",
        "265",
        "266",
        "267",
        "268",
        "269",
        "270",
        "271",
        "272",
        "273",
        "274",
        "275",
        "276",
        "277",
        "278",
        "279",
        "280",
        "281",
        "282",
        "283",
        "284",
        "285",
        "286",
        "287",
        "288",
        "289",
        "290",
        "291",
        "292",
        "293",
        "294",
        "295",
        "296",
        "297",
        "298",
        "299",
        "300",
        "301",
        "302",
        "303",
        "304",
        "305",
        "306",
        "307",
        "308",
        "309",
        "310",
        "311",
        "312",
        "313",
        "314",
        "315",
        "316",
        "317",
        "318",
        "319",
        "320",
        "321",
        "322",
        "323",
        "324",
        "325",
        "326",
        "327",
        "328",
        "329",
        "330",
        "331",
        "332",
        "333",
        "334",
        "335",
        "336",
        "337",
        "338",
        "339",
        "340",
        "341",
        "342",
        "343",
        "344",
        "345",
        "346",
        "347",
        "348",
        "349",
        "350",
        "351",
        "352",
        "353",
        "354",
        "355",
        "356",
        "357",
        "358",
        "359",
        "360",
        "361",
        "362",
        "363",
        "364",
        "365",
        "366",
        "367",
        "368",
        "369",
        "370",
        "371",
        "372",
        "373",
        "374",
        "375",
        "376",
        "377",
        "378",
        "379",
        "380",
        "381",
        "382",
        "383",
        "384",
        "385",
        "386",
        "387",
        "388",
        "389",
        "390",
        "391",
        "392",
        "393",
        "394",
        "395",
        "396",
        "397",
        "398",
        "399",
        "400",
        "401",
        "402",
        "403",
        "404",
        "405",
        "406",
        "407",
        "408",
        "409",
        "410",
        "411",
        "412",
        "413",
        "414",
        "415",
        "416",
        "417",
        "418",
        "419",
        "420",
        "421",
        "422",
        "423",
        "424",
        "425",
        "426",
        "427",
        "428",
        "429",
        "430",
        "431",
        "432",
        "433",
        "434",
        "435",
        "436",
        "437",
        "438",
        "439",
        "440",
        "441",
        "442",
        "443",
        "444",
        "445",
        "446",
        "447",
        "448",
        "449",
        "450",
        "451",
        "452",
        "453",
        "454",
        "455",
        "456",
        "457",
        "458",
        "459",
        "460",
        "461",
        "462",
        "463",
        "464",
        "465",
        "466",
        "467",
        "468",
        "469",
        "470",
        "471",
        "472",
        "473",
        "474",
        "475",
        "476",
        "477",
        "478",
        "479",
        "480",
        "481",
        "482",
        "483",
        "484",
        "485",
        "486",
        "487",
        "488",
        "489",
        "490",
        "491",
        "492",
        "493",
        "494",
        "495",
        "496",
        "497",
        "498",
        "499",
        "500",
        "501",
        "502",
        "503",
        "504",
        "505",
        "506",
        "507",
        "508",
        "509",
        "510",
        "511",
        "512",
        "513",
        "514",
        "515",
        "516",
        "517",
        "518",
        "519",
        "520",
        "521",
        "522",
        "523",
        "524",
        "525",
        "526",
        "527",
        "528",
        "529",
        "530",
        "531",
        "532",
        "533",
        "534",
        "535",
        "536",
        "537",
        "538",
        "539",
        "540",
        "541",
        "542",
        "543",
        "544",
        "545",
        "546",
        "547",
        "548",
        "549",
        "550",
        "551",
        "552",
        "553",
        "554",
        "555",
        "556",
        "557",
        "558",
        "559",
        "560",
        "561",
        "562",
        "563",
        "564",
        "565",
        "566",
        "567",
        "568",
        "569",
        "570",
        "571",
        "572",
        "573",
        "574",
        "575",
        "576",
        "577",
        "578",
        "579",
        "580",
        "581",
        "582",
        "583",
        "584",
        "585",
        "586",
        "587",
        "588",
        "589",
        "590",
        "591",
        "592"
      ]
    },
    %{
      "name" => "vertical",
      "required" => true,
      "type" => "userbusinesses_vertical_enum_param",
      "values" => [
        "ADVERTISING",
        "AUTOMOTIVE",
        "CONSUMER_PACKAGED_GOODS",
        "ECOMMERCE",
        "EDUCATION",
        "ENERGY_AND_UTILITIES",
        "ENTERTAINMENT_AND_MEDIA",
        "FINANCIAL_SERVICES",
        "GAMING",
        "GOVERNMENT_AND_POLITICS",
        "HEALTH",
        "LUXURY",
        "MARKETING",
        "NON_PROFIT",
        "NOT_SET",
        "ORGANIZATIONS_AND_ASSOCIATIONS",
        "OTHER",
        "PROFESSIONAL_SERVICES",
        "RESTAURANT",
        "RETAIL",
        "TECHNOLOGY",
        "TELECOM",
        "TRAVEL"
      ]
    }
  ])

  operation(:get_conversations, "GET", "conversations", nil, [
    %{"name" => "folder", "required" => false, "type" => "string"},
    %{
      "name" => "platform",
      "required" => false,
      "type" => "userconversations_platform_enum_param",
      "values" => ["INSTAGRAM", "MESSENGER"]
    },
    %{"name" => "tags", "required" => false, "type" => "list<string>"},
    %{"name" => "user_id", "required" => false, "type" => "string"}
  ])

  operation(:get_custom_labels, "GET", "custom_labels", nil, [])

  operation(:get_events, "GET", "events", nil, [
    %{"name" => "include_canceled", "required" => false, "type" => "bool"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "userevents_type_enum_param",
      "values" => ["attending", "created", "declined", "maybe", "not_replied"]
    }
  ])

  operation(:get_feed, "GET", "feed", nil, [
    %{"name" => "include_hidden", "required" => false, "type" => "bool"},
    %{"name" => "q", "required" => false, "type" => "string"},
    %{"name" => "show_expired", "required" => false, "type" => "bool"},
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{"name" => "until", "required" => false, "type" => "datetime"},
    %{"name" => "with", "required" => false, "type" => "string"}
  ])

  operation(:get_friends, "GET", "friends", nil, [
    %{"name" => "uid", "required" => false, "type" => "int"}
  ])

  operation(:get_fundraisers, "GET", "fundraisers", nil, [])

  operation(:get_groups, "GET", "groups", nil, [
    %{"name" => "admin_only", "required" => false, "type" => "bool"},
    %{"name" => "parent", "required" => false, "type" => "string"}
  ])

  operation(:get_ids_for_apps, "GET", "ids_for_apps", nil, [
    %{"name" => "app", "required" => false, "type" => "int"}
  ])

  operation(:get_ids_for_business, "GET", "ids_for_business", nil, [
    %{"name" => "app", "required" => false, "type" => "int"}
  ])

  operation(:get_ids_for_pages, "GET", "ids_for_pages", nil, [
    %{"name" => "page", "required" => false, "type" => "int"}
  ])

  operation(:get_likes, "GET", "likes", nil, [
    %{"name" => "target_id", "required" => false, "type" => "string"}
  ])

  operation(:get_live_videos, "GET", "live_videos", nil, [
    %{
      "name" => "broadcast_status",
      "required" => false,
      "type" => "list<userlive_videos_broadcast_status_enum_param>",
      "values" => [
        "LIVE",
        "LIVE_STOPPED",
        "PROCESSING",
        "SCHEDULED_CANCELED",
        "SCHEDULED_EXPIRED",
        "SCHEDULED_LIVE",
        "SCHEDULED_UNPUBLISHED",
        "UNPUBLISHED",
        "VOD"
      ]
    },
    %{
      "name" => "source",
      "required" => false,
      "type" => "userlive_videos_source_enum_param",
      "values" => ["owner", "target"]
    }
  ])

  operation(
    :create_messenger_desktop_performance_traces,
    "POST",
    "messenger_desktop_performance_traces",
    nil,
    []
  )

  operation(
    :create_messenger_kids_accounts_unread_badge,
    "POST",
    "messenger_kids_accounts_unread_badge",
    nil,
    [%{"name" => "proxied_app_id", "required" => true, "type" => "int"}]
  )

  operation(:get_music, "GET", "music", nil, [
    %{"name" => "target_id", "required" => false, "type" => "string"}
  ])

  operation(:create_notifications, "POST", "notifications", nil, [
    %{"name" => "bot_message_payload_elements", "required" => false, "type" => "string"},
    %{
      "name" => "filtering",
      "required" => false,
      "type" => "list<usernotifications_filtering_enum_param>",
      "values" => ["ema", "groups", "groups_social"]
    },
    %{"name" => "game_metadata", "required" => false, "type" => "string"},
    %{"name" => "href", "required" => false, "type" => "Object"},
    %{"name" => "label", "required" => false, "type" => "string"},
    %{"name" => "message", "required" => false, "type" => "map"},
    %{"name" => "notif_ids", "required" => false, "type" => "list<string>"},
    %{"name" => "notification_content_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "payload", "required" => false, "type" => "string"},
    %{"name" => "read", "required" => false, "type" => "bool"},
    %{"name" => "ref", "required" => false, "type" => "string"},
    %{"name" => "schedule_interval", "required" => false, "type" => "unsigned int"},
    %{"name" => "seen", "required" => false, "type" => "bool"},
    %{"name" => "template", "required" => false, "type" => "Object"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "usernotifications_type_enum_param",
      "values" => ["content_update", "generic"]
    }
  ])

  operation(:get_payment_transactions, "GET", "payment_transactions", nil, [])

  operation(:delete_permissions, "DELETE", "permissions", nil, [
    %{"name" => "permission", "required" => false, "type" => "string"}
  ])

  operation(:get_permissions, "GET", "permissions", nil, [
    %{"name" => "permission", "required" => false, "type" => "string"},
    %{
      "name" => "status",
      "required" => false,
      "type" => "userpermissions_status_enum_param",
      "values" => ["declined", "expired", "granted"]
    }
  ])

  operation(:get_personal_ad_accounts, "GET", "personal_ad_accounts", nil, [])

  operation(:get_photos, "GET", "photos", nil, [
    %{
      "name" => "type",
      "required" => false,
      "type" => "userphotos_type_enum_param",
      "values" => ["tagged", "uploaded"]
    }
  ])

  operation(:create_photos, "POST", "photos", nil, [
    %{"name" => "aid", "required" => false, "type" => "string"},
    %{"name" => "allow_spherical_photo", "required" => false, "type" => "bool"},
    %{"name" => "alt_text_custom", "required" => false, "type" => "string"},
    %{"name" => "android_key_hash", "required" => false, "type" => "string"},
    %{"name" => "application_id", "required" => false, "type" => "string"},
    %{"name" => "attempt", "required" => false, "type" => "unsigned int"},
    %{"name" => "audience_exp", "required" => false, "type" => "bool"},
    %{"name" => "backdated_time", "required" => false, "type" => "datetime"},
    %{
      "name" => "backdated_time_granularity",
      "required" => false,
      "type" => "userphotos_backdated_time_granularity_enum_param",
      "values" => ["day", "hour", "min", "month", "none", "year"]
    },
    %{"name" => "caption", "required" => false, "type" => "string"},
    %{"name" => "composer_entry_point", "required" => false, "type" => "string"},
    %{"name" => "composer_session_id", "required" => false, "type" => "string"},
    %{"name" => "direct_share_status", "required" => false, "type" => "unsigned int"},
    %{"name" => "feed_targeting", "required" => false, "type" => "Object"},
    %{"name" => "filter_type", "required" => false, "type" => "unsigned int"},
    %{"name" => "full_res_is_coming_later", "required" => false, "type" => "bool"},
    %{
      "name" => "initial_view_heading_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "initial_view_pitch_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{
      "name" => "initial_view_vertical_fov_override_degrees",
      "required" => false,
      "type" => "unsigned int"
    },
    %{"name" => "ios_bundle_id", "required" => false, "type" => "string"},
    %{"name" => "is_explicit_location", "required" => false, "type" => "bool"},
    %{"name" => "is_explicit_place", "required" => false, "type" => "bool"},
    %{"name" => "manual_privacy", "required" => false, "type" => "bool"},
    %{"name" => "message", "required" => false, "type" => "string"},
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "no_story", "required" => false, "type" => "bool"},
    %{"name" => "offline_id", "required" => false, "type" => "unsigned int"},
    %{"name" => "og_action_type_id", "required" => false, "type" => "string"},
    %{"name" => "og_icon_id", "required" => false, "type" => "string"},
    %{"name" => "og_object_id", "required" => false, "type" => "string"},
    %{"name" => "og_phrase", "required" => false, "type" => "string"},
    %{"name" => "og_set_profile_badge", "required" => false, "type" => "bool"},
    %{"name" => "og_suggestion_mechanism", "required" => false, "type" => "string"},
    %{"name" => "place", "required" => false, "type" => "Object"},
    %{"name" => "privacy", "required" => false, "type" => "string"},
    %{"name" => "profile_id", "required" => false, "type" => "int"},
    %{"name" => "provenance_info", "required" => false, "type" => "map"},
    %{"name" => "provenance_metadata", "required" => false, "type" => "map"},
    %{"name" => "proxied_app_id", "required" => false, "type" => "string"},
    %{"name" => "published", "required" => false, "type" => "bool"},
    %{"name" => "qn", "required" => false, "type" => "string"},
    %{"name" => "scheduled_publish_time", "required" => false, "type" => "unsigned int"},
    %{"name" => "spherical_metadata", "required" => false, "type" => "map"},
    %{"name" => "sponsor_id", "required" => false, "type" => "string"},
    %{"name" => "sponsor_relationship", "required" => false, "type" => "unsigned int"},
    %{"name" => "tags", "required" => false, "type" => "list<Object>"},
    %{"name" => "target_id", "required" => false, "type" => "int"},
    %{"name" => "targeting", "required" => false, "type" => "Object"},
    %{"name" => "time_since_original_post", "required" => false, "type" => "unsigned int"},
    %{"name" => "uid", "required" => false, "type" => "int"},
    %{
      "name" => "unpublished_content_type",
      "required" => false,
      "type" => "userphotos_unpublished_content_type_enum_param",
      "values" => [
        "ADS_POST",
        "DRAFT",
        "INLINE_CREATED",
        "PUBLISHED",
        "PUBLISH_PENDING",
        "REVIEWABLE_BRANDED_CONTENT",
        "SCHEDULED",
        "SCHEDULED_RECURRING"
      ]
    },
    %{"name" => "url", "required" => false, "type" => "string"},
    %{"name" => "user_selected_tags", "required" => false, "type" => "bool"},
    %{"name" => "vault_image_id", "required" => false, "type" => "string"}
  ])

  operation(:get_picture, "GET", "picture", nil, [
    %{"name" => "height", "required" => false, "type" => "int"},
    %{"name" => "redirect", "required" => false, "type" => "bool"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "userpicture_type_enum_param",
      "values" => ["album", "large", "normal", "small", "square"]
    },
    %{"name" => "width", "required" => false, "type" => "int"}
  ])

  operation(:get_posts, "GET", "posts", nil, [
    %{"name" => "include_hidden", "required" => false, "type" => "bool"},
    %{"name" => "q", "required" => false, "type" => "string"},
    %{"name" => "show_expired", "required" => false, "type" => "bool"},
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{"name" => "until", "required" => false, "type" => "datetime"},
    %{"name" => "with", "required" => false, "type" => "string"}
  ])

  operation(:get_rich_media_documents, "GET", "rich_media_documents", nil, [
    %{"name" => "query", "required" => false, "type" => "string"}
  ])

  operation(:get_videos, "GET", "videos", nil, [
    %{
      "name" => "type",
      "required" => false,
      "type" => "uservideos_type_enum_param",
      "values" => ["TAGGED", "UPLOADED"]
    }
  ])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "emoji_color_pref", "required" => false, "type" => "unsigned int"},
    %{"name" => "firstname", "required" => false, "type" => "string"},
    %{"name" => "lastname", "required" => false, "type" => "string"},
    %{
      "name" => "local_news_megaphone_dismiss_status",
      "required" => false,
      "type" => "user_local_news_megaphone_dismiss_status",
      "values" => ["NO", "YES"]
    },
    %{
      "name" => "local_news_subscription_status",
      "required" => false,
      "type" => "user_local_news_subscription_status",
      "values" => ["STATUS_OFF", "STATUS_ON"]
    },
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "password", "required" => false, "type" => "string"}
  ])

  finish()
end
