# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserPaymentMobilePricepoints do
  use MetaAds.Model

  field("mobile_country", "string", [])
  field("phone_number_last4", "string", [])
  field("pricepoints", "list<Object>", [])
  field("user_currency", "string", [])

  finish()
end
