# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserPaymentModulesOptions do
  use MetaAds.Model

  field("account_id", "string", [])
  field("available_payment_options", "list<Object>", [])
  field("country", "string", [])
  field("currency", "string", [])

  finish()
end
