# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserIDForApp do
  use MetaAds.Model

  field("app", "Application", [])
  field("id", "string", [])
  field("instant_game_player_id", "string", [])

  finish()
end
