# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserCoverPhoto do
  use MetaAds.Model

  field("offset_x", "float", [])
  field("offset_y", "float", [])
  field("source", "string", [])

  finish()
end
