# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.UserPaymentMethodsInfo do
  use MetaAds.Model

  field("account_id", "string", [])
  field("available_card_types", "list<string>", [])
  field("available_payment_methods", "list<string>", [])
  field("available_payment_methods_details", "list<Object>", [])
  field("country", "string", [])
  field("currency", "string", [])
  field("existing_payment_methods", "list<Object>", [])

  finish()
end
