# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.Vehicle do
  use MetaAds.Model

  field("address", "Object", [])
  field("applinks", "CatalogItemAppLinks", [])
  field("availability", "string", [])
  field("availability_circle_radius", "float", [])
  field("availability_circle_radius_unit", "string", [])
  field("body_style", "string", [])
  field("condition", "string", [])
  field("currency", "string", [])
  field("custom_label_0", "string", [])
  field("custom_label_1", "string", [])
  field("custom_label_2", "string", [])
  field("custom_label_3", "string", [])
  field("custom_label_4", "string", [])
  field("custom_number_0", "unsigned int", [])
  field("custom_number_1", "unsigned int", [])
  field("custom_number_2", "unsigned int", [])
  field("custom_number_3", "unsigned int", [])
  field("custom_number_4", "unsigned int", [])
  field("date_first_on_lot", "string", [])
  field("dealer_communication_channel", "string", [])
  field("dealer_email", "string", [])
  field("dealer_id", "string", [])
  field("dealer_name", "string", [])
  field("dealer_phone", "string", [])
  field("dealer_privacy_policy_url", "string", [])
  field("description", "string", [])
  field("drivetrain", "string", [])
  field("exterior_color", "string", [])
  field("fb_page_id", "Page", [])
  field("features", "list<Object>", [])
  field("fuel_type", "string", [])
  field("id", "string", [])

  field("image_fetch_status", "Vehicle_image_fetch_status", [
    "DIRECT_UPLOAD",
    "FETCHED",
    "FETCH_FAILED",
    "NO_STATUS",
    "OUTDATED",
    "PARTIAL_FETCH"
  ])

  field("images", "list<string>", [])
  field("interior_color", "string", [])
  field("legal_disclosure_impressum_url", "string", [])
  field("make", "string", [])
  field("mileage", "Object", [])
  field("model", "string", [])
  field("previous_currency", "string", [])
  field("previous_price", "string", [])
  field("price", "string", [])
  field("product_priority_0", "float", [])
  field("product_priority_1", "float", [])
  field("product_priority_2", "float", [])
  field("product_priority_3", "float", [])
  field("product_priority_4", "float", [])
  field("sale_currency", "string", [])
  field("sale_price", "string", [])
  field("sanitized_images", "list<string>", [])
  field("state_of_vehicle", "string", [])
  field("tags", "list<string>", [])
  field("title", "string", [])
  field("transmission", "string", [])
  field("trim", "string", [])
  field("unit_price", "Object", [])
  field("url", "string", [])
  field("vehicle_id", "string", [])
  field("vehicle_registration_plate", "string", [])
  field("vehicle_specifications", "list<Object>", [])
  field("vehicle_type", "string", [])
  field("vin", "string", [])
  field("visibility", "Vehicle_visibility", ["PUBLISHED", "STAGING"])
  field("year", "unsigned int", [])

  operation(:get_channels_to_integrity_status, "GET", "channels_to_integrity_status", nil, [])

  operation(:get_override_details, "GET", "override_details", nil, [
    %{"name" => "keys", "required" => false, "type" => "list<string>"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "vehicleoverride_details_type_enum_param",
      "values" => ["COUNTRY", "LANGUAGE", "LANGUAGE_AND_COUNTRY"]
    }
  ])

  operation(:get_videos_metadata, "GET", "videos_metadata", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "address", "required" => false, "type" => "map"},
    %{"name" => "applinks", "required" => false, "type" => "Object"},
    %{
      "name" => "availability",
      "required" => false,
      "type" => "vehicle_availability",
      "values" => ["AVAILABLE", "NOT_AVAILABLE", "PENDING", "UNKNOWN"]
    },
    %{
      "name" => "body_style",
      "required" => false,
      "type" => "vehicle_body_style",
      "values" => [
        "CONVERTIBLE",
        "COUPE",
        "CROSSOVER",
        "ESTATE",
        "GRANDTOURER",
        "HATCHBACK",
        "MINIBUS",
        "MINIVAN",
        "MPV",
        "NONE",
        "OTHER",
        "PICKUP",
        "ROADSTER",
        "SALOON",
        "SEDAN",
        "SMALL_CAR",
        "SPORTSCAR",
        "SUPERCAR",
        "SUPERMINI",
        "SUV",
        "TRUCK",
        "VAN",
        "WAGON"
      ]
    },
    %{
      "name" => "condition",
      "required" => false,
      "type" => "vehicle_condition",
      "values" => ["EXCELLENT", "FAIR", "GOOD", "NONE", "OTHER", "POOR", "VERY_GOOD"]
    },
    %{"name" => "currency", "required" => false, "type" => "string"},
    %{"name" => "date_first_on_lot", "required" => false, "type" => "string"},
    %{"name" => "dealer_id", "required" => false, "type" => "string"},
    %{"name" => "dealer_name", "required" => false, "type" => "string"},
    %{"name" => "dealer_phone", "required" => false, "type" => "string"},
    %{"name" => "description", "required" => false, "type" => "string"},
    %{
      "name" => "drivetrain",
      "required" => false,
      "type" => "vehicle_drivetrain",
      "values" => ["AWD", "FOUR_WD", "FWD", "NONE", "OTHER", "RWD", "TWO_WD"]
    },
    %{"name" => "exterior_color", "required" => false, "type" => "string"},
    %{"name" => "fb_page_id", "required" => false, "type" => "string"},
    %{
      "name" => "fuel_type",
      "required" => false,
      "type" => "vehicle_fuel_type",
      "values" => [
        "DIESEL",
        "ELECTRIC",
        "FLEX",
        "GASOLINE",
        "HYBRID",
        "NONE",
        "OTHER",
        "PETROL",
        "PLUGIN_HYBRID"
      ]
    },
    %{"name" => "images", "required" => false, "type" => "list<Object>"},
    %{"name" => "interior_color", "required" => false, "type" => "string"},
    %{"name" => "make", "required" => false, "type" => "string"},
    %{"name" => "mileage", "required" => false, "type" => "map"},
    %{"name" => "model", "required" => false, "type" => "string"},
    %{"name" => "price", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "state_of_vehicle",
      "required" => false,
      "type" => "vehicle_state_of_vehicle",
      "values" => ["CPO", "NEW", "USED"]
    },
    %{"name" => "title", "required" => false, "type" => "string"},
    %{
      "name" => "transmission",
      "required" => false,
      "type" => "vehicle_transmission",
      "values" => ["AUTOMATIC", "MANUAL", "NONE", "OTHER"]
    },
    %{"name" => "trim", "required" => false, "type" => "string"},
    %{"name" => "url", "required" => false, "type" => "string"},
    %{
      "name" => "vehicle_type",
      "required" => false,
      "type" => "vehicle_vehicle_type",
      "values" => [
        "BOAT",
        "CAR_TRUCK",
        "COMMERCIAL",
        "MOTORCYCLE",
        "OTHER",
        "POWERSPORT",
        "RV_CAMPER",
        "TRAILER"
      ]
    },
    %{"name" => "vin", "required" => false, "type" => "string"},
    %{"name" => "year", "required" => false, "type" => "unsigned int"}
  ])

  finish()
end
