# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VehicleOffer do
  use MetaAds.Model

  field("amount_currency", "string", [])
  field("amount_percentage", "float", [])
  field("amount_price", "string", [])
  field("amount_qualifier", "string", [])
  field("applinks", "CatalogItemAppLinks", [])
  field("availability", "string", [])
  field("body_style", "string", [])
  field("cashback_currency", "string", [])
  field("cashback_price", "string", [])
  field("comscore_market_codes", "list<string>", [])
  field("currency", "string", [])
  field("custom_label_0", "string", [])
  field("custom_label_1", "string", [])
  field("custom_label_2", "string", [])
  field("custom_label_3", "string", [])
  field("custom_label_4", "string", [])
  field("custom_number_0", "unsigned int", [])
  field("custom_number_1", "unsigned int", [])
  field("custom_number_2", "unsigned int", [])
  field("custom_number_3", "unsigned int", [])
  field("custom_number_4", "unsigned int", [])
  field("dma_codes", "list<string>", [])
  field("downpayment_currency", "string", [])
  field("downpayment_price", "string", [])
  field("downpayment_qualifier", "string", [])
  field("drivetrain", "string", [])
  field("end_date", "string", [])
  field("end_time", "int", [])
  field("exterior_color", "string", [])
  field("fuel_type", "string", [])
  field("generation", "string", [])
  field("id", "string", [])

  field("image_fetch_status", "VehicleOffer_image_fetch_status", [
    "DIRECT_UPLOAD",
    "FETCHED",
    "FETCH_FAILED",
    "NO_STATUS",
    "OUTDATED",
    "PARTIAL_FETCH"
  ])

  field("images", "list<string>", [])
  field("interior_color", "string", [])
  field("interior_upholstery", "string", [])
  field("make", "string", [])
  field("model", "string", [])
  field("offer_description", "string", [])
  field("offer_disclaimer", "string", [])
  field("offer_type", "string", [])
  field("price", "string", [])
  field("product_priority_0", "float", [])
  field("product_priority_1", "float", [])
  field("product_priority_2", "float", [])
  field("product_priority_3", "float", [])
  field("product_priority_4", "float", [])
  field("sanitized_images", "list<string>", [])
  field("start_date", "string", [])
  field("start_time", "int", [])
  field("tags", "list<string>", [])
  field("term_length", "unsigned int", [])
  field("term_qualifier", "string", [])
  field("title", "string", [])
  field("transmission", "string", [])
  field("trim", "string", [])
  field("unit_price", "Object", [])
  field("url", "string", [])
  field("vehicle_offer_id", "string", [])
  field("visibility", "VehicleOffer_visibility", ["PUBLISHED", "STAGING"])
  field("year", "int", [])

  operation(:get_channels_to_integrity_status, "GET", "channels_to_integrity_status", nil, [])

  operation(:get_override_details, "GET", "override_details", nil, [
    %{"name" => "keys", "required" => false, "type" => "list<string>"},
    %{
      "name" => "type",
      "required" => false,
      "type" => "vehicleofferoverride_details_type_enum_param",
      "values" => ["COUNTRY", "LANGUAGE", "LANGUAGE_AND_COUNTRY"]
    }
  ])

  operation(:get_videos_metadata, "GET", "videos_metadata", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
