# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoList do
  use MetaAds.Model

  field("creation_time", "datetime", [])
  field("description", "string", [])
  field("id", "string", [])
  field("last_modified", "datetime", [])
  field("owner", "Object", [])
  field("season_number", "int", [])
  field("thumbnail", "string", [])
  field("title", "string", [])
  field("videos_count", "int", [])

  operation(:get_videos, "GET", "videos", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
