# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoGroup do
  use MetaAds.Model

  field("created_time", "string", [])
  field("description", "string", [])
  field("disable_reason", "string", [])
  field("id", "string", [])
  field("ig_profile_ids", "list<string>", [])
  field("is_disabled", "bool", [])
  field("is_fb_video_group", "bool", [])
  field("last_used_time", "string", [])
  field("length", "float", [])
  field("name", "string", [])
  field("page_id", "string", [])
  field("page_ids", "list<string>", [])
  field("picture", "string", [])
  field("placements", "list<string>", [])
  field("video_group_types", "list<string>", [])
  field("videos", "list<string>", [])
  field("views", "unsigned int", [])

  finish()
end
