# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoCopyrightConditionGroup do
  use MetaAds.Model

  field("action", "string", [])
  field("conditions", "list<Object>", [])
  field("validity_status", "string", [])

  finish()
end
