# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoCopyrightRule do
  use MetaAds.Model

  field("condition_groups", "list<VideoCopyrightConditionGroup>", [])
  field("copyrights", "list<string>", [])
  field("created_date", "datetime", [])
  field("creator", "User", [])
  field("id", "string", [])
  field("is_in_migration", "bool", [])
  field("name", "string", [])
  field("validity_status", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
