# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoCopyrightCheckStatus do
  use MetaAds.Model

  field("matches_found", "bool", [])
  field("status", "string", [])

  finish()
end
