# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoThumbnail do
  use MetaAds.Model

  field("height", "unsigned int", [])
  field("id", "string", [])
  field("is_preferred", "bool", [])
  field("name", "string", [])
  field("scale", "float", [])
  field("uri", "string", [])
  field("width", "unsigned int", [])

  finish()
end
