# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoPoll do
  use MetaAds.Model

  field("close_after_voting", "bool", [])
  field("default_open", "bool", [])
  field("id", "string", [])
  field("question", "string", [])
  field("show_gradient", "bool", [])
  field("show_results", "bool", [])
  field("status", "VideoPoll_status", ["closed", "results_open", "voting_open"])

  operation(:get_poll_options, "GET", "poll_options", nil, [])
  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{
      "name" => "action",
      "required" => true,
      "type" => "videopoll_action",
      "values" => ["ATTACH_TO_VIDEO", "CLOSE", "DELETE_POLL", "SHOW_RESULTS", "SHOW_VOTING"]
    },
    %{"name" => "close_after_voting", "required" => false, "type" => "bool"},
    %{"name" => "default_open", "required" => false, "type" => "bool"},
    %{"name" => "show_gradient", "required" => false, "type" => "bool"},
    %{"name" => "show_results", "required" => false, "type" => "bool"}
  ])

  finish()
end
