# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoStatusProcessingPhase do
  use MetaAds.Model

  field("errors", "list<VideoStatusError>", [])
  field("status", "string", [])

  finish()
end
