# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoUploadLimits do
  use MetaAds.Model

  field("length", "unsigned int", [])
  field("size", "int", [])

  finish()
end
