# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.VideoCopyrightSegment do
  use MetaAds.Model

  field("duration_in_sec", "float", [])
  field("media_type", "string", [])
  field("start_time_in_sec", "float", [])

  finish()
end
