# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WearableDevicePublicKey do
  use MetaAds.Model

  field("base64_encoded_public_key", "string", [])
  field("creation_time_on_device", "datetime", [])
  field("device_uuid", "string", [])
  field("id", "string", [])
  field("key_type", "string", [])
  field("owner_id", "string", [])
  field("product_use_case", "string", [])
  field("version", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
