# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WebAppLink do
  use MetaAds.Model

  field("should_fallback", "bool", [])
  field("url", "string", [])

  finish()
end
