# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WebsiteCreativeInfo do
  use MetaAds.Model

  field("id", "string", [])
  field("image_urls", "list<string>", [])
  field("link_url", "string", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
