# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WhatsAppPaymentCapabilities do
  use MetaAds.Model

  field("is_enabled", "bool", [])
  field("payment_capability_details", "list<Object>", [])

  finish()
end
