# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WhatsAppBusinessProfile do
  use MetaAds.Model

  field("id", "string", [])
  field("name_verification", "Object", [])
  field("whatsapp_business_api_data", "Object", [])

  operation(:get, "GET", "", nil, [])
  operation(:create, "POST", "", nil, [])
  finish()
end
