# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WhatsAppBusinessAccount do
  use MetaAds.Model

  field("account_review_status", "string", [])
  field("analytics", "Object", [])
  field("auth_international_rate_eligibility", "Object", [])

  field("business_verification_status", "WhatsAppBusinessAccount_business_verification_status", [
    "expired",
    "failed",
    "ineligible",
    "not_verified",
    "pending",
    "pending_need_more_info",
    "pending_submission",
    "rejected",
    "revoked",
    "verified"
  ])

  field("country", "string", [])
  field("creation_time", "int", [])
  field("currency", "string", [])
  field("disable_marketing_messages_on_cloud_api", "bool", [])
  field("health_status", "WhatsAppBusinessHealthStatusForMessageSend", [])
  field("id", "string", [])
  field("is_enabled_for_insights", "bool", [])
  field("is_shared_with_partners", "bool", [])
  field("linked_commerce_account", "CommerceMerchantSettings", [])
  field("marketing_messages_ad_account", "Object", [])
  field("marketing_messages_lite_api_status", "string", [])
  field("marketing_messages_onboarding_status", "string", [])
  field("message_template_namespace", "string", [])
  field("name", "string", [])
  field("on_behalf_of_business_info", "Object", [])
  field("owner_business", "Business", [])
  field("owner_business_info", "Object", [])
  field("ownership_type", "string", [])
  field("primary_business_location", "string", [])
  field("primary_funding_id", "string", [])
  field("purchase_order_number", "string", [])
  field("status", "string", [])
  field("template_auto_archival_enabled", "bool", [])
  field("timezone_id", "string", [])

  field(
    "whatsapp_business_manager_messaging_limit",
    "WhatsAppBusinessAccount_whatsapp_business_manager_messaging_limit",
    ["TIER_100K", "TIER_10K", "TIER_250", "TIER_2K", "TIER_50", "TIER_UNLIMITED", "UNTIERED"]
  )

  field("whatsapp_manager_marketing_messages_max_price_enroll_status", "string", [])

  operation(:get_activities, "GET", "activities", nil, [])

  operation(:delete_assigned_users, "DELETE", "assigned_users", nil, [
    %{"name" => "user", "required" => true, "type" => "int"}
  ])

  operation(:get_assigned_users, "GET", "assigned_users", nil, [
    %{"name" => "business", "required" => true, "type" => "string"}
  ])

  operation(:create_assigned_users, "POST", "assigned_users", nil, [
    %{
      "name" => "tasks",
      "required" => true,
      "type" => "list<whatsappbusinessaccountassigned_users_tasks_enum_param>",
      "values" => [
        "DEVELOP",
        "MANAGE",
        "MANAGE_EXTENSIONS",
        "MANAGE_PHONE",
        "MANAGE_PHONE_ASSETS",
        "MANAGE_TEMPLATES",
        "MESSAGING",
        "VIEW_COST",
        "VIEW_PHONE_ASSETS",
        "VIEW_TEMPLATES"
      ]
    },
    %{"name" => "user", "required" => true, "type" => "int"}
  ])

  operation(:get_audiences, "GET", "audiences", nil, [])

  operation(
    :create_business_messaging_feature_status,
    "POST",
    "business_messaging_feature_status",
    nil,
    [%{"name" => "features", "required" => true, "type" => "list<map>"}]
  )

  operation(:get_call_analytics, "GET", "call_analytics", nil, [
    %{"name" => "country_codes", "required" => false, "type" => "list<string>"},
    %{
      "name" => "dimensions",
      "required" => false,
      "type" => "list<whatsappbusinessaccountcall_analytics_dimensions_enum_param>",
      "values" => ["COUNTRY", "DIRECTION", "PHONE", "TIER", "UNKNOWN"]
    },
    %{
      "name" => "directions",
      "required" => false,
      "type" => "list<whatsappbusinessaccountcall_analytics_directions_enum_param>",
      "values" => ["BUSINESS_INITIATED", "UNKNOWN", "USER_INITIATED"]
    },
    %{"name" => "end", "required" => true, "type" => "unsigned int"},
    %{
      "name" => "granularity",
      "required" => true,
      "type" => "whatsappbusinessaccountcall_analytics_granularity_enum_param",
      "values" => ["DAILY", "HALF_HOUR", "MONTHLY"]
    },
    %{
      "name" => "metric_types",
      "required" => false,
      "type" => "list<whatsappbusinessaccountcall_analytics_metric_types_enum_param>",
      "values" => ["AVERAGE_DURATION", "COST", "COUNT", "UNKNOWN"]
    },
    %{"name" => "phone_numbers", "required" => false, "type" => "list<string>"},
    %{"name" => "start", "required" => true, "type" => "unsigned int"},
    %{"name" => "tiers", "required" => false, "type" => "list<string>"}
  ])

  operation(:get_conversation_analytics, "GET", "conversation_analytics", nil, [
    %{
      "name" => "conversation_categories",
      "required" => false,
      "type" =>
        "list<whatsappbusinessaccountconversation_analytics_conversation_categories_enum_param>",
      "values" => [
        "AUTHENTICATION",
        "AUTHENTICATION_INTERNATIONAL",
        "MARKETING",
        "MARKETING_LITE",
        "SERVICE",
        "UTILITY"
      ]
    },
    %{
      "name" => "conversation_directions",
      "required" => false,
      "type" =>
        "list<whatsappbusinessaccountconversation_analytics_conversation_directions_enum_param>",
      "values" => ["BUSINESS_INITIATED", "UNKNOWN", "USER_INITIATED"]
    },
    %{
      "name" => "conversation_types",
      "required" => false,
      "type" =>
        "list<whatsappbusinessaccountconversation_analytics_conversation_types_enum_param>",
      "values" => ["FREE_ENTRY_POINT", "FREE_TIER", "REGULAR", "UNKNOWN"]
    },
    %{"name" => "country_codes", "required" => false, "type" => "list<string>"},
    %{
      "name" => "dimensions",
      "required" => false,
      "type" => "list<whatsappbusinessaccountconversation_analytics_dimensions_enum_param>",
      "values" => [
        "CONVERSATION_CATEGORY",
        "CONVERSATION_DIRECTION",
        "CONVERSATION_TYPE",
        "COUNTRY",
        "PHONE",
        "UNKNOWN"
      ]
    },
    %{"name" => "end", "required" => true, "type" => "unsigned int"},
    %{
      "name" => "granularity",
      "required" => true,
      "type" => "whatsappbusinessaccountconversation_analytics_granularity_enum_param",
      "values" => ["DAILY", "HALF_HOUR", "MONTHLY"]
    },
    %{
      "name" => "metric_types",
      "required" => false,
      "type" => "list<whatsappbusinessaccountconversation_analytics_metric_types_enum_param>",
      "values" => ["CONVERSATION", "COST", "UNKNOWN"]
    },
    %{"name" => "phone_numbers", "required" => false, "type" => "list<string>"},
    %{"name" => "start", "required" => true, "type" => "unsigned int"}
  ])

  operation(:get_dataset, "GET", "dataset", nil, [])

  operation(:create_dataset, "POST", "dataset", nil, [
    %{"name" => "dataset_name", "required" => false, "type" => "string"}
  ])

  operation(:get_degrees_of_freedom_spec, "GET", "degrees_of_freedom_spec", nil, [])
  operation(:get_flows, "GET", "flows", nil, [])

  operation(:create_flows, "POST", "flows", nil, [
    %{
      "name" => "categories",
      "required" => true,
      "type" => "list<whatsappbusinessaccountflows_categories_enum_param>",
      "values" => [
        "APPOINTMENT_BOOKING",
        "CONTACT_US",
        "CUSTOMER_SUPPORT",
        "LEAD_GENERATION",
        "OTHER",
        "SHOPPING",
        "SIGN_IN",
        "SIGN_UP",
        "SURVEY"
      ]
    },
    %{"name" => "clone_flow_id", "required" => false, "type" => "string"},
    %{"name" => "endpoint_uri", "required" => false, "type" => "string"},
    %{"name" => "flow_json", "required" => false, "type" => "string"},
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "publish", "required" => false, "type" => "bool"}
  ])

  operation(
    :create_generate_payment_configuration_oauth_link,
    "POST",
    "generate_payment_configuration_oauth_link",
    nil,
    [
      %{"name" => "configuration_name", "required" => true, "type" => "string"},
      %{"name" => "redirect_url", "required" => false, "type" => "string"}
    ]
  )

  operation(:get_group_analytics, "GET", "group_analytics", nil, [
    %{"name" => "end", "required" => true, "type" => "datetime"},
    %{
      "name" => "granularity",
      "required" => false,
      "type" => "whatsappbusinessaccountgroup_analytics_granularity_enum_param",
      "values" => ["DAILY"]
    },
    %{"name" => "group_ids", "required" => true, "type" => "list<string>"},
    %{
      "name" => "metric_types",
      "required" => false,
      "type" => "list<whatsappbusinessaccountgroup_analytics_metric_types_enum_param>",
      "values" => [
        "CLICKS",
        "COST",
        "DELIVERED",
        "PARTICIPANTS_JOINED",
        "PARTICIPANTS_LEFT",
        "READ",
        "REPLIES",
        "SENT"
      ]
    },
    %{"name" => "start", "required" => true, "type" => "datetime"}
  ])

  operation(:get_message_campaigns, "GET", "message_campaigns", nil, [])

  operation(:create_message_samples, "POST", "message_samples", nil, [
    %{"name" => "interactive", "required" => false, "type" => "map"},
    %{"name" => "text", "required" => false, "type" => "map"},
    %{
      "name" => "type",
      "required" => true,
      "type" => "whatsappbusinessaccountmessage_samples_type_enum_param",
      "values" => ["INTERACTIVE", "TEXT"]
    }
  ])

  operation(:get_message_template_previews, "GET", "message_template_previews", nil, [
    %{"name" => "add_security_recommendation", "required" => false, "type" => "bool"},
    %{"name" => "business_name", "required" => false, "type" => "string"},
    %{
      "name" => "button_types",
      "required" => false,
      "type" => "list<whatsappbusinessaccountmessage_template_previews_button_types_enum_param>",
      "values" => ["OTP"]
    },
    %{
      "name" => "category",
      "required" => true,
      "type" => "whatsappbusinessaccountmessage_template_previews_category_enum_param",
      "values" => ["AUTHENTICATION"]
    },
    %{"name" => "code_expiration_minutes", "required" => false, "type" => "unsigned int"},
    %{"name" => "languages", "required" => false, "type" => "list<string>"}
  ])

  operation(:delete_message_templates, "DELETE", "message_templates", nil, [
    %{"name" => "hsm_id", "required" => false, "type" => "string"},
    %{"name" => "hsm_ids", "required" => false, "type" => "list<string>"},
    %{"name" => "name", "required" => false, "type" => "string"}
  ])

  operation(:get_message_templates, "GET", "message_templates", nil, [
    %{
      "name" => "category",
      "required" => false,
      "type" => "list<whatsappbusinessaccountmessage_templates_category_enum_param>",
      "values" => ["AUTHENTICATION", "MARKETING", "UTILITY"]
    },
    %{"name" => "content", "required" => false, "type" => "string"},
    %{"name" => "language", "required" => false, "type" => "list<string>"},
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "name_or_content", "required" => false, "type" => "string"},
    %{
      "name" => "quality_score",
      "required" => false,
      "type" => "list<whatsappbusinessaccountmessage_templates_quality_score_enum_param>",
      "values" => ["GREEN", "RED", "UNKNOWN", "YELLOW"]
    },
    %{"name" => "since", "required" => false, "type" => "datetime"},
    %{
      "name" => "source",
      "required" => false,
      "type" => "whatsappbusinessaccountmessage_templates_source_enum_param",
      "values" => ["AUTO_GENERATED", "MANUAL"]
    },
    %{
      "name" => "status",
      "required" => false,
      "type" => "list<whatsappbusinessaccountmessage_templates_status_enum_param>",
      "values" => [
        "APPROVED",
        "ARCHIVED",
        "DELETED",
        "DISABLED",
        "IN_APPEAL",
        "LIMIT_EXCEEDED",
        "PAUSED",
        "PENDING",
        "PENDING_DELETION",
        "REJECTED"
      ]
    },
    %{"name" => "until", "required" => false, "type" => "datetime"}
  ])

  operation(:create_message_templates, "POST", "message_templates", nil, [
    %{"name" => "allow_category_change", "required" => false, "type" => "bool"},
    %{
      "name" => "category",
      "required" => false,
      "type" => "whatsappbusinessaccountmessage_templates_category_enum_param",
      "values" => ["AUTHENTICATION", "MARKETING", "UTILITY"]
    },
    %{"name" => "components", "required" => false, "type" => "list<map>"},
    %{"name" => "creative_sourcing_spec", "required" => false, "type" => "map"},
    %{"name" => "cta_url_link_tracking_opted_out", "required" => false, "type" => "bool"},
    %{"name" => "degrees_of_freedom_spec", "required" => false, "type" => "map"},
    %{
      "name" => "display_format",
      "required" => false,
      "type" => "whatsappbusinessaccountmessage_templates_display_format_enum_param",
      "values" => ["ORDER_DETAILS"]
    },
    %{"name" => "is_primary_device_delivery_only", "required" => false, "type" => "bool"},
    %{"name" => "language", "required" => false, "type" => "string"},
    %{"name" => "library_template_body_inputs", "required" => false, "type" => "map"},
    %{"name" => "library_template_body_param_inputs", "required" => false, "type" => "list<map>"},
    %{"name" => "library_template_button_inputs", "required" => false, "type" => "list<map>"},
    %{"name" => "library_template_name", "required" => false, "type" => "string"},
    %{"name" => "message_send_ttl_seconds", "required" => false, "type" => "unsigned int"},
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "optimization_spec", "required" => false, "type" => "map"},
    %{
      "name" => "parameter_format",
      "required" => false,
      "type" => "whatsappbusinessaccountmessage_templates_parameter_format_enum_param",
      "values" => ["NAMED", "POSITIONAL"]
    },
    %{"name" => "product_set_id", "required" => false, "type" => "string"},
    %{
      "name" => "send_type",
      "required" => false,
      "type" => "whatsappbusinessaccountmessage_templates_send_type_enum_param",
      "values" => ["CAMPAIGN", "DIRECT", "TRIGGER"]
    },
    %{"name" => "source_template_id", "required" => false, "type" => "unsigned int"},
    %{
      "name" => "sub_category",
      "required" => false,
      "type" => "whatsappbusinessaccountmessage_templates_sub_category_enum_param",
      "values" => ["ORDER_DETAILS", "ORDER_STATUS", "RICH_ORDER_STATUS"]
    }
  ])

  operation(:create_migrate_flows, "POST", "migrate_flows", nil, [
    %{"name" => "source_flow_names", "required" => false, "type" => "list<string>"},
    %{"name" => "source_waba_id", "required" => true, "type" => "string"}
  ])

  operation(:create_migrate_message_templates, "POST", "migrate_message_templates", nil, [
    %{"name" => "count", "required" => false, "type" => "unsigned int"},
    %{"name" => "page_number", "required" => false, "type" => "unsigned int"},
    %{"name" => "source_waba_id", "required" => true, "type" => "string"},
    %{"name" => "template_ids", "required" => false, "type" => "list<string>"}
  ])

  operation(:delete_payment_configuration, "DELETE", "payment_configuration", nil, [
    %{"name" => "configuration_name", "required" => true, "type" => "string"}
  ])

  operation(:get_payment_configuration, "GET", "payment_configuration", nil, [
    %{"name" => "configuration_name", "required" => true, "type" => "string"}
  ])

  operation(:create_payment_configuration, "POST", "payment_configuration", nil, [
    %{"name" => "configuration_name", "required" => true, "type" => "string"},
    %{"name" => "data_endpoint_url", "required" => false, "type" => "string"},
    %{"name" => "merchant_category_code", "required" => false, "type" => "string"},
    %{"name" => "merchant_vpa", "required" => false, "type" => "string"},
    %{
      "name" => "provider_name",
      "required" => false,
      "type" => "whatsappbusinessaccountpayment_configuration_provider_name_enum_param",
      "values" => ["BILLDESK", "PAYU", "RAZORPAY", "UPI_VPA", "ZAAKPAY"]
    },
    %{"name" => "purpose_code", "required" => false, "type" => "string"},
    %{"name" => "redirect_url", "required" => false, "type" => "string"}
  ])

  operation(:get_payment_configurations, "GET", "payment_configurations", nil, [])
  operation(:get_phone_numbers, "GET", "phone_numbers", nil, [])

  operation(:create_phone_numbers, "POST", "phone_numbers", nil, [
    %{"name" => "cc", "required" => false, "type" => "string"},
    %{"name" => "migrate_phone_number", "required" => false, "type" => "bool"},
    %{"name" => "phone_number", "required" => false, "type" => "string"},
    %{"name" => "preverified_id", "required" => false, "type" => "string"},
    %{"name" => "verified_name", "required" => false, "type" => "string"}
  ])

  operation(:get_pricing_analytics, "GET", "pricing_analytics", nil, [
    %{"name" => "country_codes", "required" => false, "type" => "list<string>"},
    %{
      "name" => "dimensions",
      "required" => false,
      "type" => "list<whatsappbusinessaccountpricing_analytics_dimensions_enum_param>",
      "values" => ["COUNTRY", "PHONE", "PRICING_CATEGORY", "PRICING_TYPE", "TIER"]
    },
    %{"name" => "end", "required" => true, "type" => "unsigned int"},
    %{
      "name" => "granularity",
      "required" => true,
      "type" => "whatsappbusinessaccountpricing_analytics_granularity_enum_param",
      "values" => ["DAILY", "HALF_HOUR", "MONTHLY"]
    },
    %{
      "name" => "metric_types",
      "required" => false,
      "type" => "list<whatsappbusinessaccountpricing_analytics_metric_types_enum_param>",
      "values" => ["COST", "VOLUME"]
    },
    %{"name" => "phone_numbers", "required" => false, "type" => "list<string>"},
    %{
      "name" => "pricing_categories",
      "required" => false,
      "type" => "list<whatsappbusinessaccountpricing_analytics_pricing_categories_enum_param>",
      "values" => [
        "AI_BOT",
        "AUTHENTICATION",
        "AUTHENTICATION_INTERNATIONAL",
        "GROUP_MARKETING",
        "GROUP_MARKETING_LITE",
        "GROUP_SERVICE",
        "GROUP_UTILITY",
        "MARKETING",
        "MARKETING_LITE",
        "MARKETING_LITE_DYNAMIC",
        "SERVICE",
        "UTILITY"
      ]
    },
    %{
      "name" => "pricing_types",
      "required" => false,
      "type" => "list<whatsappbusinessaccountpricing_analytics_pricing_types_enum_param>",
      "values" => [
        "FREE_CUSTOMER_SERVICE",
        "FREE_ENTRY_POINT",
        "FREE_GROUP_CUSTOMER_SERVICE",
        "REGULAR"
      ]
    },
    %{"name" => "start", "required" => true, "type" => "unsigned int"},
    %{"name" => "tiers", "required" => false, "type" => "list<string>"}
  ])

  operation(:delete_product_catalogs, "DELETE", "product_catalogs", nil, [
    %{"name" => "catalog_id", "required" => true, "type" => "string"}
  ])

  operation(:get_product_catalogs, "GET", "product_catalogs", nil, [])

  operation(:create_product_catalogs, "POST", "product_catalogs", nil, [
    %{"name" => "catalog_id", "required" => true, "type" => "string"}
  ])

  operation(:get_schedules, "GET", "schedules", nil, [])

  operation(:create_set_solution_migration_intent, "POST", "set_solution_migration_intent", nil, [
    %{"name" => "app_id", "required" => false, "type" => "string"},
    %{"name" => "solution_id", "required" => false, "type" => "string"}
  ])

  operation(:get_solutions, "GET", "solutions", nil, [])
  operation(:delete_subscribed_apps, "DELETE", "subscribed_apps", nil, [])
  operation(:get_subscribed_apps, "GET", "subscribed_apps", nil, [])

  operation(:create_subscribed_apps, "POST", "subscribed_apps", nil, [
    %{"name" => "override_callback_uri", "required" => false, "type" => "string"},
    %{"name" => "verify_token", "required" => false, "type" => "string"}
  ])

  operation(:get_template_analytics, "GET", "template_analytics", nil, [
    %{"name" => "end", "required" => true, "type" => "datetime"},
    %{
      "name" => "granularity",
      "required" => true,
      "type" => "whatsappbusinessaccounttemplate_analytics_granularity_enum_param",
      "values" => ["DAILY"]
    },
    %{"name" => "metric_types", "required" => false, "type" => "list<string>"},
    %{
      "name" => "product_type",
      "required" => false,
      "type" => "whatsappbusinessaccounttemplate_analytics_product_type_enum_param",
      "values" => ["CAMPAIGN_INSIGHTS", "CLOUD_API", "MARKETING_MESSAGES_LITE_API"]
    },
    %{"name" => "start", "required" => true, "type" => "datetime"},
    %{"name" => "template_ids", "required" => true, "type" => "list<string>"},
    %{"name" => "use_waba_timezone", "required" => false, "type" => "bool"}
  ])

  operation(:get_template_group_analytics, "GET", "template_group_analytics", nil, [
    %{"name" => "end", "required" => true, "type" => "datetime"},
    %{
      "name" => "granularity",
      "required" => true,
      "type" => "whatsappbusinessaccounttemplate_group_analytics_granularity_enum_param",
      "values" => ["DAILY"]
    },
    %{"name" => "metric_types", "required" => false, "type" => "list<string>"},
    %{"name" => "start", "required" => true, "type" => "datetime"},
    %{"name" => "template_group_ids", "required" => true, "type" => "list<string>"},
    %{"name" => "use_waba_timezone", "required" => false, "type" => "bool"}
  ])

  operation(:get_template_groups, "GET", "template_groups", nil, [])

  operation(:create_template_groups, "POST", "template_groups", nil, [
    %{"name" => "description", "required" => true, "type" => "string"},
    %{"name" => "name", "required" => true, "type" => "string"},
    %{"name" => "whatsapp_business_templates", "required" => true, "type" => "list<string>"}
  ])

  operation(:create_upsert_message_templates, "POST", "upsert_message_templates", nil, [
    %{
      "name" => "category",
      "required" => true,
      "type" => "whatsappbusinessaccountupsert_message_templates_category_enum_param",
      "values" => ["AUTHENTICATION"]
    },
    %{"name" => "components", "required" => true, "type" => "list<map>"},
    %{"name" => "languages", "required" => true, "type" => "list<string>"},
    %{"name" => "message_send_ttl_seconds", "required" => false, "type" => "unsigned int"},
    %{"name" => "name", "required" => true, "type" => "string"}
  ])

  operation(:delete_welcome_message_sequences, "DELETE", "welcome_message_sequences", nil, [
    %{"name" => "sequence_id", "required" => true, "type" => "string"}
  ])

  operation(:get_welcome_message_sequences, "GET", "welcome_message_sequences", nil, [
    %{"name" => "app_id", "required" => false, "type" => "string"},
    %{"name" => "sequence_id", "required" => false, "type" => "string"}
  ])

  operation(:create_welcome_message_sequences, "POST", "welcome_message_sequences", nil, [
    %{"name" => "name", "required" => false, "type" => "string"},
    %{"name" => "sequence_id", "required" => false, "type" => "string"},
    %{"name" => "welcome_message_sequence", "required" => false, "type" => "Object"}
  ])

  operation(:get, "GET", "", nil, [])

  operation(:create, "POST", "", nil, [
    %{"name" => "creative_optimizations_enrollment", "required" => false, "type" => "map"},
    %{"name" => "degrees_of_freedom_spec", "required" => false, "type" => "map"},
    %{"name" => "disable_marketing_messages_on_cloud_api", "required" => false, "type" => "bool"},
    %{"name" => "is_enabled_for_insights", "required" => false, "type" => "bool"},
    %{"name" => "template_auto_archival_enabled", "required" => false, "type" => "bool"},
    %{
      "name" => "whatsapp_manager_marketing_messages_max_price_enroll_status",
      "required" => false,
      "type" =>
        "whatsappbusinessaccount_whatsapp_manager_marketing_messages_max_price_enroll_status",
      "values" => ["OPT_IN", "OPT_OUT"]
    }
  ])

  finish()
end
