# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WhatsAppBusinessPreVerifiedPhoneNumber do
  use MetaAds.Model

  field(
    "code_verification_status",
    "WhatsAppBusinessPreVerifiedPhoneNumber_code_verification_status",
    ["EXPIRED", "NOT_VERIFIED", "VERIFIED"]
  )

  field("code_verification_time", "datetime", [])
  field("id", "string", [])
  field("owner_business", "Business", [])
  field("phone_number", "string", [])
  field("verification_expiry_time", "datetime", [])

  operation(:get_partners, "GET", "partners", nil, [])

  operation(:create_request_code, "POST", "request_code", nil, [
    %{
      "name" => "code_method",
      "required" => true,
      "type" => "whatsappbusinesspreverifiedphonenumberrequest_code_code_method_enum_param",
      "values" => ["IVR", "SMS", "VOICE"]
    },
    %{"name" => "language", "required" => true, "type" => "string"}
  ])

  operation(:create_verify_code, "POST", "verify_code", nil, [
    %{"name" => "code", "required" => true, "type" => "string"}
  ])

  operation(:delete, "DELETE", "", nil, [])
  operation(:get, "GET", "", nil, [])
  finish()
end
