# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WindowsAppLink do
  use MetaAds.Model

  field("app_id", "string", [])
  field("app_name", "string", [])
  field("package_family_name", "string", [])
  field("url", "string", [])

  finish()
end
