# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WorkAccessCode do
  use MetaAds.Model

  field("code", "string", [])
  field("expiration_time", "datetime", [])

  finish()
end
