# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WorkExperience do
  use MetaAds.Model

  field("description", "string", [])
  field("employer", "Page", [])
  field("end_date", "string", [])
  field("from", "User", [])
  field("id", "string", [])
  field("location", "Page", [])
  field("position", "Page", [])
  field("projects", "list<Object>", [])
  field("start_date", "string", [])
  field("with", "list<User>", [])

  operation(:get, "GET", "", nil, [])
  finish()
end
