# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WorkUserFrontline do
  use MetaAds.Model

  field("has_access", "bool", [])
  field("is_frontline", "bool", [])

  finish()
end
