# This file is generated by mix meta_ads.generate; manual edits will be lost.
defmodule MetaAds.Models.WorkUserBadges do
  use MetaAds.Model

  field("category", "string", [])
  field("description", "string", [])
  field("icon", "string", [])
  field("id", "string", [])
  field("name", "string", [])

  finish()
end
