defmodule Mix.Tasks.MetaAds.Generate do
  @shortdoc "Regenerates Meta Ads model modules"

  @moduledoc """
  Regenerates `lib/meta_ads/models` from Meta's Business SDK JSON schema.

  The default input is the vendored schema snapshot. Keeping a pinned snapshot
  makes package builds reproducible; updating it is an explicit schema upgrade,
  not a side effect of compilation.
  """

  use Mix.Task

  @default_specs "priv/codegen/specs"
  @output "lib/meta_ads/models"

  @impl Mix.Task
  def run(args) do
    {options, _argv, invalid} = OptionParser.parse(args, strict: [specs: :string])

    if invalid != [] do
      Mix.raise("Unexpected generator options: #{inspect(invalid)}")
    end

    project_root = File.cwd!()
    specs_path = Path.expand(options[:specs] || @default_specs, project_root)
    output_path = Path.join(project_root, @output)

    unless File.exists?(Path.join(project_root, "mix.exs")) do
      Mix.raise("Run this task from the meta_ads project root")
    end

    unless File.dir?(specs_path) do
      Mix.raise("Schema directory does not exist: #{specs_path}")
    end

    spec_files =
      specs_path
      |> Path.join("*.json")
      |> Path.wildcard()
      |> Enum.sort()

    enum_types = load_enum_types(specs_path)
    model_files = Enum.reject(spec_files, &String.ends_with?(&1, "/enum_types.json"))

    # The output is a derived, project-local directory; deleting it keeps stale
    # modules from surviving a schema contraction.
    File.rm_rf!(output_path)
    File.mkdir_p!(output_path)

    counts =
      Enum.reduce(model_files, %{models: 0, operations: 0, skipped: 0}, fn path, counts ->
        case JSON.decode(File.read!(path)) do
          {:ok, %{} = spec} ->
            {operation_count, skipped} = write_model!(output_path, path, spec, enum_types)

            %{
              counts
              | models: counts.models + 1,
                operations: counts.operations + operation_count,
                skipped: counts.skipped + skipped
            }

          {:ok, other} ->
            Mix.raise("Expected an object schema in #{path}, got: #{inspect(other)}")

          {:error, reason} ->
            Mix.raise("Invalid JSON in #{path}: #{inspect(reason)}")
        end
      end)

    Mix.shell().info(
      "Generated #{counts.models} models and #{counts.operations} operations; skipped #{counts.skipped} dynamic endpoint(s)"
    )

    output_path
    |> Path.join("**/*.ex")
    |> Path.wildcard()
    |> then(&Mix.Task.rerun("format", &1))
  end

  defp load_enum_types(specs_path) do
    path = Path.join(specs_path, "enum_types.json")

    if File.exists?(path) do
      case JSON.decode(File.read!(path)) do
        {:ok, enums} when is_list(enums) ->
          Map.new(enums, &{&1["name"], &1["values"]})

        _other ->
          Mix.raise("Invalid enum_types.json schema")
      end
    else
      %{}
    end
  end

  defp write_model!(output_path, path, spec, enum_types) do
    source_name = Path.rootname(Path.basename(path))
    module_name = Macro.camelize(source_name)
    file_name = Macro.underscore(module_name) <> ".ex"

    fields =
      spec
      |> Map.get("fields", [])
      |> Enum.map(fn field ->
        field_name = field["name"]
        type = field["type"]
        values = Map.get(enum_types, type, [])

        "  field #{inspect(field_name)}, #{inspect(type)}, #{literal(values)}"
      end)

    {operation_lines, {operation_count, skipped}} =
      spec
      |> Map.get("apis", [])
      |> Enum.map_reduce({0, 0}, fn api, {operation_count, skipped} ->
        endpoint = Map.get(api, "endpoint", "")

        if String.contains?(endpoint, "{") do
          {"", {operation_count, skipped + 1}}
        else
          base_path = Map.get(api, "basePath") || Map.get(api, "base_path")
          params = Enum.map(Map.get(api, "params", []), &param_with_values(&1, enum_types))
          # Macro escaping is used instead of inspect/1 because Mix truncates
          # deeply nested inspect output by default, which emits invalid source.
          params_literal = literal(params)

          line =
            "  operation #{inspect(function_name(api, endpoint))}, #{inspect(api["method"])}, " <>
              "#{inspect(endpoint)}, #{inspect(base_path)}, #{params_literal}"

          {line, {operation_count + 1, skipped}}
        end
      end)

    body =
      [
        "# This file is generated by mix meta_ads.generate; manual edits will be lost.",
        "defmodule MetaAds.Models.#{module_name} do",
        "  use MetaAds.Model"
      ] ++
        ["" | fields] ++
        ["" | operation_lines] ++
        ["  finish()", "end", ""]

    File.write!(Path.join(output_path, file_name), Enum.join(body, "\n"))
    {operation_count, skipped}
  end

  defp param_with_values(param, enum_types) do
    values = enum_values(param["type"], enum_types)
    if values, do: Map.put(param, "values", values), else: param
  end

  defp literal(term), do: term |> Macro.escape() |> Macro.to_string()

  defp enum_values("list<" <> rest = _type, enum_types) do
    inner_type = String.trim_trailing(rest, ">")
    values = Map.get(enum_types, inner_type)
    if values, do: values, else: nil
  end

  defp enum_values(type, enum_types) do
    Map.get(enum_types, type)
  end

  defp function_name(api, endpoint) do
    action =
      case api["method"] do
        "GET" -> "get"
        "POST" -> "create"
        "DELETE" -> "delete"
        "PUT" -> "update"
      end

    suffix =
      endpoint
      |> String.replace(~r/[^0-9A-Za-z_]+/, "_")
      |> String.downcase()
      |> String.trim("_")

    # Root-level custom operations all have an empty endpoint; Meta's generated
    # name is the only stable discriminator once basePath differs.
    suffix =
      case api["name"] do
        "gen" <> named when endpoint == "" -> named |> Macro.underscore() |> String.trim("_")
        _ -> suffix
      end

    if suffix == "", do: String.to_atom(action), else: String.to_atom(action <> "_" <> suffix)
  end
end
